### ISSUE TITLE
在0.0.1版本时，可以使用knext reasoner query来查询推理出来的结果（顶点、边、属性），但0.0.2版本，变成了 knext reasoner execute，会导致每次都要重新生成执行计划，导致查询访问的时间明显变长。请问是否有类似预计算的接口，以便于在上层应用访问时，可以快速直接“查询”出来结果？

### ISSUE THREAD

**Issue by w00125533** [OpenSPG/openspg#111]

**Comment by baifuyu** [comment]
@w00125533 非常感谢对OpenSPG的支持。在0.0.1版本中其实是在server端中将gql转化为执行计划并执行的。在0.0.2版本中，我们对OpenSPG的定位主要是图谱核心引擎框架，里面包含了builder、reasoner、schema、knext等，其中builder、reasoner都目前只提供了本地单机版的执行方式。

针对您提到的快速直接查询出来结果，我们内部使用目前有2种方式：

1. 部署一个内存常驻的进程，服务端将收到的gql直接丢给该进程计算并返回，这种方式可以减少启动进程的时间；
2. 还有一种方式是知识服务方式，将gql预编译成执行计划，提供在线服务查询；

目前已开源版本中的builder、schema、knext能力还不够完善，我们将在完善当前已开源版本的基础上，再去开源其他内容，也欢迎讨论共建~

**Comment by w00125533** [comment]
部署一个内存常驻的进程，服务端将收到的gql直接丢给该进程计算并返回，这种方式可以减少启动进程的时间；
还有一种方式是知识服务方式，将gql预编译成执行计划，提供在线服务查询；

**Comment by baifuyu** [comment]
> 针对你所说的两种方式，我如何操作能达到这两个目的，能否给个简单的样例指导？ """ 针对您提到的快速直接查询出来结果，我们内部使用目前有2种方式： 1.部署一个内存常驻的进程，服务端将收到的gql直接丢给该进程计算并返回，这种方式可以减少启动进程的时间； 2.还有一种方式是知识服务方式，将gql预编译成执行计划，提供在线服务查询； """

这2种方式暂时都还不支持，目前开源部分只支持单机本地版的推理。第一种方式我们将在下一版支持（预计3月底），可以在服务端执行推理。第二种方式目前还没有开源计划。

**Comment by w00125533** [comment]
好的，感谢并期待~

另外，顺带问一下，当前仅支持了单机本地推理，分布式的推理能力是否有开源的时间计划？

**Comment by baifuyu** [comment]
> 好的，感谢并期待~
> 
> 另外，顺带问一下，当前仅支持了单机本地推理，分布式的推理能力是否有开源的时间计划？

分布式的推理能力目前蚂蚁内部实现了内部计算引擎的适配。开源的计算引擎适配可以参考 https://openspg.yuque.com/ndx6g9/ooil9x/qrdqadbrug0ty7xp 这边文章提到的 RDG 适配，但目前还是伪代码的方式
