### ISSUE TITLE
在构建有互相依赖的实体时，违反了Schema的“父类型要在子类型之前定义”约束，这种情况下，怎么建立互相依赖的双向关联关系？

### ISSUE THREAD

**Issue by w00125533** [OpenSPG/openspg#112]
例如有以下Schema，
Son(子): EntityType
	properties:
		father(父亲): Father		

Father(父): EntityType
	properties:
		son（儿子）: Son

![image](https://github.com/OpenSPG/openspg/assets/22139807/c9aba200-bb4f-46ab-9df1-182e00fb536f)

但是执行时报错，查阅文档是有这个约束：
![image](https://github.com/OpenSPG/openspg/assets/22139807/b765bdb6-f644-4fc3-8538-699ed733b8df)

请问，用什么方式构造类似这种关系~

**Comment by matthewhyx** [comment]
您好，目前通过客户端确实无法建立这种关系，将在下个迭代里解决。在此之前，您可以先建立单向关系，查询的时候以单向关系的终点作为起点，查入边方向解决反向查询的问题。
