### ISSUE TITLE
supplychain实例中，在使用concept.rule构建边的时候，concept.rule中action中定义的是(s:`TaxOfProdEvent`/`价格上涨`)-[p:leadTo]->(o:`CompanyEvent`/`成本上升事件`)，最终效果为何是(s:`ProductChainEvent`/`价格上涨`)-[p:leadTo]->(o:`CompanyEvent`/`成本上升事件`)？

### ISSUE THREAD

**Issue by billc114** [OpenSPG/openspg#123]
代码位置：
python/knext/knext/examples/supplychain/schema/concept.rule
```
`TaxOfProdEvent`/`价格上涨`:TaxOfCompanyEvent/`成本上涨`
    rule: [[
        Define (s:`TaxOfProdEvent`/`价格上涨`)-[p:leadTo]->(o:`TaxOfCompanyEvent`/`成本上涨`) {
            Structure {
                (s)-[:subject]->(prod:Product)-[:hasSupplyChain]->(down:Product)<-[:product]-(c:Company)
            }
            Constraint {
            eventName = concat(c.name, "成本上升事件")
            }
            Action {
                downEvent = createNodeInstance(
                    type=CompanyEvent,
                    value = {
                        subject=c.id
                        name=eventName
                        trend="上涨"
                        index="成本"
                    }
                )
                createEdgeInstance(
                    src=s,
                    dst=downEvent,
                    type=leadTo,
                    value={}
                )
            }
        }
    ]]
```
求解答~

**Comment by billc114** [comment]
查询时关联的边是(s:SupplyChain.ProductChainEvent)-[:leadTo]->(o:SupplyChain.CompanyEvent)：
![image](https://github.com/OpenSPG/openspg/assets/52943316/6d7feaf8-194d-4b74-922f-acd6deb26427)

**Comment by royzhao** [comment]
![image](https://github.com/OpenSPG/openspg/assets/5119000/0df3653a-b25a-4dce-b68e-4e366207071b)
参见上图
在事件推理中，存在两个维度
第一个是事理维度，这个是抽象的事件之间的关联，比如(价格上涨)-[leadTo]->(成本上升)
第二个是事件维度，这个是具体的事件及其关联，比如(A公司产品价格上涨)-[leadTo]->(B公司产品成本上升)
在实际的应用中，查询侧一般只关心事件维度，某个具体事件会导致什么后果，但是事件的影响是由事理层定义
所以在concept.rule中，我们定义了抽象的事理关系
`Define` (s:`TaxOfProdEvent`/`价格上涨`)-[p:leadTo]->(o:`TaxOfCompanyEvent`/`成本上涨`)
在规则的Action部分，createNodeInstance是创建了一个新的事件实例，并且通过createEdgeInstance将两个具体事件ProdEvent和CompanyEvent进行关联，类型为leadTo，这个也是为什么最终查询的时候，能够直接匹配具体事件。
此外
TaxOfProdEvent、TaxOfCompanyEvent这两个类型是ProdEvent和CompanyEvent的一个分类概念，我们在规则系统中此类分类概念可以作为类型存在直接使用，例如`TaxOfProdEvent`/`价格上涨`就表示一个具体的类型，但指向的数据还是ProdEvent，有点类似标签分类

**Comment by billc114** [comment]
> ![image](https://private-user-images.githubusercontent.com/5119000/305775925-fd768a59-dbb2-4a2d-82ca-108cc35648c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTMxOTIsIm5iZiI6MTcwODMxMjg5MiwicGF0aCI6Ii81MTE5MDAwLzMwNTc3NTkyNS1mZDc2OGE1OS1kYmIyLTRhMmQtODJjYS0xMDhjYzM1NjQ4YzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTlUMDMyMTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWY0Y2I2Njg3MjdmYzBjNDA4NDUzZTZjOWYzODViMzE5ZDIzYzJiOTYxOGJhY2VmMGMwNDBiODRkYmNkZTc4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6CMNgdwGLswsGwH6ZYVDgWu7dnQqoYm6VxAYJ6FZ9lw)
> 
> 参见上图 在事件推理中，存在两个维度 第一个是事理维度，这个是抽象的事件之间的关联，比如(价格上涨)-[leadTo]->(成本上升) 第二个是事件维度，这个是具体的事件及其关联，比如(A公司产品价格上涨)-[leadTo]->(B公司产品成本上升) 在实际的应用中，查询侧一般只关心事件维度，某个具体事件会导致什么后果，但是事件的影响是由事理层定义 所以在concept.rule中，我们定义了抽象的事理关系 `Define` (s:`TaxOfProdEvent`/`价格上涨`)-[p:leadTo]->(o:`TaxOfCompanyEvent`/`成本上涨`) 在规则的Action部分，createNodeInstance是创建了一个新的事件实例，并且通过createEdgeInstance将两个具体事件ProdEvent和CompanyEvent进行关联，类型为leadTo，这个也是为什么最终查询的时候，能够直接匹配具体事件。 此外 TaxOfProdEvent、TaxOfCompanyEvent这两个类型是ProdEvent和CompanyEvent的一个分类概念，我们在规则系统中此类分类概念可以作为类型存在直接使用，例如`TaxOfProdEvent`/`价格上涨`就表示一个具体的类型，但指向的数据还是ProdEvent，有点类似标签分类

感谢解答！
分成两个维度的思想之前没理解到
