### ISSUE TITLE
关于使用riskmining运行时的错误

### ISSUE THREAD

**Issue by zhui6688** [OpenSPG/openspg#124]
我在使用案例riskmining运行knext schema commit时，会有下面错误：
![image](https://github.com/OpenSPG/openspg/assets/38718591/899738b3-97c3-4d52-8030-bd3987b87baf)
为什么？

出错后，再次运行knext schema commit时，会有下面错误：
![image](https://github.com/OpenSPG/openspg/assets/38718591/c2386bdb-0d40-4834-a6ef-d831d5e4d988)
如何解决？

**Comment by baifuyu** [comment]
> 我在使用案例riskmining运行knext schema commit时，会有下面错误： ![image](https://private-user-images.githubusercontent.com/38718591/306125219-899738b3-97c3-4d52-8030-bd3987b87baf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzA5MDcsIm5iZiI6MTcwODQzMDYwNywicGF0aCI6Ii8zODcxODU5MS8zMDYxMjUyMTktODk5NzM4YjMtOTdjMy00ZDUyLTgwMzAtYmQzOTg3Yjg3YmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDEyMDMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MWJjZjc1NGE5NTNiZDJjMzVmYjY1Yjc1YWQwYTMxMTljMjRjNDRiMzdhZWNjNzBjODdkNDNhMTQ0MDY4OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9f-jdn4iglOGsJoKYGzZRYcQezvXcXWKgTKi24z7sE4) 为什么？
> 
> 出错后，再次运行knext schema commit时，会有下面错误： ![image](https://private-user-images.githubusercontent.com/38718591/306126446-c2386bdb-0d40-4834-a6ef-d831d5e4d988.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzA5MDcsIm5iZiI6MTcwODQzMDYwNywicGF0aCI6Ii8zODcxODU5MS8zMDYxMjY0NDYtYzIzODZiZGItMGQ0MC00ODM0LWE2ZWYtZDgzMWQ1ZTRkOTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDEyMDMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4YjE1ZTQ2ZWJkNmExMDgzYWRmODA1OGY3MTkwNThmYWUwNzIwYjU0NWY2NWYyMWY1ZjU0MWJhMTI1Y2FiYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VaHSXTQfEfi9eqXJXNgAEOB4m7WRXtPjxCcC03MzzsQ) 如何解决？

本地执行下 docker ps 命令看下es是否正常启动的，如果非正常启动可以执行下 docker logs [容器Id] 看下错误日志，这里的报错还没那么友好。

第二个问题确认下是否本地有其他文本编辑器打开了 riskmining_schema_helper.py 文件，导致本地多了 riskmining_schema_helper.py.tmpl，如果没有的话，可以删除这2个文件重试下

**Comment by zhui6688** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，该回复仅表明本人已收到此邮件，并不代表本人已查看过邮件。我将查看邮件后，亲自回复您的邮件！！谢谢

**Comment by zhui6688** [comment]
1、使用docker ps运行了，es正常启动了。如下图：
![image](https://github.com/OpenSPG/openspg/assets/38718591/db4f158a-df1e-492b-92c5-b53ffff094ef)

2、删除了riskmining_schema_helper.py与riskmining_schema_helper.py.tmpl文件，但是会报错。如下图：
![image](https://github.com/OpenSPG/openspg/assets/38718591/a07b3a18-b5e3-41fe-a14a-672de869c6c7)

3、我用自定义项目命令来操作，也会报错，如下图：
![image](https://github.com/OpenSPG/openspg/assets/38718591/397a1cdc-7297-4539-92a3-5868b9f030bc)

4、目前，无论是否出错，服务端都会创建项目，但项目都无法删除，应该如何处理？如下图
![image](https://github.com/OpenSPG/openspg/assets/38718591/a8276c72-0dcb-4231-875a-a1806362ec82)

5、在创建自定义项目，若使用相同的namespace时会报错，namespace都不能相同吗？若是，那namespace不是没意义了？
![image](https://github.com/OpenSPG/openspg/assets/38718591/f899c635-37b6-4e77-820b-ea15b7ee7414)

**Comment by baifuyu** [comment]
> 1、使用docker ps运行了，es正常启动了。如下图： ![image](https://private-user-images.githubusercontent.com/38718591/306269290-db4f158a-df1e-492b-92c5-b53ffff094ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODQzNzgsIm5iZiI6MTcwODQ4NDA3OCwicGF0aCI6Ii8zODcxODU5MS8zMDYyNjkyOTAtZGI0ZjE1OGEtZGYxZS00OTJiLTkyYzUtYjUzZmZmZjA5NGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAyNTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjODY0ZDQ0NjA0Y2ExODEwOTAyYTZlNTllNzliNjM1Njc1MWZhNTZhOTQ4YjhmN2MxMjBlNDg4YjdkYjkxMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TA7xU6tFp0FB6nE4gWITURkvMZrliZW0TAPCTnJGHjo)
> 
> 2、删除了riskmining_schema_helper.py与riskmining_schema_helper.py.tmpl文件，但是会报错。如下图： ![image](https://private-user-images.githubusercontent.com/38718591/306269986-a07b3a18-b5e3-41fe-a14a-672de869c6c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODQzNzgsIm5iZiI6MTcwODQ4NDA3OCwicGF0aCI6Ii8zODcxODU5MS8zMDYyNjk5ODYtYTA3YjNhMTgtYjVlMy00MWZlLWExNGEtNjcyZGU4NjljNmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAyNTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZmYyNzMwNTM2NTdlZGE1OTVlZmQ5ZDJjMjJlNWI3Yjg3NWY3ZmFmOGE3Y2ViMTlkM2ZlY2VhMWM4ZTdlOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OPTpfYXt8Z9IsB5aBF0lsZWCdbhH-uLSfD7XnncQj8U)
> 
> 3、我用自定义项目命令来操作，也会报错，如下图： ![image](https://private-user-images.githubusercontent.com/38718591/306270808-397a1cdc-7297-4539-92a3-5868b9f030bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODQzNzgsIm5iZiI6MTcwODQ4NDA3OCwicGF0aCI6Ii8zODcxODU5MS8zMDYyNzA4MDgtMzk3YTFjZGMtNzI5Ny00NTM5LTkyYTMtNTg2OGI5ZjAzMGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAyNTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YmI2ODRhODhiOWM1YzA4NmQxMmU5OWU0NzA0MTk3YjAzYzU1NDQzMmJkNTE5ZTMzYmZkMDhlY2E0NzY1OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WVw4thMMlwQX_Fgx3m347KOK-0PzoqFb2UDUmLamg6I)
> 
> 4、目前，无论是否出错，服务端都会创建项目，但项目都无法删除，应该如何处理？如下图 ![image](https://private-user-images.githubusercontent.com/38718591/306271185-a8276c72-0dcb-4231-875a-a1806362ec82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODQzNzgsIm5iZiI6MTcwODQ4NDA3OCwicGF0aCI6Ii8zODcxODU5MS8zMDYyNzExODUtYTgyNzZjNzItMGRjYi00MjMxLTg3NWEtYTE4MDYzNjJlYzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAyNTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MDU4YjRkYjYxOWM1Yzc4NDQ0NTMyNDQ0NDRmZWNjZTllNzc2YWRkZjg0ZWVmY2QwMTkwMjgxZTY5ZTM3NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J9CYcEoTtXn4eMPMWpLXRScKj64DfRPGWjHRfKPFfzE)
> 
> 5、在创建自定义项目，若使用相同的namespace时会报错，namespace都不能相同吗？若是，那namespace不是没意义了？ ![image](https://private-user-images.githubusercontent.com/38718591/306272201-f899c635-37b6-4e77-820b-ea15b7ee7414.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODQzNzgsIm5iZiI6MTcwODQ4NDA3OCwicGF0aCI6Ii8zODcxODU5MS8zMDYyNzIyMDEtZjg5OWM2MzUtMzdiNi00ZTc3LTgyMGItZWExNWI3ZWU3NDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAyNTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MTQ2ODZiY2ExNzcyMGY5NTYxNzY0ZDg0ZjFkMTRlOGExZDkzYzkwMjExMDZkMTE1ZjQzNzg3YTBiYjE2ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.olJ_Mdjmuu0pZ7jlEuaXImzGAEmr-UZrxG7eypd-a5I)

hi 帮忙确认下是否是这种方式安装的openspg，目前已经测试的这种方式安装是可行的。https://openspg.yuque.com/ndx6g9/ooil9x/xht6kkegvs33cwwr。从上面的报错信息来看，knext客户端的安装方式不是使用docker安装的。

项目目前暂时不支持删除，namespace跟随着项目走，一般而言一个项目一个namespace。

**Comment by zhui6688** [comment]
解决了，是knext客户端的docker没有启动的问题。主要是这个命令没搞明白：

# 启动容器，将其中的${project_dir}替换成源码目录
docker run --rm --net=host -v ${project_dir}:/code \
  -it openspg/openspg-python:latest \
  "/bin/bash"

这个命令的作用是启动一个新的Docker容器，该容器具有我们创建的项目目录，并在该容器中启动一个bash shell。这样，我们就可以在这个bash shell中运行命令，就像自己主机上一样。

![Uploading image.png…]()
上面是操作成功的界面，这个操作流程和原来0.01的版本不一样。
