### ISSUE TITLE
起docker服务后，使用knext命名报错 ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by xiaoshan0609** [OpenSPG/openspg#126]
Traceback (most recent call last):
  File "/openspg_venv/bin/knext", line 5, in <module>
    from knext.command.knext_cli import _main
  File "/openspg_venv/lib/python3.8/site-packages/knext/__init__.py", line 18, in <module>
    init_env()
  File "/openspg_venv/lib/python3.8/site-packages/knext/common/env.py", line 60, in init_env
    load_operator()
  File "/openspg_venv/lib/python3.8/site-packages/knext/common/env.py", line 135, in load_operator
    register_from_package(builder_operator_path, BaseOp)
  File "/openspg_venv/lib/python3.8/site-packages/knext/common/class_register.py", line 52, in register_from_package
    _register(path, root, files, class_type)
  File "/openspg_venv/lib/python3.8/site-packages/knext/common/class_register.py", line 29, in _register
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ValueError: source code string cannot contain null bytes

**Comment by baifuyu** [comment]
> Traceback (most recent call last): File "/openspg_venv/bin/knext", line 5, in from knext.command.knext_cli import _main File "/openspg_venv/lib/python3.8/site-packages/knext/**init**.py", line 18, in init_env() File "/openspg_venv/lib/python3.8/site-packages/knext/common/env.py", line 60, in init_env load_operator() File "/openspg_venv/lib/python3.8/site-packages/knext/common/env.py", line 135, in load_operator register_from_package(builder_operator_path, BaseOp) File "/openspg_venv/lib/python3.8/site-packages/knext/common/class_register.py", line 52, in register_from_package _register(path, root, files, class_type) File "/openspg_venv/lib/python3.8/site-packages/knext/common/class_register.py", line 29, in _register module = importlib.import_module(module_name) File "/usr/lib/python3.8/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) ValueError: source code string cannot contain null bytes

hi有更多的上下文信息不？比如是否按照官网的方式安装的openspg，以及是否执行了源码里面的example，以及是否对源码有改动呢

**Comment by xiaoshan0609** [comment]
> > Traceback (most recent call last): File "/openspg_venv/bin/knext", line 5, in from knext.command.knext_cli import _main File "/openspg_venv/lib/python3.8/site-packages/knext/**init**.py", line 18, in init_env() File "/openspg_venv/lib/python3.8/site-packages/knext/common/env.py", line 60, in init_env load_operator() File "/openspg_venv/lib/python3.8/site-packages/knext/common/env.py", line 135, in load_operator register_from_package(builder_operator_path, BaseOp) File "/openspg_venv/lib/python3.8/site-packages/knext/common/class_register.py", line 52, in register_from_package _register(path, root, files, class_type) File "/openspg_venv/lib/python3.8/site-packages/knext/common/class_register.py", line 29, in _register module = importlib.import_module(module_name) File "/usr/lib/python3.8/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) ValueError: source code string cannot contain null bytes
> 
> hi有更多的上下文信息不？比如是否按照官网的方式安装的openspg，以及是否执行了源码里面的example，以及是否对源码有改动呢

其他example可以执行，就自己新建的project不能执行
