### ISSUE TITLE
ERROR: com.antgroup.tugraph.TuGraphDbRpcException: KvException: MDB_DBS_FULL: Environment maxdbs limit reached

### ISSUE THREAD

**Issue by zhangcongxiao** [OpenSPG/openspg#13]
ERROR: com.antgroup.tugraph.TuGraphDbRpcException: KvException: MDB_DBS_FULL: Environment maxdbs limit reached
这个报错是什么原因，有设置最大db数的参数吗，另外删除db的命令是什么

**Comment by J4ckycjl** [comment]
@zhangcongxiao 您好！

OpenSPG项目底层依赖开源图数据库TuGraph，这个报错的可能原因有两种：
1、TuGraph中的图实例（即您提及的“db”）数量过多，当前集成的TuGraph版本仅支持创建不超过255个图实例。
2、TuGraph中的单个图实例中Label数量过多，当前集成的TuGraph版本近支持创建不超过255个Label。
经过沟通，预计TuGraph将在下个版本将图数量上限调整为4096，将类型数量上限调整为1024。OpenSPG将在TuGraph新版本稳定后进行适配升级。

OpenSPG不提供直接操作底层图数据库的能力接口。不支持删除图实例操作。但可以对图实例进行手动清除。如下图所示，可以登陆TuGraph的前端页面([http://localhost:7070])后，点击待删图实例后的按钮，管理员账号为：admin，密码为73@TuGraph。
![image](https://github.com/OpenSPG/openspg/assets/152955942/c7e880a3-5f81-4720-ae34-741262d38b24)

PS：如删除名为“default“的图实例，需要重建一个同名的图实例，因为目前OpenSPG直接依赖该图实例来提供相关服务

**Comment by zhangcongxiao** [comment]
感谢解答

**Comment by zhangcongxiao** [comment]
我记得这个问题当时说是这样的，这个会在一月份版本带入吗
![image](https://github.com/OpenSPG/openspg/assets/46892331/2f3785e8-e485-4258-8565-f79d216195a5)

**Comment by baifuyu** [comment]
> 我记得这个问题当时说是这样的，这个会在一月份版本带入吗 ![image](https://private-user-images.githubusercontent.com/46892331/293198179-2f3785e8-e485-4258-8565-f79d216195a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MzQ1OTAsIm5iZiI6MTcwMzgzNDI5MCwicGF0aCI6Ii80Njg5MjMzMS8yOTMxOTgxNzktMmYzNzg1ZTgtZTQ4NS00MjU4LTg1NjUtZjc5ZDIxNjE5NWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDA3MTgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzZTBhMDFkOGQyNWI4OWNjMGI1ZWJjOWRiNmFkYmU4YzYzYjExNjExODEzYzc4NWUzM2FlMTg1YzQzNGJjNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kQvrHXubDb5GfRMg63_mp5tbo9bDtAda6BOPHxVlEQ8)

是的。我们将在1月初的时候发布一版修复这些问题，欢迎届时关注
