### ISSUE TITLE
关于riskmining案例代码的一些疑问

### ISSUE THREAD

**Issue by zhui6688** [OpenSPG/openspg#130]
1.关于CompanyHasCert的疑问，见#后面的内容
class CompanyHasCert(BuilderJob):
    def build(self):
        source = CSVReader(
            local_path="./builder/job/data/Company_hasCert_Cert.csv",
            columns=["src", "dst"],
            start_row=2,
        )

        mapping = (
            RelationMapping(
                subject_name=RiskMining.Company,
                predicate_name="hasCert",
                object_name=RiskMining.Cert,
            )

            # 我的理解是用"src"的值自动填充"srcId"的值。不知是否正确？
            # 另外：srcId的内容，我可以在哪里可以看到呢？

            .add_sub_property_mapping("src", "srcId") 
            .add_sub_property_mapping("dst", "dstId")
        )

2、关于CertLinkerOperator的疑问：
2.1 上个类CompanyHasCert的处理如何与本类CertLinkerOperator关联的呢？
2.2 #后面的内容
class CertLinkerOperator(LinkOp):
    bind_to = "RiskMining.Cert"

    def __init__(self):
        super().__init__()
        self.search_client = SearchClient("RiskMining.Cert")

    def invoke(self, property: str, record: SPGRecord) -> List[SPGRecord]:
        
        # 是否只处理has_cert，不处理APP类型的useCert关系

        has_cert = property

        query = {"match": {"certNum": has_cert}}
        recall_certs = self.search_client.search(query, start=0, size=10)
        if recall_certs is not None and len(recall_certs) > 0:
            return [

                # 没理解这段代码的含义是什么？

                SPGRecord("RiskMining.Cert").upsert_properties(
                    {"id": recall_certs[0].doc_id}
                )
            ]

        return [SPGRecord("RiskMining.Cert").upsert_properties({"id": property})]

**Comment by baifuyu** [comment]
> 1.关于CompanyHasCert的疑问，见#后面的内容 class CompanyHasCert(BuilderJob): def build(self): source = CSVReader( local_path="./builder/job/data/Company_hasCert_Cert.csv", columns=["src", "dst"], start_row=2, )
> 
> ```
>     mapping = (
>         RelationMapping(
>             subject_name=RiskMining.Company,
>             predicate_name="hasCert",
>             object_name=RiskMining.Cert,
>         )
> 
>         # 我的理解是用"src"的值自动填充"srcId"的值。不知是否正确？
>         # 另外：srcId的内容，我可以在哪里可以看到呢？
> 
>         .add_sub_property_mapping("src", "srcId") 
>         .add_sub_property_mapping("dst", "dstId")
>     )
> ```
> 
> 2、关于CertLinkerOperator的疑问： 2.1 上个类CompanyHasCert的处理如何与本类CertLinkerOperator关联的呢？ 2.2 #后面的内容 class CertLinkerOperator(LinkOp): bind_to = "RiskMining.Cert"
> 
> ```
> def __init__(self):
>     super().__init__()
>     self.search_client = SearchClient("RiskMining.Cert")
> 
> def invoke(self, property: str, record: SPGRecord) -> List[SPGRecord]:
>     
>     # 是否只处理has_cert，不处理APP类型的useCert关系
> 
>     has_cert = property
> 
>     query = {"match": {"certNum": has_cert}}
>     recall_certs = self.search_client.search(query, start=0, size=10)
>     if recall_certs is not None and len(recall_certs) > 0:
>         return [
> 
>             # 没理解这段代码的含义是什么？
> 
>             SPGRecord("RiskMining.Cert").upsert_properties(
>                 {"id": recall_certs[0].doc_id}
>             )
>         ]
> 
>     return [SPGRecord("RiskMining.Cert").upsert_properties({"id": property})]
> ```

1. CompanyHasCert构建任务是要去构建公司与Cert之间的边。从Company_hasCert_Cert.csv中读取数据，里面包括源点(src)和终点(dst)，将这2个字段映射到这条边的srcId和dstId导入。目前底层是使用了tugraph作为图谱的知识存储，可以直接打开http://127.0.0.1:7070 端口看下tugraph的产品界面。3月底spg会有自己的产品界面发布。
2. 知识构建过程会有5类算子，其中的链指算子当在算子定义中声明 bind_to 时，在知识构建时会自动执行该算子。链指算子的用途主要是将传入的数据链指到图谱已经存在的实体。CertLinkerOperator例子中是从es中召回该文档，然后使用该文档的id作为真正的实体id写入

知识构建builder目前来看可编程的易用性还不够友好，我们内部主要是产品化的使用知识构建功能。我们也在讨论新的知识构建方案

**Comment by zhui6688** [comment]
1、关于第一个问题的疑问：

- 边hasCert的属性srcId与dstId，是在CompanyHasCert的mapping执行时才生成的，对吧？
- 如果是这样，是否可以在构建schema中直接声明子属性srcId与dstId呢？
- 如果可以使用schema声明边的子属性，那我们还需要在CompanyHasCert中写mapping代码吗？
- 此时写的mapping代码与上述的代码有否不同之处？

2、关于第二个问题的疑问：

- 我在沿着CertLinkerOperator的继承关系在回溯代码的实现逻辑。应该是通过LinkOp类中的_handle()实现图谱已存储实例的链指。不知道是否是这样？- 
-另外：LinkOp类中_pre_process()应该是在知识构建时的src与dst。本例中应该就是:company实例与cert实例。但是，下面代码是用input[0]作为self.invoke(_property, subject_record)的参数。而在CertLinkerOperator类实现的invoke()，has_cert = property这个逻辑就感觉有点怪了。能否麻烦解释一下

   def _pre_process(*inputs):

        #此处
        return inputs[0], SPGRecord.from_dict(inputs[1])

    def _handle(self, *inputs) -> Dict[str, Any]:
        _property, subject_record = self._pre_process(*inputs)
        cache_key = str(self.bind_to) + _property
        cache_property = cache.get(cache_key)
        if cache_property:
            output = [
                SPGRecord(spg_type_name=self.bind_to).upsert_property(
                    "id", cache_property
                )
            ]
        else:
           #此处
            output = self.invoke(_property, subject_record)
        post_output = self._post_process(output)
        return post_output


class CertLinkerOperator(LinkOp):
    bind_to = "RiskMining.Cert"
    def invoke(self, property: str, record: SPGRecord) -> List[SPGRecord]:
        
        #此处
        has_cert = property

        query = {"match": {"certNum": has_cert}}
        recall_certs = self.search_client.search(query, start=0, size=10)

**Comment by baifuyu** [comment]
> 1、关于第一个问题的疑问：
> 
> * 边hasCert的属性srcId与dstId，是在CompanyHasCert的mapping执行时才生成的，对吧？
> * 如果是这样，是否可以在构建schema中直接声明子属性srcId与dstId呢？
> * 如果可以使用schema声明边的子属性，那我们还需要在CompanyHasCert中写mapping代码吗？
> * 此时写的mapping代码与上述的代码有否不同之处？
> 
> 2、关于第二个问题的疑问：
> 
> * 我在沿着CertLinkerOperator的继承关系在回溯代码的实现逻辑。应该是通过LinkOp类中的_handle()实现图谱已存储实例的链指。不知道是否是这样？-
>   -另外：LinkOp类中_pre_process()应该是在知识构建时的src与dst。本例中应该就是:company实例与cert实例。但是，下面代码是用input[0]作为self.invoke(_property, subject_record)的参数。而在CertLinkerOperator类实现的invoke()，has_cert = property这个逻辑就感觉有点怪了。
> 
> class LinkOp(BaseOp, ABC):
> 
> def _pre_process(*inputs):
> 
> ```
>     #此处
>     return inputs[0], SPGRecord.from_dict(inputs[1])
> 
> def _handle(self, *inputs) -> Dict[str, Any]:
>     _property, subject_record = self._pre_process(*inputs)
>     cache_key = str(self.bind_to) + _property
>     cache_property = cache.get(cache_key)
>     if cache_property:
>         output = [
>             SPGRecord(spg_type_name=self.bind_to).upsert_property(
>                 "id", cache_property
>             )
>         ]
>     else:
>        #此处
>         output = self.invoke(_property, subject_record)
>     post_output = self._post_process(output)
>     return post_output
> ```
> 
> class CertLinkerOperator(LinkOp): bind_to = "RiskMining.Cert" def invoke(self, property: str, record: SPGRecord) -> List[SPGRecord]:
> 
> ```
>     #此处
>     has_cert = property
> 
>     query = {"match": {"certNum": has_cert}}
>     recall_certs = self.search_client.search(query, start=0, size=10)
> ```


1. 边hasCert的属性srcId和dstId是在knext schema commit的时候生成的。在CompanyHasCert中只是告诉builder将原始csv的中数据导入到这2个属性中，不然builder不知道如何将csv中的字段映射到图谱字段了
2. 这里的理解你大部分是对的哈。具体的链指执行策略入口是 com.antgroup.openspg.builder.core.strategy.linking.impl.OperatorLinking#linking，其中 inputs[0]是company或者cert的csv内容，后面的input[1]是上下文信息。但是 Company没有链指算子，CertLinkerOperator是Cert的链指算子，所以表达成了 has_cert = property

**Comment by zhui6688** [comment]
为什么Company的类型定义里没有该子属性的定义呀？

Company(企业): EntityType
	properties:
		hasPhone(电话号码): STD.ChinaMobile
	relations:
		hasCert(拥有证书): Cert
		holdShare(持股): Company

**Comment by baifuyu** [comment]
> 为什么Company的类型定义里没有srcId和dstId子属性的定义呢。看了一下TuGraph，是不是所有的边默认都有两个srcId和dstId子属性？
> 
> Company(企业): EntityType properties: hasPhone(电话号码): STD.ChinaMobile relations: hasCert(拥有证书): Cert holdShare(持股): Company

关系（边）上默认会创建srcId和dstId的。Company在tugraph上存储成点了，所以不会创建的

**Comment by zhui6688** [comment]
明白了，十分感谢！
