### ISSUE TITLE
源码疑问，在推理过程中存在大量的foreach，特别是因果语义CausalConceptReasoner#propagate中，代码逻辑为递归、深度优先遍历，这部分代码有并行度优化计划吗？求解答~

### ISSUE THREAD

**Issue by billc114** [OpenSPG/openspg#131]

**Comment by baifuyu** [comment]
这块代码是在知识构建过程中的传导推理，以产业链为例子，当一个事件发生时，会leadTo下游事件的发生。如果在逻辑规则上定义了多层leadTo传导，则会进行多层推理，所以这里使用了递归的方式。

知识构建builder模块，后续我们会有一次大的优化升级，与蚂蚁内部的系统保持一致。目前开源的版本会稍微简单一些，后续会支持分布式的知识构建，但是对于单个事件的传导链，短期之内应该还是目前方式

**Comment by billc114** [comment]
> 这块代码是在知识构建过程中的传导推理，以产业链为例子，当一个事件发生时，会leadTo下游事件的发生。如果在逻辑规则上定义了多层leadTo传导，则会进行多层推理，所以这里使用了递归的方式。
> 
> 知识构建builder模块，后续我们会有一次大的优化升级，与蚂蚁内部的系统保持一致。目前开源的版本会稍微简单一些，后续会支持分布式的知识构建，但是对于单个事件的传导链，短期之内应该还是目前方式
感谢回答！请问
1、预计什么时候开源分布式知识构建，是spg文档中基于Spark的RDG那一套吗？
2、递归推理过程中有相同leadTo推理，它的逻辑计划->物理计划都会重新生成，物理计划缓存与复用，请问将来是否有这方面的优化？

**Comment by baifuyu** [comment]
> > 这块代码是在知识构建过程中的传导推理，以产业链为例子，当一个事件发生时，会leadTo下游事件的发生。如果在逻辑规则上定义了多层leadTo传导，则会进行多层推理，所以这里使用了递归的方式。
> > 知识构建builder模块，后续我们会有一次大的优化升级，与蚂蚁内部的系统保持一致。目前开源的版本会稍微简单一些，后续会支持分布式的知识构建，但是对于单个事件的传导链，短期之内应该还是目前方式
> 
> 感谢回答！请问 1、预计什么时候开源分布式知识构建，是spg文档中基于Spark的RDG那一套吗？ 2、递归推理过程中有相同leadTo推理，它的逻辑计划->物理计划都会重新生成，物理计划缓存与复用，请问将来是否有这方面的优化？

1. 现在还没有确切的时间开源分布式知识构建，内部会先重构一版，面向用户提供更友好的使用方式，目前基于BuilderJob的方式还不是很友好。思路会和Spark/Flink类似，提供高阶API编程。Spark的RDG那套是推理引擎使用的，后续可能会将推理和构建引擎统一，预计3月中会有较清晰的计划
2. 这块如果按照上述的计划，构建和推理引擎统一后会实现这些优化。到时候设计文档我们发布到openspg.yueque.com可以大家一起review下
