### ISSUE TITLE
schema创建后，builder数据时，可能改变elasticsearch中记录的schema信息，导致spg修改schema时报错

### ISSUE THREAD

**Issue by billc114** [OpenSPG/openspg#133]
我进行了如下操作：
1、新建schema，如下：
```
Test: EntityType
    properties:
       ...
       st : Text
       ...
```
2、导入数据，数据中的st为时间格式
![image](https://github.com/OpenSPG/openspg/assets/52943316/434573d2-e933-4300-9e52-b4922d6bd1e2)
3、导入成功后，修改schema报错：
![image](https://github.com/OpenSPG/openspg/assets/52943316/2fddc0db-5229-44c4-aa60-2e52442e802c)

定位后发现是由于导入数据后，elasticsearch中记录的schema信息是这样的：
```
			"st": {
				"type": "date"
			}
```
看了下spg server代码，发现业务逻辑为，在提交schema时，会对elasticsearch中记录的schema信息做校验（`com.antgroup.openspg.cloudext.interfaces.searchengine.adapter.schema.impl.SPGSchema2IdxServiceImpl#checkSchemaAlterations`），
date类型不在elasticsearch支持的几种基础类型中。所以在第3步修改schema时会报错。初看报错时一直在找.schema中定义的类型是否有date类型，spg、turaph中的类型都没有date，在elasticsearch中却变成了date，这块是否可以优化，否则很难定位到

**Comment by baifuyu** [comment]
> 我进行了如下操作： 1、新建schema，如下：
> 
> ```
> Test: EntityType
>     properties:
>        ...
>        st : Text
>        ...
> ```
> 
> 2、导入数据，数据中的st为时间格式 ![image](https://private-user-images.githubusercontent.com/52943316/309215246-434573d2-e933-4300-9e52-b4922d6bd1e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNjY0MjgsIm5iZiI6MTcwOTM2NjEyOCwicGF0aCI6Ii81Mjk0MzMxNi8zMDkyMTUyNDYtNDM0NTczZDItZTkzMy00MzAwLTllNTItYjQ5MjJkNmJkMWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDA3NTUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNzY2YmIyMGJiNDQ3YzA1YTE1YWI3YjljZWU0Mjg3ZGY0MTFkMmE2ZTAzZGE4NzNiZTA2MGJjYWJiNjg3M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kLJi8Hb__FsCe29FuifJfeZGH-l7aXKKE-l1T3u13bE) 3、导入成功后，修改schema报错： ![image](https://private-user-images.githubusercontent.com/52943316/309215492-2fddc0db-5229-44c4-aa60-2e52442e802c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNjY0MjgsIm5iZiI6MTcwOTM2NjEyOCwicGF0aCI6Ii81Mjk0MzMxNi8zMDkyMTU0OTItMmZkZGMwZGItNTIyOS00NGM0LWFhNjAtMmU1MjQ0MmU4MDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDA3NTUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNzQ4ZjU5ODYwZjZhNTQ5ZDY1ZDE2MjFiNzlmOGY3N2Y0MjMwN2JlYjg2MDczOThmMjQ5ZTA0MGFiOTQwN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RKkntiHm1p9gBPtmjkzhFFIGyybtBVsFyiAfxs1xFpM)
> 
> 定位后发现是由于导入数据后，elasticsearch中记录的schema信息是这样的：
> 
> ```
> 			"st": {
> 				"type": "date"
> 			}
> ```
> 
> 看了下spg server代码，发现业务逻辑为，在提交schema时，会对elasticsearch中记录的schema信息做校验（`com.antgroup.openspg.cloudext.interfaces.searchengine.adapter.schema.impl.SPGSchema2IdxServiceImpl#checkSchemaAlterations`）， date类型不在elasticsearch支持的几种基础类型中。所以在第3步修改schema时会报错。初看报错时一直在找.schema中定义的类型是否有date类型，spg、turaph中的类型都没有date，在elasticsearch中却变成了date，这块是否可以优化，否则很难定位到

收到，这块es目前是直接基于数据内容做的schema，时间类型自动会被判断成date了，我们尽快修复下
