### ISSUE TITLE
请问在dsl查询时如何使用KGDSL语法

### ISSUE THREAD

**Issue by billc114** [OpenSPG/openspg#135]
示例中的dsl查询语句均为简单的MATCH - RETURN语句，类似于Cipher语法，想在查询时进行推理，例：
```
Structure {
    （s:User）
}
Constraint {
    R1("成年人"): s.age > 18

    R2("男性"): s.gender == "男"

    // 下面这句是正确的，R3由R1和R2组合而成，就被视为是一条规则组
    R3("成年男性"): R1 and R2

    // 下面这句是错误的，规则组里不允许有非规则的变量
    R3("成年男性"): R1 and s.gender == "男"
}
```
想要在.dsl文件中增加上述语法，请问可以做到吗？

**Comment by fishjoy** [comment]
支持的，另外对于: R3("成年男性"): R1 and s.gender == "男" 这条规则，我们也认为是正确的，这个时候 s.gender == "男" 是一个匿名规则，R1 会被解释成 s.age > 18

**Comment by billc114** [comment]
> 支持的，另外对于: R3("成年男性"): R1 and s.gender == "男" 这条规则，我们也认为是正确的，这个时候 s.gender == "男" 是一个匿名规则，R1 会被解释成 s.age > 18

求一个完整的dsl查询语句示例！文档中的dsl查询只有简单的MATCH+RETURN，不知道怎么写上述语法
