### ISSUE TITLE
如何使用knext shema commit提交到tugraph指定的子图

### ISSUE THREAD

**Issue by zhangcongxiao** [OpenSPG/openspg#14]
knext shema commit 命令默认提交到tugraph的default子图下，如何指定提交到其他子图

**Comment by baifuyu** [comment]
> knext shema commit 命令默认提交到tugraph的default子图下，如何指定提交到其他子图

暂时不允许提交到其他的子图。主要原因在于后面要做融合，tugraph的不同子图没法做融合查询哈

**Comment by baifuyu** [comment]
> knext shema commit 命令默认提交到tugraph的default子图下，如何指定提交到其他子图

后期我们会开放蚂蚁这边得图存系统。那会会支持会命名空间
