### ISSUE TITLE
找不到已经生成哈皮的知识图谱文件

### ISSUE THREAD

**Issue by fameifanqie** [OpenSPG/openspg#140]
knext builder execute Disease
请问一下在执行完此命令后，是不是就生成了知识图谱呢？但是生成的这个图谱的文件在哪里呢？看了教程和说明书，没有找到，非工科专业，问的问题可能略幼稚，谢谢，期待回复

**Comment by baifuyu** [comment]
> knext builder execute Disease 请问一下在执行完此命令后，是不是就生成了知识图谱呢？但是生成的这个图谱的文件在哪里呢？看了教程和说明书，没有找到，非工科专业，问的问题可能略幼稚，谢谢，期待回复

目前openspg会将数据写到底层的图存储，目前是在tugraph的图数据库中。可以打开对应部署tugraph的容器，假如在本地运行的话，可以打开浏览器端口 http://127.0.0.1:7070 看到tugraph的可视化界面

**Comment by fameifanqie** [comment]
好的，我再试一下，感谢

**Comment by Shiyaoa** [comment]
@baifuyu 打开可视化界面后需要登录，用户名和密码是什么呢？另外，容器里的mysql,elasticsearch 也是有端口的么，同样的用户名密码是什么

**Comment by zhui6688** [comment]
1、帐号与密码在tugraph官网的“可视化界面”这部分有说明。
2、elasticsearch的端口可使用docker ps命令查看，0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp

**Comment by baifuyu** [comment]
> @baifuyu 打开可视化界面后需要登录，用户名和密码是什么呢？另外，容器里的mysql,elasticsearch 也是有端口的么，同样的用户名密码是什么

从这个文件中可以找到答案。https://github.com/OpenSPG/openspg/blob/master/dev/release/docker-compose.yml 

1. tugraph的可视化界面的账号密码是admin，73@TuGraph
2. mysql的账号密码是账号root，密码是openspg。端口为3306
3. es没有账号密码，端口为9200

**Comment by Shiyaoa** [comment]
感谢 @baifuyu @zhui6688
