### ISSUE TITLE
自己修改医疗的Schema，执行knext schema commit报错

### ISSUE THREAD

**Issue by cuijiaxin8** [OpenSPG/openspg#147]
自定义的Schema如下，增加了两个Entity，分别是检查项目和检验项目，并且在Disease中增加applicableInspection、applicableCheck
`namespace Medicine

Symptom(症状): EntityType
    desc: 这是一个症状

Drug(药品): EntityType

Indicator(医学指征): EntityType

Inspection(检验项目): EntityType
    desc: 这是一个检验

Check(检查项目): EntityType
    desc: 这是一个检查

BodyPart(人体部位): ConceptType
    hypernymPredicate: isA

HospitalDepartment(医院科室): ConceptType
    hypernymPredicate: isA

Disease(疾病): EntityType
    properties:
        complication(并发症): Disease
            constraint: MultiValue
        commonSymptom(常见症状): Symptom
            constraint: MultiValue
        applicableInspection(适用检验): Inspection
            constraint: MultiValue
        applicableCheck(适用检查): Check
            constraint: MultiValue
        applicableDrug(适用药品): Drug
            constraint: MultiValue
        department(就诊科室): HospitalDepartment
            constraint: MultiValue
        diseaseSite(发病部位): BodyPart
            constraint: MultiValue
    relations:
        abnormal(异常指征): Indicator
            properties:
                range(指标范围): Text
                color(颜色): Text
                shape(性状): Text`
  
在执行 `knext schema commit`时，提示：
ERROR: id must in the property of vertex, and now the property of vertex(Medicine.Disease) is [applicableInspection, applicableCheck]

**Comment by baifuyu** [comment]
> must in the property of vertex

我这边没法复现这个问题，在 medicine.schema 上增加了这2个EntityType，以及作为Disease的属性，直接基于更改后的schema文件再执行 knext schema commit 命令结果是成功的。不知道能否提供更多的错误上下文呢 

![image](https://github.com/OpenSPG/openspg/assets/147798664/4714aae0-3ce8-4048-b14e-4f9b2914b7de)
