### ISSUE TITLE
关于docker中的elasticsearch分词器的问题

### ISSUE THREAD

**Issue by zhui6688** [OpenSPG/openspg#148]
我想找到opspg服务器中的elasticsearch目前使用的所有分词器，应该如何查询？另外，可以在服务器添加自己的分词器吗？应该如何操作？目前，我找不到elasticsearch的plugin目录在哪里？

**Comment by baifuyu** [comment]
> 我想找到opspg服务器中的elasticsearch目前使用的所有分词器，应该如何查询？另外，可以在服务器添加自己的分词器吗？应该如何操作？目前，我找不到elasticsearch的plugin目录在哪里？

如果是使用docker-compose这种方式启动的话，配置是这个链接 https://github.com/OpenSPG/openspg/blob/master/dev/release/docker-compose.yml，那么es是直接集成开源es的8.5.3版本，相关es的文档可以参考：https://www.elastic.co/guide/en/elasticsearch/reference/8.5/analysis-analyzers.html

openspg还没提供指定es分词器的功能，默认是使用 standard analyzer，具体文档可以先参考这里 https://www.elastic.co/guide/en/elasticsearch/reference/8.5/specify-analyzer.html#specify-index-time-default-analyzer
