### ISSUE TITLE
根据用户手册中的安装说明安装完并初试话riskmining项目时报错 ERROR: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by adjcjh777** [OpenSPG/openspg#151]
在执行riskming项目下执行knext project create --prj_path .的时候报了
`ERROR: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`
这个错误，这是什么原因呢？
在安装过程中执行docker compose那一步完成后 使用的服务器自动添加了一条172.18.0.0的路由规则，导致我无法链接我的服务器，之后经过管理员调整路由之后重新链接服务器，重启所有的docker容器后再执行knext project create --prj_path .一直会有`ERROR: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`的错误，不知道是不是因为这个路由的修改导致的容器间无法通信而导致的链接错误呢？

**Comment by baifuyu** [comment]
> 在执行riskming项目下执行knext project create --prj_path .的时候报了 `ERROR: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))` 这个错误，这是什么原因呢？ 在安装过程中执行docker compose那一步完成后 使用的服务器自动添加了一条172.18.0.0的路由规则，导致我无法链接我的服务器，之后经过管理员调整路由之后重新链接服务器，重启所有的docker容器后再执行knext project create --prj_path .一直会有`ERROR: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`的错误，不知道是不是因为这个路由的修改导致的容器间无法通信而导致的链接错误呢？

可以尝试下在你的knext的docker容器中ping下安装了openspg的服务器端口，比如 ping 127.0.0.1:8887，如果不通的话说明knext链接不上服务端。上面的报错意思就是没连接上服务端
