### ISSUE TITLE
1.项目名称已存在如何修改；2.在tugraph中找不到已上传的图谱信息

### ISSUE THREAD

**Issue by fameifanqie** [OpenSPG/openspg#154]
两个疑问：
1.在跑程序的时候，提示项目名称已存在，应该在哪里修改项目名称呢？
2.之前跑成功过，但是登录tugraph后找不到相关文件？应该如何解决？
谢谢

![微信截图_20240312120249](https://github.com/OpenSPG/openspg/assets/134571436/3359a9fa-970e-4c7a-8015-8ccbcf258bd7)

![2](https://github.com/OpenSPG/openspg/assets/134571436/11a69aab-3048-403d-9c2d-d013357a822f)

**Comment by baifuyu** [comment]
> 两个疑问： 1.在跑程序的时候，提示项目名称已存在，应该在哪里修改项目名称呢？ 2.之前跑成功过，但是登录tugraph后找不到相关文件？应该如何解决？ 谢谢
> 
> ![微信截图_20240312120249](https://private-user-images.githubusercontent.com/134571436/311936588-3359a9fa-970e-4c7a-8015-8ccbcf258bd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTU4ODgsIm5iZiI6MTcxMDI5NTU4OCwicGF0aCI6Ii8xMzQ1NzE0MzYvMzExOTM2NTg4LTMzNTlhOWZhLTk3MGUtNGM3YS04MDE1LThjY2JjZjI1OGJkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QwMjA2MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDVlMmRhMjg4ZTMxNzVkYThkYjg1ZDhiYTM0YzA3YmI0NWQ0MTI5YzgzYzY0MDQ2OGE0MTQ1MGMxYjNjMTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Z5POjaFHXGVIVbhRnkVFsMBKdYt_NUo-8e6hgosEslE)
> 
> ![2](https://private-user-images.githubusercontent.com/134571436/311936984-11a69aab-3048-403d-9c2d-d013357a822f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTU4ODgsIm5iZiI6MTcxMDI5NTU4OCwicGF0aCI6Ii8xMzQ1NzE0MzYvMzExOTM2OTg0LTExYTY5YWFiLTMwNDgtNDAzZC05YzJkLWQwMTMzNTdhODIyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QwMjA2MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWM2NGU1MDM0NDY1ZmE2MGYzMmRjNjkwMTIyMTFmNDZhYWQ5ODkyYzgyOGU5YmEzNjYyMGYzZTY0NDRhNjE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ASlTH35Gzj82SFvjB7Qt4XKcamGb6A8KzHIc07yt55g)


1. 系统暂时没有提供修改项目名称的功能。可以销毁容器再重新创建，或者修改下该目录下的.knext.cfg文件调整下 project_name和namespace
2. 不能将knext命令贴到tugraph的执行框里，可以贴gql进去执行。knext命令直接基于命令行就可以了
