### ISSUE TITLE
openspg有哪些可以直接调用的图谱算法模型，有相应的统计吗

### ISSUE THREAD

**Issue by KeangZHU** [OpenSPG/openspg#158]

**Comment by baifuyu** [comment]
@KeangKangKang 图谱算法模型是指图学习算法？还是指的是NLP相关的算法呢？如果是指图学习的话，目前还没有集成。NLP目前就只基于大模型做知识构建

**Comment by KeangKangKang** [comment]
> @KeangKangKang 图谱算法模型是指图学习算法？还是指的是NLP相关的算法呢？如果是指图学习的话，目前还没有集成。NLP目前就只基于大模型做知识构建

**Comment by KeangKangKang** [comment]
多谢，类似transE类型的推理算法

**Comment by KeangKangKang** [comment]
谢谢，类似TransE的图谱推理算法呢

**Comment by KeangKangKang** [comment]
> @KeangKangKang 图谱算法模型是指图学习算法？还是指的是NLP相关的算法呢？如果是指图学习的话，目前还没有集成。NLP目前就只基于大模型做知识构建

谢谢，类似TransE的图谱推理算法呢
