### ISSUE TITLE
请问KGDSL语法中的Action语法是否支持设置属性的值？

### ISSUE THREAD

**Issue by billc114** [OpenSPG/openspg#166]
> Action中支持多种操作：
● createNodeInstance/createEdgeInstance：用于因果的逻辑结果的语义表达
● get ：输出匹配的结果，包括实体、关系以及属性等内容。

官方文档如上，请问是否支持类似于set语句，对匹配的结果的属性进行修改

**Comment by fishjoy** [comment]
目前还不支持对属性的修改，但是可以新增一个属性。
```
Define (s:A)-[p:prop]->(o:Int) {
   GraphStructure {
        (s)<-[:belong]-(d:B)
    }
    Rule {
        o = group(s).count(B)
    }
}
```
这个DSL的功能是给匹配出来的A，新增一个prop属性，属性的值类型为Int
