### ISSUE TITLE
是否有0.0.1beta1版本的推理部分的代码？在0.0.1版本中，这部分代码只是发布了个jar包，github上没有代码，调试过程看不到代码信息。

### ISSUE THREAD

**Issue by w00125533** [OpenSPG/openspg#167]
![image](https://github.com/OpenSPG/openspg/assets/22139807/1153912d-ed1e-40ad-b57e-61d281426b18)

**Comment by baifuyu** [comment]
> ![image](https://private-user-images.githubusercontent.com/22139807/315198730-1153912d-ed1e-40ad-b57e-61d281426b18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNzU4NDAsIm5iZiI6MTcxMTA3NTU0MCwicGF0aCI6Ii8yMjEzOTgwNy8zMTUxOTg3MzAtMTE1MzkxMmQtZWQxZS00MGFkLWI1N2UtNjFkMjgxNDI2YjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDAyNDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YWRjMGI2Y2NiZmIxNTg1OTQzODc0NzNkZjk4ZmI2NzM5YzBiODM0MmYzZDUzZmVlZjZhYjM0ZTkzZmEyNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v7IkRtW8jB3YsJB70OjtzaETeZRDKcwWAGFyr6GMzgw)

这部分代码已经开源了在/reasoner目录下。可以使用0.0.2的版本。最新安装文档地址可以查看 https://openspg.yuque.com/ndx6g9/ooil9x
