### ISSUE TITLE
事件概念体系构建问题

### ISSUE THREAD

**Issue by AnYingLieShouTuT** [OpenSPG/openspg#179]
![image](https://github.com/OpenSPG/openspg/assets/108744191/a9212171-c120-48a4-85df-c2fa484a2cb8)
您好，图上的事件概念体系构建是否有代码参考。

**Comment by AnYingLieShouTuT** [comment]
examples中没有看到类似的代码

**Comment by leywar** [comment]
> 

你好，可以参考 https://github.com/OpenSPG/openspg/blob/master/python/knext/knext/examples/supplychain/schema/supplychain.schema 中CompanyEvent的定义。
