### ISSUE TITLE
TuGraph的快照能力

### ISSUE THREAD

**Issue by zhangcongxiao** [OpenSPG/openspg#18]
为了验证TuGraph的快照能力，根据Tugraph文档提供的参数，我在docker-compose.ymal 将tuGraph的启动命令修改如下：
![image](https://github.com/OpenSPG/openspg/assets/46892331/d9f270f1-295f-42f7-b1e7-d730bd02b5c0)
但实际运行后发现/var/tmp目录下没有生成快照文件，请问可能是什么原因

**Comment by baifuyu** [comment]
> 为了验证TuGraph的快照能力，根据Tugraph文档提供的参数，我在docker-compose.ymal 将tuGraph的启动命令修改如下： ![image](https://private-user-images.githubusercontent.com/46892331/288951207-d9f270f1-295f-42f7-b1e7-d730bd02b5c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMzAxNTMsIm5iZiI6MTcwMjAyOTg1MywicGF0aCI6Ii80Njg5MjMzMS8yODg5NTEyMDctZDlmMjcwZjEtMjk1Zi00MmY3LWIxZTctZDczMGJkMDJiNWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDEwMDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNWVkZDNhNDU3Y2ViODAwY2YxN2E4ZjJiNDE2Y2QxNmJiOTQ4MzZmZmEwYzQyNTBhNzRlZTUxMzA5MjQ3N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BdKdYnQ0g1ZC6Yo4Gqv7iGyi7q536ZGmokRnOY7j_ew) 但实际运行后发现/var/tmp目录下没有生成快照文件，请问可能是什么原因

确认下哈，/var/tmp 应该是在docker里面的目录的，而不是本机上的 /var/tmp

**Comment by zhangcongxiao** [comment]
是在容器内部
![image](https://github.com/OpenSPG/openspg/assets/46892331/71d45c70-b3e0-456e-aebe-38cbf65a11db)

**Comment by J4ckycjl** [comment]
@zhangcongxiao 您好！

经过咨询，我们了解到，TuGraph的企业版的高可用模式（HA，high availability）能够支持快照能力（https://tugraph-db.readthedocs.io/zh-cn/latest/5.developer-manual/2.running/3.high-availability-mode.html）。

目前，OpenSPG项目集成的是TuGraph的开源社区版本镜像，因此无法满足您的需求。

如果只是想备份的哈，可以考虑使用lgraph_backup，这个和这类snapshot走的过程基本是一致的。

**Comment by baifuyu** [comment]
> 是在容器内部 ![image](https://private-user-images.githubusercontent.com/46892331/289405358-71d45c70-b3e0-456e-aebe-38cbf65a11db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTE2NzcsIm5iZiI6MTcwMjI5MTM3NywicGF0aCI6Ii80Njg5MjMzMS8yODk0MDUzNTgtNzFkNDVjNzAtYjNlMC00NTZlLWFlYmUtMzhjYmY2NWExMWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEwNDI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlOTNkOWY2OWI5YjY2NzY4MDExMzY1YTg1M2FiMjY2NmY2MjIzNDU0YTBhNThjOTFhZmYyNWQ0MDllYzBjZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5inCwNAuv9zKDMPsQyT2aRSvEE1dcjC32r-prg31sm8)

OpenSPG目前集成得是TuGraph的开源单机版本，不支持上述的方式创建SNAPSHOT。如果确实需要使用可以尝试使用 lgraph_backup命令来导出db数据。

另外，OpenSPG后续也会开源企业级大规模语义知识图谱存储，基于DFS存储图谱数据，适应多云环境部署，具有易扩展、低成本等特点。欢迎关注OpenSPG的发布动态， 如果有新的发布计划我们将第一时间通知~
