### ISSUE TITLE
knext config无法连接服务端

### ISSUE THREAD

**Issue by QIYU0w0** [OpenSPG/openspg#185]
`knext config set --global host_addr=http://127.0.0.1:8887`没有报错
`knext project create --name demo --namespace Demo --desc 这是个demo`报错

ERROR: HTTPConnectionPool(host='127.0.0.1', port=8887): Max retries exceeded with url: /public/v1/project (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020DF5154370>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

防火墙已经开放了端口，netstat -an查询端口状态发现没有打开。
怎么处理才能连接？

**Comment by leywar** [comment]
你好，如果开启了代理，可以关闭代理试下。 https://huaweicloud.csdn.net/63806d62dacf622b8df880b0.html

**Comment by baifuyu** [comment]
> `knext config set --global host_addr=http://127.0.0.1:8887`没有报错 `knext project create --name demo --namespace Demo --desc 这是个demo`报错
> 
> ERROR: HTTPConnectionPool(host='127.0.0.1', port=8887): Max retries exceeded with url: /public/v1/project (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020DF5154370>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
> 
> 防火墙已经开放了端口，netstat -an查询端口状态发现没有打开。 怎么处理才能连接？

得看下本地的 openspg-server 容器是否启动呢？knext会去链接本地的 8887 端口，这个端口是 openspg-server 容器提供schema查询服务的
