### ISSUE TITLE
参数疑问

### ISSUE THREAD

**Issue by AnYingLieShouTuT** [OpenSPG/openspg#187]
```
class Company(BuilderJob):
    parallelism = 6
```
```
class ProductChainEvent(BuilderJob):
    lead_to = True
```
你好，parallelism = 6以及lead_to = True的作用是什么？

**Comment by baifuyu** [comment]
> ```
> class Company(BuilderJob):
>     parallelism = 6
> ```
> 
> ```
> class ProductChainEvent(BuilderJob):
>     lead_to = True
> ```
> 
> 你好，parallelism = 6以及lead_to = True的作用是什么？

parallelism = 6 表示并发度为6，底层知识构建会启动6个线程同时处理一个csv文件的导入。
lead_to = True 当该参数设置为True的时候，当前事件的导入会根据leadTo逻辑规则进行事件传导

**Comment by AnYingLieShouTuT** [comment]
> > ```
> > class Company(BuilderJob):
> >     parallelism = 6
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > class ProductChainEvent(BuilderJob):
> >     lead_to = True
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 你好，parallelism = 6以及lead_to = True的作用是什么？
> 
> parallelism = 6 表示并发度为6，底层知识构建会启动6个线程同时处理一个csv文件的导入。 lead_to = True 当该参数设置为True的时候，当前事件的导入会根据leadTo逻辑规则进行事件传导

感谢答复，还有几个问题：
1. lead_to = True是指导入事件的时候会自动根据concept.rule里设置的规则去判断leadTo是否成立吗，那如果lead_to设置为false或者不设置的时候，是当执行.dsl文件的时候才进行传导吗？
2. belongTo是当导入数据的时候进行判断的，还是在执行.dsl进行查询belongTo的时候才会进行判断。

**Comment by baifuyu** [comment]
> > > ```
> > > class Company(BuilderJob):
> > >     parallelism = 6
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > class ProductChainEvent(BuilderJob):
> > >     lead_to = True
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 你好，parallelism = 6以及lead_to = True的作用是什么？
> > 
> > 
> > parallelism = 6 表示并发度为6，底层知识构建会启动6个线程同时处理一个csv文件的导入。 lead_to = True 当该参数设置为True的时候，当前事件的导入会根据leadTo逻辑规则进行事件传导
> 
> 感谢答复，还有几个问题：
> 
> 1. lead_to = True是指导入事件的时候会自动根据concept.rule里设置的规则去判断leadTo是否成立吗，那如果lead_to设置为false或者不设置的时候，是当执行.dsl文件的时候才进行传导吗？
> 2. belongTo是当导入数据的时候进行判断的，还是在执行.dsl进行查询belongTo的时候才会进行判断。

1. lead_to设置为True，当导入事件时候就自动会进行事件传导，并将传导结果写入图存。否则在查询时候也不会传导的。
2. 当设置lead_to为True时候，导入数据时候也会判断，并将判断结果写入图存。执行dsl时候也会判断，但只是查询结果，不会写入图存
