### ISSUE TITLE
关于抽取任务和实体属性的问题

### ISSUE THREAD

**Issue by Funer100** [OpenSPG/openspg#188]
从 auto_prompt.py 的代码上来看，LLMBasedExtractor 只有 RE 和 EE 任务，没有实体抽取的任务
请问：
1、如果只有 RE 任务，那实体的属性是怎么从文本中抽取出来并映射到 schema 上的？
2、从医疗案例的 medicine.schema 来看，属性也是先被定义成实体类型的，但从别的案例的 schema 来看，名为 Text 的属性并没有先被定义成实体，我在用户手册中并没有找到这样做的原因，只在代码中看到了定义了三个基本类型，请问是为什么呢？
![image](https://github.com/OpenSPG/openspg/assets/152193861/02439aff-4f60-4ec5-b40f-455bb799ca55)
3、是否只有用 UserDefinedExtractor 自定义算子，通过定义 NER 任务的 prompt 才能进行实体抽取呢？
4、按照我的理解，属性之所以被先定义成实体，是否是希望通过大模型抽取出该实体（属性），然后再作为属性映射到 schema 中？但是我并没有在各种案例的代码中看到关于属性的抽取工作。

**Comment by baifuyu** [comment]
> 从 auto_prompt.py 的代码上来看，LLMBasedExtractor 只有 RE 和 EE 任务，没有实体抽取的任务 请问： 1、如果只有 RE 任务，那实体的属性是怎么从文本中抽取出来并映射到 schema 上的？ 2、从医疗案例的 medicine.schema 来看，属性也是先被定义成实体类型的，但从别的案例的 schema 来看，名为 Text 的属性并没有先被定义成实体，我在用户手册中并没有找到这样做的原因，只在代码中看到了定义了三个基本类型，请问是为什么呢？ ![image](https://private-user-images.githubusercontent.com/152193861/318461702-02439aff-4f60-4ec5-b40f-455bb799ca55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDcwNzAsIm5iZiI6MTcxMjA0Njc3MCwicGF0aCI6Ii8xNTIxOTM4NjEvMzE4NDYxNzAyLTAyNDM5YWZmLTRmNjAtNGVjNS1iNDBmLTQ1NWJiNzk5Y2E1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQwODMyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTJiMjY0YTFmY2Y3ODRmODAzYmU4Y2E4ZWM2ODgwMWFiMTc0ODEwMTdiMTIzNzViNDYyOWRjMzU0YzRmY2IxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.de_UaqusAhM_egOw1O0UnzjlWOQrVLqk6OtliZbVGUk) 3、是否只有用 UserDefinedExtractor 自定义算子，通过定义 NER 任务的 prompt 才能进行实体抽取呢？ 4、按照我的理解，属性之所以被先定义成实体，是否是希望通过大模型抽取出该实体（属性），然后再作为属性映射到 schema 中？但是我并没有在各种案例的代码中看到关于属性的抽取工作。

auto_prompt.py 中没有NER的原因主要在知识图谱的加工链路中，RE一般是抽取SPO已经包含了实体了。

1. 可以参考下这个例子 https://github.com/OpenSPG/openspg/blob/master/python/knext/knext/examples/medicine/builder/job/disease.py，RE抽取后将结果映射到schema上
2. 在spg中，主体类型是分为实体类型，概念类型，事件类型以及基础类型的，Text，Integer，Float是基础类型。一个属性的类型可以是实体类型，概念类型，或者基础类型都是可以的，类似于面向对象编程的思想。具体可以参考 https://openspg.yuque.com/ndx6g9/nmwkzz/ltt3u0f121mm2z2c 文档
3. 如果有需要NER抽取的话，目前只有通过UserDefinedExtractor自定义算子
4. 这个问题和第2个类型，可以参照第二个问题答案
