### ISSUE TITLE
 knext builder execute提交任务时的报错

### ISSUE THREAD

**Issue by Funer100** [OpenSPG/openspg#194]
(openspg_venv) root@docker-desktop:/code/openspg-master/python/knext/knext/examples/deepke# knext builder execute task_entry
ERROR: task_entry is not a registered name for BuilderJob.

**提问：**
1、无论是提交自己写的任务或是案例的任务都会出现 XX is not a registered name for BuilderJob，但检查了类确实继承了BuilderJob，看了源码没找到问题的解决方法。请问这个该如何解决呢
2、目前项目列表只有两个项目：
![image](https://github.com/OpenSPG/openspg/assets/152193861/e8ce7ddc-9d96-46a2-ac14-9cc1fe5766cd)
，在TuGraph上看到的是两个项目的schema在同一个图里，这样是否会导致冲突呢？
![image](https://github.com/OpenSPG/openspg/assets/152193861/8e0b1d34-85e5-498e-a558-1bf59f430244)
是否需要一个任务完成后清除所有建模内容后再开始下一个任务，或者是将两个任务分开建模呢？

**Comment by andylau-55** [comment]
这里应该使用执行加工任务类名而非文件名，比如
![lQLPJwAx3rfKGCHNBOrNCUywcnAP4OG5NVoGAMX3vOnfAA_2380_1258](https://github.com/OpenSPG/openspg/assets/19925690/590035a4-86df-4fc7-9ede-a21a7d638b61)
对应为 knext builder execute Disease

**Comment by Funer100** [comment]
1、该案例修改为加工任务类名后出现另一个错误：
(openspg_venv) root@docker-desktop:/code/python/knext/knext/examples/deepke# knext builder execute Disease
ERROR: can not create invoker for NN config
问题：从原码中看，可能是没正确配置大模型？请问这里有案例可以参考吗？deepkg的案例是否能复现？
![image](https://github.com/OpenSPG/openspg/assets/152193861/d7006507-c14b-4133-afe1-f51a66c85fed)
2、自己构建的任务，提交的也是加工类任务名，却仍然报错 XX is not a registered name for BuilderJob.

**Comment by Sternstunde34** [comment]
自己构建的任务，使用knext builder execute BlockCipher一直报错ERROR: cannot unpack non-iterable NoneType object
![image](https://github.com/OpenSPG/openspg/assets/94873614/0f5e2831-0a9c-480e-bc88-0a58dca3a33f)
![image](https://github.com/OpenSPG/openspg/assets/94873614/c308e885-28c4-403b-882e-7c67f0b6d0f1)

**Comment by Sternstunde34** [comment]
> 自己构建的任务，使用knext builder execute BlockCipher一直报错ERROR: cannot unpack non-iterable NoneType object ![image](https://private-user-images.githubusercontent.com/94873614/321465820-0f5e2831-0a9c-480e-bc88-0a58dca3a33f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDYwNzQsIm5iZiI6MTcxMjgwNTc3NCwicGF0aCI6Ii85NDg3MzYxNC8zMjE0NjU4MjAtMGY1ZTI4MzEtMGE5Yy00ODBlLWJjODgtMGE1OGRjYTNhMzNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAzMjI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZmIzYzAzNjJjNzcwNjMyZmUzMDFjYWY1YTJiMmYzNDVlZTE5M2FlOTUwNjRkYzYxNjljZmYzOTJlYWU0ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7tD1--N24-ArvIwBXIUP0MLyEEdPHXpMG9H60fg_BgA) ![image](https://private-user-images.githubusercontent.com/94873614/321465969-c308e885-28c4-403b-882e-7c67f0b6d0f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDYwNzQsIm5iZiI6MTcxMjgwNTc3NCwicGF0aCI6Ii85NDg3MzYxNC8zMjE0NjU5NjktYzMwOGU4ODUtMjhjNC00MDNiLTg4MmUtN2M2N2YwYjZkMGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAzMjI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YzJkODgzNWQyYzk2OWFmZGE3ZTBjMGY4MWRlNDRiOTZhNDU1ZGU2NTQ0Y2Q4MGZkNDE1NTUxMjZlZjViYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.64sDN9FFy-ZqNhvBW6nCafWVZt8FYGIJifmgoNzgeMA) 似乎是从未成功调用大模型，apikey没有使用记录

上面用的是0.0.3b1版本，后续尝试了官方提供的医疗图谱同样倒在了这一步。
随后我尝试了回退到0.0.2b5版本才没有报错，医疗图谱运行结果如下：
![image](https://github.com/OpenSPG/openspg/assets/94873614/a086574f-2310-4b4c-a9ad-8ab488ef2284)
说明目前的0.0.3b1版本在knext builder execute命令存在执行问题🤣🤣🤣

**Comment by andylau-55** [comment]
> 1、该案例修改为加工任务类名后出现另一个错误： (openspg_venv) root@docker-desktop:/code/python/knext/knext/examples/deepke# knext builder execute Disease ERROR: can not create invoker for NN config 问题：从原码中看，可能是没正确配置大模型？请问这里有案例可以参考吗？deepkg的案例是否能复现？ ![image](https://private-user-images.githubusercontent.com/152193861/320482501-d7006507-c14b-4133-afe1-f51a66c85fed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzE0OTEsIm5iZiI6MTcxMzE3MTE5MSwicGF0aCI6Ii8xNTIxOTM4NjEvMzIwNDgyNTAxLWQ3MDA2NTA3LWMxNGItNDEzMy1hZmUxLWY1MWE2NmM4NWZlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwODUzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjQ0MjcyZTg2NGMzZDdlNWI1YzEzNTBkZjQ4M2EwMWE5N2EzYzk0M2JiMmU5NDQxM2U5YjQzZWJlMWUzMTE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8kwakn2IOVh5IiX9XgAAx-aLg1WWIcbBCbEyWsCKDxY) 2、自己构建的任务，提交的也是加工类任务名，却仍然报错 XX is not a registered name for BuilderJob.

请参考文档https://openspg.yuque.com/ndx6g9/nmwkzz/xnf98pv55cphq4id  以及  https://openspg.yuque.com/ndx6g9/nmwkzz/qmg40br79sk1b65w

**Comment by andylau-55** [comment]
> > 自己构建的任务，使用knext builder execute BlockCipher一直报错ERROR: cannot unpack non-iterable NoneType object ![image](https://private-user-images.githubusercontent.com/94873614/321465820-0f5e2831-0a9c-480e-bc88-0a58dca3a33f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDYwNzQsIm5iZiI6MTcxMjgwNTc3NCwicGF0aCI6Ii85NDg3MzYxNC8zMjE0NjU4MjAtMGY1ZTI4MzEtMGE5Yy00ODBlLWJjODgtMGE1OGRjYTNhMzNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAzMjI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZmIzYzAzNjJjNzcwNjMyZmUzMDFjYWY1YTJiMmYzNDVlZTE5M2FlOTUwNjRkYzYxNjljZmYzOTJlYWU0ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7tD1--N24-ArvIwBXIUP0MLyEEdPHXpMG9H60fg_BgA) ![image](https://private-user-images.githubusercontent.com/94873614/321465969-c308e885-28c4-403b-882e-7c67f0b6d0f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDYwNzQsIm5iZiI6MTcxMjgwNTc3NCwicGF0aCI6Ii85NDg3MzYxNC8zMjE0NjU5NjktYzMwOGU4ODUtMjhjNC00MDNiLTg4MmUtN2M2N2YwYjZkMGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAzMjI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YzJkODgzNWQyYzk2OWFmZGE3ZTBjMGY4MWRlNDRiOTZhNDU1ZGU2NTQ0Y2Q4MGZkNDE1NTUxMjZlZjViYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.64sDN9FFy-ZqNhvBW6nCafWVZt8FYGIJifmgoNzgeMA) 似乎是从未成功调用大模型，apikey没有使用记录
> 
> 上面用的是0.0.3b1版本，后续尝试了官方提供的医疗图谱同样倒在了这一步。 随后我尝试了回退到0.0.2b5版本才没有报错，医疗图谱运行结果如下： ![image](https://private-user-images.githubusercontent.com/94873614/321484528-a086574f-2310-4b4c-a9ad-8ab488ef2284.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzE0OTIsIm5iZiI6MTcxMzE3MTE5MiwicGF0aCI6Ii85NDg3MzYxNC8zMjE0ODQ1MjgtYTA4NjU3NGYtMjMxMC00YjRjLWE5YWQtOGFiNDg4ZWYyMjg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA4NTMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzYzJjNjlkZmRiMzVkNGRiNGNmMzU5NTRlMzJmNTBhZDYwZGVhOGJiOGY2MTI2OTgyZjY1Y2QyNjNhNjI5MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XA3I_C_fnE08LZFEJsB9t1Lp_wodMBj94x9aWogO2fU) 说明目前的0.0.3b1版本在knext builder execute命令存在执行问题🤣🤣🤣

是的，0.0.3b1版本最近会修复这个bug。感谢你的反馈
