### ISSUE TITLE
4.1.0版本的tugraph镜像适配情况

### ISSUE THREAD

**Issue by funnykeke** [OpenSPG/openspg#195]
4.1.0版本的tugraph镜像无法在openspg中使用，4.0.1的图数据库可视化工具较为简陋，请问什么时候可以适配新版tugraph，使用上tugraph-db-browser

**Comment by andylau-55** [comment]
非常感谢您对 OpenSPG 的关注和反馈。当前阶段还未制定tugraph的升级计划，后续迭代我们会考虑相关功能升级以减少用户使用成本 ，请持续关注OpenSPG的后续更新，也欢迎您参与到项目的社区共建中来。
