### ISSUE TITLE
knext 使用异常

### ISSUE THREAD

**Issue by coooodeXjl** [OpenSPG/openspg#2]
问题：
客户端 knext 无法初始化项目，报错
 ERROR: HTTPConnectionPool(host='localhost', port=8887): Max retries exceeded with url: /public/v1/project (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9598a22340>: Failed to establish a new connection: [Errno 111] Connection refused'))

操作流程
1.下载镜像
docker pull baifuyu/openspg
docker pull baifuyu/openspg-mysql
docker pull tugraph/tugraph-runtime-centos7:4.0.1
docker pull elasticsearch:8.5.3

2.启动服务
// docker-compose.yml 文件内容在这个页面复制
// https://spg.openkg.cn/quick-start/install

docker-compose -f docker-compose.yml up -d

3.新建客户端容器，成功安装客户端
docker run -itd python:3.8
docker exec -it 737 bash

pip install openspg-knext -i https://pypi.tuna.tsinghua.edu.cn/simple

4.客户端设置服务端地址失败
knext config set --global host_addr=http://127.0.0.1:8887
// 报错：ERROR: [Errno 2] No such file or directory: '/root/.config/.knext.cfg'

5.在指定位置创建 .knext.cfg 后，设置服务端地址，创建示例项目失败
knext project create --name 示例项目 --namespace Prj --desc 这是一个示例项目
//  报错：ERROR: HTTPConnectionPool(host='localhost', port=8887): Max retries exceeded with url: /public/v1/project (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9598a22340>: Failed to establish a new connection: [Errno 111] Connection refused'))

似乎是配置设置后未生效

**Comment by baifuyu** [comment]
> 问题： 客户端 knext 无法初始化项目，报错 ERROR: HTTPConnectionPool(host='localhost', port=8887): Max retries exceeded with url: /public/v1/project (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9598a22340>: Failed to establish a new connection: [Errno 111] Connection refused'))
> 
> 操作流程 1.下载镜像 docker pull baifuyu/openspg docker pull baifuyu/openspg-mysql docker pull tugraph/tugraph-runtime-centos7:4.0.1 docker pull elasticsearch:8.5.3
> 
> 2.启动服务 // docker-compose.yml 文件内容在这个页面复制 // https://spg.openkg.cn/quick-start/install
> 
> docker-compose -f docker-compose.yml up -d
> 
> 3.新建客户端容器，成功安装客户端 docker run -itd python:3.8 docker exec -it 737 bash
> 
> pip install openspg-knext -i https://pypi.tuna.tsinghua.edu.cn/simple
> 
> 4.客户端设置服务端地址失败 knext config set --global host_addr=http://127.0.0.1:8887 // 报错：ERROR: [Errno 2] No such file or directory: '/root/.config/.knext.cfg'
> 
> 5.在指定位置创建 .knext.cfg 后，设置服务端地址，创建示例项目失败 knext project create --name 示例项目 --namespace Prj --desc 这是一个示例项目 // 报错：ERROR: HTTPConnectionPool(host='localhost', port=8887): Max retries exceeded with url: /public/v1/project (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9598a22340>: Failed to establish a new connection: [Errno 111] Connection refused'))
> 
> 似乎是配置设置后未生效


4. knext config set --global host_addr=http://127.0.0.1:8887/    这个报错可以先手动在/root下创建.config目录，可以再次尝试下执行命令，有些系统下没有.config目录导致knext报错。
5. 这个报错的原因在于knext没有连上openspg服务端。需要确认2个点：1. 第4步配置的host_addr是服务端地址；2. openspg 的container启动大约需要1-2min，需要等container启动后再执行命令。
