### ISSUE TITLE
Error when executing knext schema commit

### ISSUE THREAD

**Issue by iwannabewater** [OpenSPG/openspg#206]
Follow the installation steps step by step, and there are no errors until this step:

>$ knext schema commit
Create type: RiskMining.TaxOfRiskUser
Create type: RiskMining.TaxOfRiskApp
Create type: RiskMining.Cert
Create type: RiskMining.App
Create type: RiskMining.Company
Create relation: [RiskMining.Company] hasCert
Create relation: [RiskMining.Company] holdShare
Create type: RiskMining.Device
Create type: RiskMining.Person
Create relation: [RiskMining.Person] hasDevice
Create relation: [RiskMining.Person] hasCert
Create relation: [RiskMining.Person] holdShare
Create relation: [RiskMining.Person] fundTrans
Create relation: [RiskMining.Person] developed
Create relation: [RiskMining.Person] release
ERROR: queryIdx error, and errorMsg=

----

This error message looks very simple. I don’t know how to debug it. I sincerely ask you for advice❤
I can provide more information if needed.

**Comment by iwannabewater** [comment]
the complete process:

## Stopping and Removing Containers and Network

```bash
docker compose down
```
Output:
```
[+] Running 5/5
 ✔ Container release-openspg-server         Removed                                                                                                                            1.6s
 ✔ Container release-openspg-tugraph        Removed                                                                                                                           10.5s
 ✔ Container release-openspg-mysql          Removed                                                                                                                            1.0s
 ✔ Container release-openspg-elasticsearch  Removed                                                                                                                            5.2s
 ✔ Network openspg_default                  Removed                                                                                                                            0.4s
```

## Starting Containers

```bash
docker compose up -d
```
Output:
```
[+] Running 4/5
 ⠋ Network openspg_default                  Created                                                                                                                            1.1s
 ✔ Container release-openspg-elasticsearch  Started                                                                                                                            0.6s
 ✔ Container release-openspg-mysql          Started                                                                                                                            0.6s
 ✔ Container release-openspg-tugraph        Started                                                                                                                            0.4s
 ✔ Container release-openspg-server         Started                                                                                                                            0.8s
```

## Running a Docker Container with Interactive Terminal

```bash
docker run --rm --net=host -v /data/xxx/openspg/openspg/:/code -it openspg/openspg-python:latest "/bin/bash"
```
Output:
```
(venv) root@host:/# cd code/python/knext/knext/examples/riskmining/
(venv) root@host:/code/python/knext/knext/examples/riskmining# ls
README.md  builder  reasoner  schema
```

## Creating a Project and Committing Schema

```bash
knext project create --prj_path .
```
Output:
```
Project [RiskMining] with namespace [RiskMining] was successfully created from [.].
```
```bash
knext schema commit
```
Output:
```
Create type: RiskMining.TaxOfRiskUser
Create type: RiskMining.TaxOfRiskApp
Create type: RiskMining.Cert
Create type: RiskMining.App
Create type: RiskMining.Company
Create relation: [RiskMining.Company] hasCert
Create relation: [RiskMining.Company] holdShare
Create type: RiskMining.Device
Create type: RiskMining.Person
Create relation: [RiskMining.Person] hasDevice
Create relation: [RiskMining.Person] hasCert
Create relation: [RiskMining.Person] holdShare
Create relation: [RiskMining.Person] fundTrans
Create relation: [RiskMining.Person] developed
Create relation: [RiskMining.Person] release
ERROR: queryIdx error, and errorMsg=
```

**Comment by andylau-55** [comment]
It seems that access to ElasticSearch failed. Please check the local ElasticSearch environment.
![image](https://github.com/OpenSPG/openspg/assets/19925690/1ecdfe25-0cfd-453f-bc27-58de7d140bec)

**Comment by iwannabewater** [comment]
Yes, I changed the elastic search port from 9200 to 9201, and the corresponding location was also changed, like this:

version: "3.7"
services:
   server:
     restart: always
     image: openspg/openspg-server:latest
     container_name: release-openspg-server
     ports:
       - "8887:8887"
     depends_on:
       - mysql
       -tugraph
       -elasticsearch
     command: [
       '--server.repository.impl.jdbc.host=mysql',
       '--server.repository.impl.jdbc.password=openspg',
       '--cloudext.graphstore.url=tugraph://tugraph:9090?graphName=default&timeout=50000&accessId=admin&accessKey=73@TuGraph',
       '--cloudext.searchengine.url=elasticsearch://elasticsearch:9201?scheme=http'
     ]

   mysql:
     restart: always
     image: openspg/openspg-mysql:latest
     container_name: release-openspg-mysql
     environment:
       TZ: Asia/Shanghai
       LANG: C.UTF-8
       MYSQL_ROOT_PASSWORD: openspg
       MYSQL_DATABASE: openspg
     ports:
       - "3307:3306"
     command: [
       '--character-set-server=utf8mb4',
       '--collation-server=utf8mb4_general_ci'
     ]

   tugraph:
     image: tugraph/tugraph-runtime-centos7:4.0.1
     container_name: release-openspg-tugraph
     # default username is admin and default password is 73@TuGraph
     ports:
       - "7070:7070"
       - "9090:9090"
     command: lgraph_server

   elasticsearch:
     image: elasticsearch:8.5.3
     container_name: release-openspg-elasticsearch
     ports:
       - "9201:9200"
       - "9300:9300"
     environment:
       - discovery.type=single-node
       -xpack.security.enabled=false

Is this yml modified incorrectly? It is normal for me to use the default port 9200, but changing it to 9201 does not work (but the elastic search container is started normally and can be accessed through curl or browser 9201). I want to know how to modify the correct yml. Thank you.

**Comment by andylau-55** [comment]
It is not recommended to make any modifications to the contents of the yml file. If you must modify it, you can try changing ports: - "9200:9200" to ports: - "9201:9200"

**Comment by andylau-55** [comment]
You need to restart your Elasticsearch container. Elasticsearch should be accessible via http://localhost:9201

**Comment by iwannabewater** [comment]
Yes, I do have access to http://localhost:9201/, but it still gives me the error "ERROR: queryIdx error, and errorMsg=", which is very strange and only works if I don't change the default port (9200) for elasticsearch. Anyway, thanks for your patience in replying
