### ISSUE TITLE
是否token身份有时间限制，长期挂载后显示jwt错误

### ISSUE THREAD

**Issue by xiaoshan0609** [OpenSPG/openspg#208]
我们的场景需要一直连着tugraph，通过TuGraphClient链接
 client = TuGraphClient(url, "admin", "73@TuGraph")
但过了一段时间，报错说jwt有问题，感觉是token身份识别码的问题？

Traceback (most recent call last):
  File "D:\software\minicoda3\envs\kg-llm\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\software\minicoda3\envs\kg-llm\lib\site-packages\nest_asyncio.py", line 154, in manage_run
    yield
  File "D:\software\minicoda3\envs\kg-llm\lib\site-packages\nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "D:\software\minicoda3\envs\kg-llm\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "D:\software\minicoda3\envs\kg-llm\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "D:\software\minicoda3\envs\kg-llm\lib\site-packages\TuGraphClient.py", line 169, in __login_and_get_host_list__
    jwt = r['jwt']
TypeError: string indices must be integers

**Comment by xiaoshan0609** [comment]
之前都是正常使用，用一段时间后，就报这个错误了，如果是需要设置身份验证的时间，请问入口在哪里呢？

**Comment by xiaoshan0609** [comment]
之前都是正常使用，用一段时间后，就报这个错误了，如果是需要设置身份验证的时间，请问入口在哪里呢？

**Comment by andylau-55** [comment]
能具体描述下在哪一步使用什么命令触发的报错吗？以及相关的上下文信息

**Comment by xiaoshan0609** [comment]
> 能具体描述下在哪一步使用什么命令触发的报错吗？以及相关的上下文信息

你好，是这样的，我用TuGraphClient 这个python库，通过 client = TuGraphClient(url, "admin", "73@TuGraph") 这个方法连接云端知识图谱，项目部署之后，刚开始一直没问题，过了快一个月，就报错说jwt的问题，如上所示。
ps：上个月也出现过一次这个现象，我们删掉了原来的tugraph docker，重新部署，就好了，这个报错看上去是身份验证失效过期的样子？ 上个月出现的时候，也是长时间运行，然后不能连了，通过tugraph客户端可以连，但无法用http接口调用，调用就报jwt的错误

**Comment by andylau-55** [comment]
OpenSPG当前使用的tugraph/tugraph-runtime-centos7:4.0.1 镜像包，内部采用的TuGraphRpcClient进行数据的查询和写入，针对http的方式可以参考TuGraph文档：https://www.oceanbase.com/docs/enterprise-tugraph-doc-cn-10000000001667858

**Comment by xiaoshan0609** [comment]
> OpenSPG当前使用的tugraph/tugraph-runtime-centos7:4.0.1 镜像包，内部采用的TuGraphRpcClient进行数据的查询和写入，针对http的方式可以参考TuGraph文档：https://www.oceanbase.com/docs/enterprise-tugraph-doc-cn-10000000001667858

你好，请问提到的 TuGraphRpcClient 是一个库吗？ 还是？如何调用呢？

**Comment by xiaoshan0609** [comment]
> > > OpenSPG当前使用的tugraph/tugraph-runtime-centos7:4.0.1 镜像包，内部采用的TuGraphRpcClient进行数据的查询和写入，针对http的方式可以参考TuGraph文档：https://www.oceanbase.com/docs/enterprise-tugraph-doc-cn-10000000001667858
> > 
> > 
> > 你好，请问提到的 TuGraphRpcClient 是一个库吗？ 还是？如何调用呢？
> 
> 参考文档：https://www.oceanbase.com/docs/enterprise-tugraph-doc-cn-10000000001669458

你好，我看了下，login时 http请求报错是这个：
{'error_message': 'Unauthorized: User has reached the maximum number of tokens.'}

**Comment by andylau-55** [comment]
> > > > OpenSPG当前使用的tugraph/tugraph-runtime-centos7:4.0.1 镜像包，内部采用的TuGraphRpcClient进行数据的查询和写入，针对http的方式可以参考TuGraph文档：https://www.oceanbase.com/docs/enterprise-tugraph-doc-cn-10000000001667858
> > > 
> > > 
> > > 你好，请问提到的 TuGraphRpcClient 是一个库吗？ 还是？如何调用呢？
> > 
> > 
> > 参考文档：https://www.oceanbase.com/docs/enterprise-tugraph-doc-cn-10000000001669458
> 
> 你好，我看了下，login时 http请求报错是这个： {'error_message': 'Unauthorized: User has reached the maximum number of tokens.'}

请参考tugraph API文档，优化Token的生成和使用策略并及时清除未使用的Token
