### ISSUE TITLE
请问V0.0.3相比V0.0.2-beta5做了哪些更新？

### ISSUE THREAD

**Issue by billc114** [OpenSPG/openspg#210]

**Comment by andylau-55** [comment]
OpenSPG v0.0.3 发布了基于OneKE 大模型统一知识抽取功能，能够帮助 OpenSPG 开发者更好地处理信息抽取、数据结构化、知识图谱构建等问题。除了大模型统一知识抽取功能，v0.0.3 还正式发布了产品可视化界面，为用户提供直观的数据探索和分析体验。帮助用户更加直观地使用 Schema 知识建模、知识加工构建、DSL 查询分析推理等相关能力。为 OpenSPG 提供可视化界面，支持用户在页面上直观的查看建模结果，并支持在界面上进行交互式分析推理查询。

**Comment by billc114** [comment]
> OpenSPG v0.0.3 发布了基于OneKE 大模型统一知识抽取功能，能够帮助 OpenSPG 开发者更好地处理信息抽取、数据结构化、知识图谱构建等问题。除了大模型统一知识抽取功能，v0.0.3 还正式发布了产品可视化界面，为用户提供直观的数据探索和分析体验。帮助用户更加直观地使用 Schema 知识建模、知识加工构建、DSL 查询分析推理等相关能力。为 OpenSPG 提供可视化界面，支持用户在页面上直观的查看建模结果，并支持在界面上进行交互式分析推理查询。

多谢！另外请问性能方面有没有更新呢？

**Comment by billc114** [comment]
> > > OpenSPG v0.0.3 发布了基于OneKE 大模型统一知识抽取功能，能够帮助 OpenSPG 开发者更好地处理信息抽取、数据结构化、知识图谱构建等问题。除了大模型统一知识抽取功能，v0.0.3 还正式发布了产品可视化界面，为用户提供直观的数据探索和分析体验。帮助用户更加直观地使用 Schema 知识建模、知识加工构建、DSL 查询分析推理等相关能力。为 OpenSPG 提供可视化界面，支持用户在页面上直观的查看建模结果，并支持在界面上进行交互式分析推理查询。
> > 
> > 
> > 多谢！另外请问性能方面有没有更新呢？
> 
> 在可控生成上发布基于构建算法逻辑的 DAG 构建执行能力，完成 LLM 的服务化：多 Lora，多 Prompt 等能力。同时也修复了之前issues遗漏的部分bug。感谢您对OpenSPG的持续关注，详细内容可关注近期官方发布的OpenSPG v0.0.3新闻稿。

好的，谢谢华仔解答
