### ISSUE TITLE
本地执行OneKE模型错误

### ISSUE THREAD

**Issue by Feynluo** [OpenSPG/openspg#212]
1）根据 https://openspg.yuque.com/ndx6g9/ps5q6b/vfoi61ks3mqwygvy, 配置本地执行OneKE模型，执行knext builder execute Disease_OneKE，提示：LLMInvoker does not support remote inference 错误，如下：
<img width="1019" alt="截屏2024-04-22 20 52 17" src="https://github.com/OpenSPG/openspg/assets/1150585/bf19ae0c-0a5f-4567-bfd6-5b911f1dc8d9">
本地依据OneKE模型官网单独执行正常，和OpenSPG结合出现上图所示错误。

2）另，是否有编写本地OneKE模型API服务端的示例，以通过API方式调用本地OneKE模型。

**Comment by chenbin11200** [comment]
@Feynluo 感谢反馈。这个问题看上去是nn4k的包比较老导致的。可以发一下你nn4k的版本号么? pip show openspg-nn4k

**Comment by Feynluo** [comment]
版本：
  Name: openspg-nn4k
  Version: 0.0.3b1
knext版本同为0.0.3b1。通过docker客户端运行也输出同样的错误。

**Comment by chenbin11200** [comment]
@Feynluo knext里需要有相关配置更新才能跑到nn4k里的新的hubInvoker，这个计划是今天打包发布，之后使用最新包应该就可以了。发布后第一时间这里通知你。
cc @andylau-55 andy @J1ers

**Comment by andylau-55** [comment]
> 版本： Name: openspg-nn4k Version: 0.0.3b1 knext版本同为0.0.3b1。通过docker客户端运行也输出同样的错误。

OpenSPG v0.0.3已正式发布，请下载最新版本latest(0.0.3-beta2)进行体验

**Comment by HildaZhan** [comment]
请问第一次使用是这样开启的

**Comment by andylau-55** [comment]
清空之前的环境，重新按照 安装说明 进行部署即可，https://openspg.yuque.com/ndx6g9/nmwkzz/xht6kkegvs33cwwr
