### ISSUE TITLE
请问project已存在，但是前端界面没有显示，是哪步操作有问题？

### ISSUE THREAD

**Issue by HildaZhan** [OpenSPG/openspg#217]
![1714007122288](https://github.com/OpenSPG/openspg/assets/107352953/0e46f503-d13b-4b4e-b888-ee84cf56ac18)
![image](https://github.com/OpenSPG/openspg/assets/107352953/1163a6e8-85b8-458a-a55b-0191912fe17f)

**Comment by andylau-55** [comment]
镜像是全新下载的0.0.3-beta2吗？还是复用之前的。之前是否执行了创建项目命令？
