### ISSUE TITLE
请问源码编译后生成的JAR包中没有静态文件，无法打开首页是哪里的问题

### ISSUE THREAD

**Issue by zjdragoon** [OpenSPG/openspg#219]
git克隆了master分支，或者直接下载tag 0.0.3-beta1，根据使用手册的编译命令mvn clean install -Dmaven.test.skip=true -Dspotless.check.skip -Dspotless.apply.skip编译后，发现生成的jar包arks-sofaboot-0.0.1-SNAPSHOT-executable.jar中没有静态文件夹static，访问网站首页提示404。
![image](https://github.com/OpenSPG/openspg/assets/42055886/ed61c1d1-5b7a-4c5a-b173-30b8f131b89a)

![image](https://github.com/OpenSPG/openspg/assets/42055886/1692dc68-83bc-4d83-9428-3d567ccce8e0)

而从docker下载的Server镜像中拷贝出来的arks-sofaboot-0.0.1-SNAPSHOT-executable.jar文件中，是有static目录的。
![image](https://github.com/OpenSPG/openspg/assets/42055886/f1eaaad1-8027-43a5-be4d-ee0dfed2b1df)

请问是我哪里的配置有问题？还是源码分支下载不对？谢谢！

**Comment by andylau-55** [comment]
目前可视化相关前端代码还未开源。如果有可视化的自定义需要可根据openspg命令进行SDK的自定义封装。

**Comment by iseelgy** [comment]
借问一下，可视化前端代码是否有计划开源？ 大概什么时候可以提供开源版本？？

**Comment by andylau-55** [comment]
> 可视化前端代码

感谢你对OpenSPG的关注。可视化前端代码暂无开源计划，用户可根据OpenSPG SDK进行自定义封装实现。
