### ISSUE TITLE
代码编译报错：reasoner下的Scala代码

### ISSUE THREAD

**Issue by the-butterfly** [OpenSPG/openspg#225]
```
reasoner\kgdsl-parser\src\main\scala\com\antgroup\openspg\reasoner\parser\LexerInit.scala:16:8

object KGDSLLexer is not a member of package com.antgroup.openspg.reasoner
import com.antgroup.openspg.reasoner.{KGDSLLexer, KGDSLParser}

object KGDSLParser is not a member of package com.antgroup.openspg.reasoner
import com.antgroup.openspg.reasoner.KGDSLParser._

```

**Comment by andylau-55** [comment]
请安装好 scala插件 ，然后把各模块对应的/src/main/scala目录都变更为sources root 再执行编译打包命令

**Comment by the-butterfly** [comment]
idea里面相关目录已经自动设置为 source root了呀，还是找不到来着，其他Scala类的import都找到了

**Comment by andylau-55** [comment]
请检查本地环境及相关配置，配置正确后编译结果如下：
![image](https://github.com/OpenSPG/openspg/assets/19925690/50467897-6867-4a6d-95d3-cba1dab2e28f)

**Comment by ai408** [comment]
我的是报这个错误：

![1](https://github.com/OpenSPG/openspg/assets/6188677/fd4ca4b3-f505-4677-8e39-0b2cc6321478)

**Comment by ai408** [comment]
增加// scalastyle:off throwerror，编译成功了：
![2](https://github.com/OpenSPG/openspg/assets/6188677/2a4bded7-3cf6-41df-977a-a8cbea879910)

**Comment by the-butterfly** [comment]
@andylau-55 请问generated-sources是从.g4文件生成的么？是通过 intelj build 命令拉起来的嘛？

**Comment by ai408** [comment]
![image](https://github.com/OpenSPG/openspg/assets/6188677/8ab63bb8-1fcb-45bc-8110-109ca65569e8)
