### ISSUE TITLE
knext builder execute Disease报错

### ISSUE THREAD

**Issue by ai408** [OpenSPG/openspg#226]
ERROR: __init__() missing 1 required positional argument: 'spg_type_name'：
![image](https://github.com/OpenSPG/openspg/assets/6188677/2b6c8750-ee89-4bbe-a7cc-99b037dabfff)

**Comment by andylau-55** [comment]
请提供完整的操作步骤，是否创建项目及schema等。同时执行 docker exec -it release-openspg-server bash 进入 logs/openspgapp 提供完整日志信息

**Comment by tianchiguaixia** [comment]
![image](https://github.com/OpenSPG/openspg/assets/29837553/e7d0f4dc-c20e-45af-ba4a-dac7c3137939)

**Comment by tianchiguaixia** [comment]
版本问题。建议都使用0.0.25b版本
