### ISSUE TITLE
源码编译失败：server/test 模块下 groovy 代码 import 失败

### ISSUE THREAD

**Issue by the-butterfly** [OpenSPG/openspg#227]
报错信息：
```

Groovyc: unable to resolve class com.antgroup.openspg.server.common.model.datasource.connection.GraphStoreConnectionInfo
Groovyc: unable to resolve class com.antgroup.openspg.cloudext.impl.searchengine.elasticsearch.ElasticSearchEngineClient
Groovyc: unable to resolve class com.antgroup.openspg.server.common.service.datasource.DataSourceService
Groovyc: unable to resolve class org.mockito.Mockito

Groovyc: unable to resolve class org.springframework.boot.test.*

```

**Comment by andylau-55** [comment]
server/test 模块为java代码，请采用java基于Maven编译。如果需要编译 reasoner包需要安装好 scala插件 ，然后把各模块对应的/src/main/scala目录都变更为sources root。单纯只做功能部署编译时 针对test 模块可以在编译时进行忽略。

**Comment by the-butterfly** [comment]
> server/test 模块为java代码，请采用java基于Maven编译。如果需要编译 reasoner包需要安装好 scala插件 ，然后把各模块对应的/src/main/scala目录都变更为sources root。单纯只做功能部署编译时 针对test 模块可以在编译时进行忽略。

是用的maven编译，intelj 自带的工具，reasoner 等其他所有模块已经编译通过，卡在 server/test 这里来着
@andylau-55
