### ISSUE TITLE
你好，我是一个对本项目感兴趣但没有工程能力的本科生，我被要求为spg增添基本的数学计算功能，需要怎么进行呢

### ISSUE THREAD

**Issue by TjuLuRui** [OpenSPG/openspg#230]
例如我导入的图谱，实体的关系有具体的数值，我希望这几个关系能进行像加减乘除平方开方这样的基本数学运算，请问我要怎么进行操作呢，tugraph的插件能支持吗，还是我需要在knext下去实现呢，由于能力有限，问题比较幼稚，希望得到答复。

**Comment by fishjoy** [comment]
可以针对你的场景举几个例子吗，我们想了解下你想解决什么样子的问题，便于评估需要支持哪些数学运算符，以及具体以什么样子的形式来辅助你完成你们得需求。

**Comment by bijinacm** [comment]
> 可以针对你的场景举几个例子吗，我们想了解下你想解决什么样子的问题，便于评估需要支持哪些数学运算符，以及具体以什么样子的形式来辅助你完成你们得需求。

例如一些询问，医疗图谱里面，我进行询问某个疾病，然后调用api进行回答
