### ISSUE TITLE
推理查询语句似乎不支持 match p = (v0:xxx)->(v1:yyy) return p 这种写法？

### ISSUE THREAD

**Issue by the-butterfly** [OpenSPG/openspg#232]

**Comment by youdonghai** [comment]
是的，不支持。
如果需要返回路径，我们的语法是：match (v0:xxx)->(v1:yyy) return __path__

**Comment by the-butterfly** [comment]
> 是的，不支持。 如果需要返回路径，我们的语法是：match (v0:xxx)->(v1:yyy) return **path**

@youdonghai 这种写法也有问题，执行：
``` kgdsl
MATCH
    (phone:STD.ChinaMobile)<-[:hasPhone]-(u:RiskMining.Person)
RETURN
    path
```
报错：
`KGReasonerLocalRunner,error:not found variable: IRVariable(path) com.antgroup.openspg.reasoner.common.exception.InvalidRefVariable: not found variable: IRVariable(path) at com.antgroup.openspg.reasoner.lube.logical.SolvedModel.getField(SolvedModel.scala:41) at com.antgroup.openspg.reasoner.lube.logical.planning.LogicalPlanner$$anonfun$1.apply(LogicalPlanner.scala:74) at com.antgroup.openspg.reasoner.lube.logical.planning.LogicalPlanner$$anonfun$1.apply(LogicalPlanner.scala:69) at scala.collection.immutable.List.map(List.scala:284) at com.antgroup.openspg.reasoner.lube.logical.planning.LogicalPlanner$.plan(LogicalPlanner.scala:69) at com.antgroup.openspg.reasoner.lube.logical.planning.SubQueryPlanner$$anonfun$plan$2.apply(SubQueryPlanner.scala:39) at com.antgroup.openspg.reasoner.lube.logical.planning.SubQueryPlanner$$anonfun$plan$2.apply(SubQueryPlanner.scala:39) at com.antgroup.openspg.reasoner.lube.logical.validate.Dag$$anonfun$map$1.apply(Dag.scala:76) at com.antgroup.openspg.reasoner.lube.logical.validate.Dag$$anonfun$map$1.apply(Dag.scala:75) at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130) at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130) at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:236) at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40) at scala.collection.mutable.HashMap.foreach(HashMap.scala:130) at com.antgroup.openspg.reasoner.lube.logical.validate.Dag.map(Dag.scala:75) at com.antgroup.openspg.reasoner.lube.logical.planning.SubQueryPlanner.plan(SubQueryPlanner.scala:39) at com.antgroup.openspg.reasoner.lube.logical.planning.LogicalPlanner$.plan(LogicalPlanner.scala:47) at com.antgroup.openspg.reasoner.session.KGReasonerSession.plan2LogicalPlan(KGReasonerSession.scala:331) at com.antgroup.openspg.reasoner.session.KGReasonerSession.plan2OptimizedLogicalPlan(KGReasonerSession.scala:189) at com.antgroup.openspg.reasoner.session.KGReasonerSession.planBlock(KGReasonerSession.scala:172) at com.antgroup.openspg.reasoner.session.KGReasonerSession.plan(KGReasonerSession.scala:165) at com.antgroup.openspg.reasoner.runner.local.LocalReasonerRunner.doRun(LocalReasonerRunner.java:114) at com.antgroup.openspg.reasoner.runner.local.LocalReasonerRunner.run(LocalReasonerRunner.java:70) at com.antgroup.openspgapp.core.reasoner.service.impl.TaskRunner$ReasonerLocalTask.call(TaskRunner.java:107) at com.antgroup.openspgapp.core.reasoner.service.impl.TaskRunner$ReasonerLocalTask.call(TaskRunner.java:80) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:750)
`

**Comment by andylau-55** [comment]
DSL详细使用语法可参考文档：https://openspg.yuque.com/ndx6g9/nmwkzz/pgslo9omezpm8xf7

**Comment by the-butterfly** [comment]
> DSL详细使用语法可参考文档：https://openspg.yuque.com/ndx6g9/nmwkzz/pgslo9omezpm8xf7

@andylau-55 这里面也没有我的问题呀，只是match里面的内容吧（define structure action）？没有return的内容呀？
