### ISSUE TITLE
执行 knext builder execute Disease 报错： ERROR: REPrompt.__init__() missing 1 required positional argument: 'spg_type_name'

### ISSUE THREAD

**Issue by lizhongxiang12138** [OpenSPG/openspg#236]
执行 knext builder execute Disease 报错：
Connected to pydev debugger (build 223.7571.203)
ERROR: REPrompt.__init__() missing 1 required positional argument: 'spg_type_name'
prompt_config 没有 params 参数
<img width="2045" alt="image" src="https://github.com/OpenSPG/openspg/assets/20783890/71ce0645-ba53-4c52-bb85-3855c0a22cc1">
<img width="1458" alt="image" src="https://github.com/OpenSPG/openspg/assets/20783890/104082fd-1e9d-4399-9621-6ae86cb58672">

**Comment by ZhiLyu** [comment]
+1

**Comment by tianchiguaixia** [comment]
+1

**Comment by abcFlyCoder** [comment]
同上报错：
<img width="652" alt="4d5f510066788ef13aa9341c217e17a" src="https://github.com/OpenSPG/openspg/assets/46623278/6135c721-bbb6-4ba8-bc3a-4f494d3b8e79">

**Comment by tianchiguaixia** [comment]
我解决了。因为版本问题。你直接参考语雀那个0.2版本操作。
![50cb3feff37663f0f69ec30691bdb4a](https://github.com/OpenSPG/openspg/assets/29837553/a6c108e9-a0e9-4a94-9810-91d8ddb99de0)
![7d8bff0c1d8a5a5a67c908df47cfe84](https://github.com/OpenSPG/openspg/assets/29837553/fa343550-2393-469d-8748-6b724dfbe52d)

**Comment by abcFlyCoder** [comment]
能再具体点不，我看0.2和0.3的教程一模一样

**Comment by andylau-55** [comment]
感谢对OpenSPG的关注。这是一个bug，我们会在下个版本进行彻底解决，目前可在本地环境执行下 pip install openspg-knext -U 命令升级下knext版本进行解决

**Comment by myboyliu2025** [comment]
请问一下你的idea debug模型怎么设置。@lizhongxiang12138
