### ISSUE TITLE
医疗demo，执行推理出错 

### ISSUE THREAD

**Issue by lizhongxiang12138** [OpenSPG/openspg#239]
推理报错
MATCH
    (s:Medical.Disease)-[p]->(o)
RETURN
    s
执行失败KGReasonerLocalRunner,error:Cannot find s in Map(s -> Set(), p -> Set(), o -> Set()) com.antgroup.openspg.reasoner.common.exception.SchemaException: Cannot find s in Map(s -> Set(), p -> Set(), o -> Set()) at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$$anonfun$com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$fieldToVar$1.apply(Validator.scala:130) at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$$anonfun$com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$fieldToVar$1.apply(Validator.scala:126) at scala.collection.immutable.List.foreach(List.scala:392) at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$.com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$fieldToVar(Validator.scala:126) at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$$anonfun$com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$resolve$1.apply(Validator.scala:112) at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$$anonfun$com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$resolve$1.apply(Validator.scala:107) at com.antgroup.openspg.reasoner.common.trees.Transform.transform(TreeTransformer.scala:179) at com.antgroup.openspg.reasoner.common.trees.Transform.transform(TreeTransformer.scala:174) at com.antgroup.openspg.reasoner.common.trees.AbstractTreeNode.transform(AbstractTreeNode.scala:60) at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$.com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$resolve(Validator.scala:107) at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$.validate(Validator.scala:52) at com.antgroup.openspg.reasoner.session.KGReasonerSession.plan2LogicalPlan(KGReasonerSession.scala:325) at com.antgroup.openspg.reasoner.session.KGReasonerSession.plan2OptimizedLogicalPlan(KGReasonerSession.scala:189) at
![image](https://github.com/OpenSPG/openspg/assets/20783890/7f2bb1d1-c329-4289-b072-a49bdbf81e1f)
图数据有数据
![image](https://github.com/OpenSPG/openspg/assets/20783890/4ab3157f-da35-4c00-998a-295bfa041e35)

**Comment by fishjoy** [comment]
根据你的截图，推理里面的类型写错了。
在截图二里面看到疾病的类型全名是Medicine.Disease，你写的是：s:Medical.Disease
这个错误是因为p和o都是匿名的，Lube里面会进行类型推导，但是因为类型写错了，推导之后是空的，这里提示没做好，我们后续完善下。
