### ISSUE TITLE
关于SPG框架中，用规则定义的关系，在源节点发生变化时，更新的方式

### ISSUE THREAD

**Issue by zwx1185** [OpenSPG/openspg#24]
尊敬的OpenSPG开发团队，您好！

相就规则定义的关系和您讨论一些实现细节，主要疑惑如下：

例如在企业供应链demo中，有一个mainSupply（主要供应商）的关系，是由规则定义的。我对于SPG的这一特性，暂时理解是类似于DB的视图，使用用户定义好的rule，去扫描一遍现有的图谱，然后为company节点更新关系。

因此目前有两个疑惑：

其一是：当源节点发生变化时，服务端会检测到变化，自动把受影响的关系进行更新，还是需要开发者手动更新？例如，第一次建立后，A公司的主要供应商是C公司，根据规则，他们之间建立的mainSupply的关系。之后C公司的产品发生了变化，图谱中进行了修改，不再满足mainSupply的rule。此时A和C之间的主供应商关系会同步删除吗？

其二是：关于上述问题，引申出的问题是，用规则定义的关系，会在扫描并生成后，持久化到节点上，作为一个实实在在存在的新的关系？还是说节点上存储的始终只是对关系的rule定义，需要用到这个关系的时候，再立即根据rule定义，去扫描图谱，生成关系。

期待您的答疑解惑！

**Comment by baifuyu** [comment]
> 尊敬的OpenSPG开发团队，您好！
> 
> 相就规则定义的关系和您讨论一些实现细节，主要疑惑如下：
> 
> 例如在企业供应链demo中，有一个mainSupply（主要供应商）的关系，是由规则定义的。我对于SPG的这一特性，暂时理解是类似于DB的视图，使用用户定义好的rule，去扫描一遍现有的图谱，然后为company节点更新关系。
> 
> 因此目前有两个疑惑：
> 
> 其一是：当源节点发生变化时，服务端会检测到变化，自动把受影响的关系进行更新，还是需要开发者手动更新？例如，第一次建立后，A公司的主要供应商是C公司，根据规则，他们之间建立的mainSupply的关系。之后C公司的产品发生了变化，图谱中进行了修改，不再满足mainSupply的rule。此时A和C之间的主供应商关系会同步删除吗？
> 
> 其二是：关于上述问题，引申出的问题是，用规则定义的关系，会在扫描并生成后，持久化到节点上，作为一个实实在在存在的新的关系？还是说节点上存储的始终只是对关系的rule定义，需要用到这个关系的时候，再立即根据rule定义，去扫描图谱，生成关系。
> 
> 期待您的答疑解惑！

hi您好，逻辑规则在OpenSPG是不会去物化数据的，只会在schema上存储这些规则，在使用（比如推理）时去实时计算出来的。所以针对问题1，由于mainSupply关系是不会物化的，底层数据变化后，mainSupply会自动变化。针对问题2，在我们实践中，可以在知识构建阶段去物化逻辑规则对应的数据，也可以选择不物化。不物化的好处就是可以底层数据随时变动，逻辑规则就跟着变动，物化之后逻辑规则对应的数据就写死到图谱了，需要手动更新了。

再延伸一点，OpenSPG其实把图谱分为2层，正如供应链例子和黑产的例子，一层是底层的fact数据，还有一层是上层的逻辑或者专家规则，比如产业链图谱的例子里面这张图显示 （https://spg.openkg.cn/example/risk-mining#%E9%BB%91%E4%BA%A7%E6%8C%96%E6%8E%98%E5%9B%BE%E8%B0%B1 ）

**Comment by royzhao** [comment]
hi，您好，openSPG对比纯属性图的一个重大改进就是通过逻辑规则表达图结构。原有的属性图方案中，会要求所有的点边数据必须都导入，这样必然会导致图数据的不一致，例如公司C的产品发生了变化，不再是A公司的主要供应商，在原来的属性图中，这个供应商关系不会变化，导致图数据产生不一致，这个是动态的事实和静态的数据矛盾，为解决这一矛盾，SPG提出使用逻辑依赖替代数据依赖，具体可以参见SPG白皮《第 2 章 基于属性图的知识管理存在的问题》

**Comment by royzhao** [comment]
针对第二个问题，我们设计了一套推理执行引擎，属于后向推理器，会根据查询请求解析依赖规则，并且生成执行计划，这部分是在代码中的reasoner文件夹中，不过代码尚未准备完毕，2023.12月底会将代码push到仓库

**Comment by zwx1185** [comment]
非常感谢您快速而详细的解答！对这个问题现在比较清楚了，OpenSPG把图谱分为两层的设计很巧妙，我会再认真学习一下框架设计~
