### ISSUE TITLE
可以在文档中注明一下需要在构建文件中写lead_to = True才能触发concept.rule中的推理

### ISSUE THREAD

**Issue by Joyce-ZhouY** [OpenSPG/openspg#240]
在注册 `knext schema reg_concept_rule --file ./schema/concept.rule` 后，执行knext build 构建的时候没有触发concept.rule里相关的推理。查看builder/client.py 后发现是没有`leadTo`这个参数。查看代码后，发现`leadTo`这个参数需要写在构建任务的py文件中，比如SupplyChain例子：
![image](https://github.com/OpenSPG/openspg/assets/59710320/678ffda6-2cc0-4b2e-b35a-2e75c284ab2d)
这个是否可以写在文档中注明一下，谢谢~

**Comment by the-butterfly** [comment]
我说为啥在推理时候报错了，原来是这里没改。。

**Comment by andylau-55** [comment]
感谢你的反馈，leadTo的具体用法我们会更新到对应文档中

**Comment by andylau-55** [comment]
https://openspg.yuque.com/ndx6g9/nmwkzz/egceglvxrcfgovny#Htqvm
