### ISSUE TITLE
MATCH 查询如何加条件

### ISSUE THREAD

**Issue by lizhongxiang12138** [OpenSPG/openspg#242]
MATCH (n:Travel.Travel{id:'滇西全景：大理、丽江、玉龙雪山、泸沽湖、香巴拉7天6晚休闲度假旅行'})-[p]-(o)-[pp]-(oo) RETURN n,p,o,pp,oo
比如我这样写是报错的

**Comment by lizhongxiang12138** [comment]
![image](https://github.com/OpenSPG/openspg/assets/20783890/98e50d06-f2c1-4e85-8711-8bd538ef0204)

MATCH (s:`Travel.Travel`/`滇西全景：大理、丽江、玉龙雪山、泸沽湖、香巴拉7天6晚休闲度假旅行`) 
RETURN s.id
-------
执行失败KGReasonerLocalRunner,error:Cannot find s in Map(s -> Set(), C_2 -> Set(), E_C_2 -> Set()) com.antgroup.openspg.reasoner.common.exception.SchemaException: Cannot find s in Map(s -> Set(), C_2 -> Set(), E_C_2 -> Set()) at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$$anonfun$com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$fieldToVar$1.apply(Validator.scala:130) at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$$anonfun$com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$fieldToVar$1.apply(Validator.scala:126) at scala.collection.immutable.List.foreach(List.scala:392) at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$.com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$fieldToVar(Validator.scala:126) at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$$anonfun$com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$resolve$1.apply(Validator.scala:112) at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$$anonfun$com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$resolve$1.apply(Validator.scala:107) at com.antgroup.openspg.reasoner.common.trees.Transform.transform(TreeTransformer.scala:179) at com.antgroup.openspg.reasoner.common.trees.Transform.transform(TreeTransformer.scala:174) at com.antgroup.openspg.reasoner.common.trees.AbstractTreeNode.transform(AbstractTreeNode.scala:60) at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$.com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$resolve(Validator.scala:107) at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$.validate(Validator.scala:52) at com.antgroup.openspg.reasoner.session.KGReasonerSession.plan2LogicalPlan(KGReasonerSession.scala:325) at com.antgroup.openspg.reasoner.session.KGReasonerSession.plan2OptimizedLogicalPlan(KGReasonerSession.scala:189) at com.antgroup.openspg.reasoner.session.KGReasonerSession.planBlock(KGReasonerSession.scala:172) at com.antgroup.openspg.reasoner.session.KGReasonerSession.plan(KGReasonerSession.scala:165) at com.antgroup.openspg.reasoner.runner.local.LocalReasonerRunner.doRun(LocalReasonerRunner.java:114) at com.antgroup.openspg.reasoner.runner.local.LocalReasonerRunner.run(LocalReasonerRunner.java:70) at com.antgroup.openspgapp.core.reasoner.service.impl.TaskRunner$ReasonerLocalTask.call(TaskRunner.java:107) at com.antgroup.openspgapp.core.reasoner.service.impl.TaskRunner$ReasonerLocalTask.call(TaskRunner.java:80) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:750)
在 tugraph有数据
![image](https://github.com/OpenSPG/openspg/assets/20783890/4ff931fa-9c41-471c-b978-b859ab60e128)

**Comment by fishjoy** [comment]
写的语法不对，试试这样写：
```
MATCH (s:Travel.Travel)
WHERE id = '滇西全景：大理、丽江、玉龙雪山、泸沽湖、香巴拉7天6晚休闲度假旅行'
RETURN s.id
```
