### ISSUE TITLE
实体属性的子属性在导入时应该怎么导入呢

### ISSUE THREAD

**Issue by AnYingLieShouTuT** [OpenSPG/openspg#245]
```
Atest(测试): EntityType
	properties:
		friend(朋友): Person
			properties:
				alias(别名): Text
```
builder_job的代码应该怎么写

**Comment by andylau-55** [comment]
请参考python/knext/knext/examples目录下示例

**Comment by AnYingLieShouTuT** [comment]
> 请参考python/knext/knext/examples目录下示例

您好，示例里好像没有关于属性的子属性的导入方法

**Comment by andylau-55** [comment]
提交schema后会生成 schema helper。可参考schema helper文件中的对象进行映射和知识构建
