### ISSUE TITLE
openspg源码新增的名为“oneke”的案例和用户手册中“oneke使用文档”给出的医疗示例不一样，能否提供一个详细的“oneke”案例体验说明

### ISSUE THREAD

**Issue by MN-LYR** [OpenSPG/openspg#247]

**Comment by MN-LYR** [comment]
oneke案例使用时报错如下：
![image](https://github.com/OpenSPG/openspg/assets/114985353/a5389586-8b20-4dff-a1cd-ae2c3ba56cf3)
执行命令knext builder execute OneKE_EE,OneKE_KG,OneKE_NER后
报错cannot decode config file，请问是什么原因

**Comment by MN-LYR** [comment]
![image](https://github.com/OpenSPG/openspg/assets/114985353/4a3ab286-fb8e-4758-a1f8-f8ec4405a389)
"hub_infer_url": "http://127.0.0.1:8000/v2/models/vllm_model/generate"这个服务接口是什么

**Comment by lsy643** [comment]
> ![image](https://private-user-images.githubusercontent.com/114985353/330249241-4a3ab286-fb8e-4758-a1f8-f8ec4405a389.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzM1MTMsIm5iZiI6MTcxNjE3MzIxMywicGF0aCI6Ii8xMTQ5ODUzNTMvMzMwMjQ5MjQxLTRhM2FiMjg2LWZiOGUtNDc1OC1hMWY4LWY4ZWM0NDA1YTM4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwMjQ2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGZlNWZiODMyZGIyOTQyZGMwYzZhMTE4YTkzNGE1NzE4MjIwODNlZTU1YmU2NDgxOTVhYjhhZGEzMmIyZDJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fmfFxsxQhqBewD2w5Bcd2mZfJtZvQkaJJ-1aX9ZlAqE) "hub_infer_url": "[http://127.0.0.1:8000/v2/models/vllm_model/generate"这个服务接口是什么](http://127.0.0.1:8000/v2/models/vllm_model/generate%22%E8%BF%99%E4%B8%AA%E6%9C%8D%E5%8A%A1%E6%8E%A5%E5%8F%A3%E6%98%AF%E4%BB%80%E4%B9%88) 我在autodl上部署了OneKE模型，我该如何调用该模型的服务


这个是一个需要自己部署的大模型的服务，如果你自己的GPU（比如A100, A10）的服务器，可以自己搭建一个类似的服务。
具体可以参考这个文档：https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html

**Comment by MN-LYR** [comment]
> > ![image](https://private-user-images.githubusercontent.com/114985353/330249241-4a3ab286-fb8e-4758-a1f8-f8ec4405a389.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzM1MTMsIm5iZiI6MTcxNjE3MzIxMywicGF0aCI6Ii8xMTQ5ODUzNTMvMzMwMjQ5MjQxLTRhM2FiMjg2LWZiOGUtNDc1OC1hMWY4LWY4ZWM0NDA1YTM4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwMjQ2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGZlNWZiODMyZGIyOTQyZGMwYzZhMTE4YTkzNGE1NzE4MjIwODNlZTU1YmU2NDgxOTVhYjhhZGEzMmIyZDJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fmfFxsxQhqBewD2w5Bcd2mZfJtZvQkaJJ-1aX9ZlAqE) "hub_infer_url": "[http://127.0.0.1:8000/v2/models/vllm_model/generate"这个服务接口是什么](http://127.0.0.1:8000/v2/models/vllm_model/generate%22%E8%BF%99%E4%B8%AA%E6%9C%8D%E5%8A%A1%E6%8E%A5%E5%8F%A3%E6%98%AF%E4%BB%80%E4%B9%88) 我在autodl上部署了OneKE模型，我该如何调用该模型的服务
> 
> 这个是一个需要自己部署的大模型的服务，如果你自己的GPU（比如A100, A10）的服务器，可以自己搭建一个类似的服务。 具体可以参考这个文档：https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html

@lsy643 我用4090的显卡部署显示cuda out of memory，24G的显存是不是不够，或者是还有什么其他问题？
