### ISSUE TITLE
自然语言推理

### ISSUE THREAD

**Issue by lizhongxiang12138** [OpenSPG/openspg#248]
<img width="1785" alt="image" src="https://github.com/OpenSPG/openspg/assets/20783890/cf0dad6e-56af-4bf1-a77c-a17d61ae9534">
如何使用自然语言进行推理，部署后是灰色的点不动

**Comment by andylau-55** [comment]
自然语言相关内容目前正在研发联调中，请持续关注OpenSPG的后续更新。
