### ISSUE TITLE
请问怎么修改和更新用dsl匹配到的实体的属性？

### ISSUE THREAD

**Issue by AnYingLieShouTuT** [OpenSPG/openspg#250]
是否支持更新规则匹配到的实体的属性

**Comment by fishjoy** [comment]
在OpenSPG现有的实现中，我们是不支持修改图谱中的数据的，数据只能通过构建链路来修改。

**Comment by AnYingLieShouTuT** [comment]
> 在OpenSPG现有的实现中，我们是不支持修改图谱中的数据的，数据只能通过构建链路来修改。

好的，感谢解答！
