### ISSUE TITLE
oneke分析推理自然语言无法使用

### ISSUE THREAD

**Issue by zhanglih** [OpenSPG/openspg#254]
<img width="949" alt="图片1" src="https://github.com/OpenSPG/openspg/assets/14040497/1c8cfbb6-6ba9-4df8-ba49-7b88485e603b">

**Comment by andylau-55** [comment]
自然语言相关能力目前还在开发测试中，预计在后续版本中会进行发布。可关注OpenSPG官方发版推送

**Comment by evilbear** [comment]
这个功能有预计的发布时间不
