### ISSUE TITLE
NN4K本地推理报错

### ISSUE THREAD

**Issue by zhanglih** [OpenSPG/openspg#259]
执行脚本:
from nn4k.invoker.base import NNInvoker
infer_invoker = NNInvoker.from_config("inference_config.json5")
print(infer_invoker.local_inference("how can I use LLM?"))

报错内容:
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
/home/deploy/miniconda3/envs/onekey_v3/lib/python3.10/site-packages/transformers/generation/utils.py:1355: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
['']

**Comment by chenbin11200** [comment]
用的是什么基座模型呢？有些模型是有eos_token_id的要求的，一般模型发布者会有说明
可以看一下这个：https://stackoverflow.com/questions/69609401/suppress-huggingface-logging-warning-setting-pad-token-id-to-eos-token-id
这种自定义的config，可以写在这里
![image](https://github.com/OpenSPG/openspg/assets/5245644/bff3a967-8865-4b73-aa26-43daf3686175)
