### ISSUE TITLE
查询语句

### ISSUE THREAD

**Issue by hfwangxxx** [OpenSPG/openspg#260]
![Uploading 2024523103210.jpg…]()

**Comment by hfwangxxx** [comment]
![2024523103210](https://github.com/OpenSPG/openspg/assets/101462593/11b0130e-4e12-4634-9866-f16d573edc40)

**Comment by hfwangxxx** [comment]
![2024523103210](https://github.com/OpenSPG/openspg/assets/101462593/566e086b-1db4-4012-8753-b2b343595205)

**Comment by hfwangxxx** [comment]
执行失败KGReasonerLocalRunner,error:Cannot find s in Map(s -> Set(), p -> Set(), o -> Set()) com.antgroup.openspg.reasoner.common.exception.SchemaException: Cannot find s in Map(s -> Set(), p -> Set(), o -> Set()) at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$$anonfun$com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$fieldToVar$1.apply(Validator.scala:130) at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$$anonfun$com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$fieldToVar$1.apply(Validator.scala:126) at scala.collection.immutable.List.foreach(List.scala:392) at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$.com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$fieldToVar(Validator.scala:126) at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$$anonfun$com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$resolve$1.apply(Validator.scala:112) at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$$anonfun$com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$resolve$1.apply(Validator.scala:107) at com.antgroup.openspg.reasoner.common.trees.Transform.transform(TreeTransformer.scala:179) at com.antgroup.openspg.reasoner.common.trees.Transform.transform(TreeTransformer.scala:174) at com.antgroup.openspg.reasoner.common.trees.AbstractTreeNode.transform(AbstractTreeNode.scala:60) at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$.com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$resolve(Validator.scala:107) at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$.validate(Validator.scala:52) at com.antgroup.openspg.reasoner.session.KGReasonerSession.plan2LogicalPlan(KGReasonerSession.scala:325) at com.antgroup.openspg.reasoner.session.KGReasonerSession.plan2OptimizedLogicalPlan(KGReasonerSession.scala:189) at com.antgroup.openspg.reasoner.session.KGReasonerSession.planBlock(KGReasonerSession.scala:172) at com.antgroup.openspg.reasoner.session.KGReasonerSession.plan(KGReasonerSession.scala:165) at com.antgroup.openspg.reasoner.runner.local.LocalReasonerRunner.doRun(LocalReasonerRunner.java:114) at com.antgroup.openspg.reasoner.runner.local.LocalReasonerRunner.run(LocalReasonerRunner.java:70) at com.antgroup.openspgapp.core.reasoner.service.impl.TaskRunner$ReasonerLocalTask.call(TaskRunner.java:107) at com.antgroup.openspgapp.core.reasoner.service.impl.TaskRunner$ReasonerLocalTask.call(TaskRunner.java:80) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:750)

**Comment by andylau-55** [comment]
请阐述下具体操作流程，如何触发的该异常信息

**Comment by hfwangxxx** [comment]
仅仅是在服务端的推理界面执行了一个DSL语句，但是报错

**Comment by andylau-55** [comment]
请提供下具体操作的流程，你貌似上传了图片失败了导致无法打开。
