### ISSUE TITLE
关于官方文档中的示例有一些问题

### ISSUE THREAD

**Issue by hfwangxxx** [OpenSPG/openspg#261]
请问下官方文档中医疗图谱案例，我看还提供了BodyPart.csv、HospitalDepartment.csv文件，并且在builder/job/disease.py的代码里也引入了，它的作用是什么呢？

**Comment by andylau-55** [comment]
csv是基础数据，是人体器官和医院科室的数据。python代码是疾病的构建任务，产生的数据跟器官和科室的连接
