### ISSUE TITLE
ERROR: com.antgroup.tugraph.TuGraphDbRpcException: pair_unique and unique configuration cannot occur simultaneously

### ISSUE THREAD

**Issue by lizhongxiang12138** [OpenSPG/openspg#263]
提交 knext schema commit
TuGraphDb：v4.3.0

ERROR: com.antgroup.tugraph.TuGraphDbRpcException: pair_unique and unique configuration cannot occur simultaneously

**Comment by andylau-55** [comment]
具体是提交的那个项目的schema咧，可查看schema目录下对应的xxx.schema配置文件根据异常提示进行排查，确认是否同时对某个属性或属性组合使用了unique和pair_unique约束。根

**Comment by andylau-55** [comment]
感谢你对OpenSPG的关注，当前OpenSPG对应的TuGraphDb版本为4.0.1，更高版本的TuGraphDb适配需等后续OpenSPG的版本更新。
