### ISSUE TITLE
概念类型和实体类型应该怎么划分呢

### ISSUE THREAD

**Issue by YYGe01** [OpenSPG/openspg#265]
您好，以[openspg/tree/master/python/knext/knext/examples/medicine](https://github.com/OpenSPG/openspg/blob/master/python/knext/knext/examples/medicine/schema/medicine.schema)

为例：

```
namespace Medicine

Symptom(症状): EntityType
    desc: 这是一个症状

Drug(药品): EntityType

Indicator(医学指征): EntityType

BodyPart(人体部位): ConceptType
    hypernymPredicate: isA

HospitalDepartment(医院科室): ConceptType
    hypernymPredicate: isA

Disease(疾病): EntityType
    properties:
        complication(并发症): Disease
            constraint: MultiValue
        commonSymptom(常见症状): Symptom
            constraint: MultiValue
        applicableDrug(适用药品): Drug
            constraint: MultiValue
        department(就诊科室): HospitalDepartment
            constraint: MultiValue
        diseaseSite(发病部位): BodyPart
            constraint: MultiValue
    relations:
        abnormal(异常指征): Indicator
            properties:
                range(指标范围): Text
                color(颜色): Text
                shape(性状): Text
```

这里的BodyPart(人体部位)、HospitalDepartment(医院科室) 为什么作为概念类型，
和实体类型：applicableDrug(适用药品)、commonSymptom(常见症状)、complication(并发症) 区别在哪，

一般区分原则是什么呢，谢谢

**Comment by YYGe01** [comment]
还有再问下properties属性和relations关系如何划分，
abnormal(异常指征): Indicator 为什么作为关系，而其他的并发症之类的，作为属性。

我看白皮书37页有说明：关系的定义和属性基本一致，表达同一个复杂对象与其他对象之间的关联，关系和
属性的区别是，若关联对象为实体类型则为关系。

那以这种说法，Disease(疾病): EntityType 下面都应该是关系，而不是属性。

**Comment by matthewhyx** [comment]
简单来说，实体用于表达复杂多元结构，也就是用若干属性来描述一个具体客观事物。概念是一个词汇，没有结构，主要通过关系来表达概念之间的语义联系。更详细的解读可以参考这篇讲建模实践的文档：https://openspg.yuque.com/ndx6g9/ooil9x/ou318zk5li1fght3。
所以，您提到的人体部位和医院科室是概念的原因是我们没有对这两个类型创建额外的属性进行描述，只是用上下位关系来表述人体部位、科室之间的层级，所以选择了用概念类型建模。

您提到的第二个问题，如果涉及到同一个谓词需要指向多个类型，举个例子比如有“治疗方案”这个关系会指向“手术”和“药品”，就没有办法用属性表达，因为目前属性上不支持表达多类型。可以作如下表达，并且不同的关系还可以有不同的属性：
relations:
    treatment(治疗方案): Drug
        properties:
             usage(用法用量): Text
    treatment(治疗方案): Operation
        properties:
             risk(手术风险): Text

**Comment by LLL1st** [comment]
您好，在这篇文章中https://mp.weixin.qq.com/s/XKbrPe4uXrzS_qQbPFyLmw?poc_token=HENbdGaj6HGH9u78OhzHrYLqZb2_vimOqJVuNxzO，建模时先创建一个“商铺”的实体类型，然后再为这个实体类型创建一个“商铺分类”的概念类型用于分类：
`namespace World
 2TaxonomyOfShop(商铺分类): ConceptType
 3  hypernymPredicate: isA
 4Shop(商铺): EntityType
 5  desc: 诸如便利店和加油站等
 6  properties:
 7     locateArea(所在区域): AdministractiveArea
 8     address(地址): Text     
 9     contactPhone(联系电话): STD.ChinaTelCode
10     IND#belongTo(属于): TaxonomyOfShop`
假设我有一个实体A，它的属性是商铺，我应该写Shop还是TaxonomyOfShop呢？

**Comment by matthewhyx** [comment]
> 您好，在这篇文章中[https://mp.weixin.qq.com/s/XKbrPe4uXrzS_qQbPFyLmw?poc_token=HENbdGaj6HGH9u78OhzHrYLqZb2_vimOqJVuNxzO，建模时先创建一个“商铺”的实体类型，然后再为这个实体类型创建一个“商铺分类”的概念类型用于分类：](https://mp.weixin.qq.com/s/XKbrPe4uXrzS_qQbPFyLmw?poc_token=HENbdGaj6HGH9u78OhzHrYLqZb2_vimOqJVuNxzO%EF%BC%8C%E5%BB%BA%E6%A8%A1%E6%97%B6%E5%85%88%E5%88%9B%E5%BB%BA%E4%B8%80%E4%B8%AA%E2%80%9C%E5%95%86%E9%93%BA%E2%80%9D%E7%9A%84%E5%AE%9E%E4%BD%93%E7%B1%BB%E5%9E%8B%EF%BC%8C%E7%84%B6%E5%90%8E%E5%86%8D%E4%B8%BA%E8%BF%99%E4%B8%AA%E5%AE%9E%E4%BD%93%E7%B1%BB%E5%9E%8B%E5%88%9B%E5%BB%BA%E4%B8%80%E4%B8%AA%E2%80%9C%E5%95%86%E9%93%BA%E5%88%86%E7%B1%BB%E2%80%9D%E7%9A%84%E6%A6%82%E5%BF%B5%E7%B1%BB%E5%9E%8B%E7%94%A8%E4%BA%8E%E5%88%86%E7%B1%BB%EF%BC%9A) `namespace World 2TaxonomyOfShop(商铺分类): ConceptType 3 hypernymPredicate: isA 4Shop(商铺): EntityType 5 desc: 诸如便利店和加油站等 6 properties: 7 locateArea(所在区域): AdministractiveArea 8 address(地址): Text 9 contactPhone(联系电话): STD.ChinaTelCode 10 IND#belongTo(属于): TaxonomyOfShop` 假设我有一个实体A，它的属性是商铺，我应该写Shop还是TaxonomyOfShop呢？

您好，如果实体A要表达跟某一个具体商铺的关联，就写Shop，比如A如果是自然人Person，可以有属性:"runningShop(经营店铺): Shop"；如果是表达A跟某一类商铺的关联，就写TaxonomyOfShop，比如:"proficient(擅长经营店铺门类): TaxonomyOfShop"。
