### ISSUE TITLE
请问，Action中的get方法还没有实现吗？用的时候会报错。

### ISSUE THREAD

**Issue by AnYingLieShouTuT** [OpenSPG/openspg#266]
```
//可通过get获取Structure或者Constraint中的属性或者临时变量

Structure {
    path: (s:Shop)<-[vP:visit]-(u:User)
}
Constraint {
    R("7天内消费"): vP.timestamp >= -7@d
    visitsNum("浏览次数") = rule_value(path, group(s).count(u),0)
    R2("热点商铺"): visitsNum > 1000
}
Action {
    // 获取shop和user点的id，并且返回Constraint中的visitsNum变量
    get(s.id, u.id, visitsNum)
}
```
![image](https://github.com/OpenSPG/openspg/assets/108744191/8f413e64-cc59-4427-830f-94a23ef2d27f)

**Comment by andylau-55** [comment]
请提供下完整的执行命令以及执行环境

**Comment by AnYingLieShouTuT** [comment]
用的是openspg-server:0.0.3-beta1、docker环境openspg-python:0.0.3-beta1执行的命令：knext schema reg_concept_rule --file ./schema/concept.rule，报错：
```
ERROR: dsl has syntax error: line: 15, column: 16, input:
                get(temp)
                ^ error here
mismatched input 'get' expecting {'}', 'createEdgeInstance', 'createNodeInstance', HexLetter, UnescapedSymbolicName, EscapedSymbolicName}
```

concept.rule
```
            Constraint {
                temp = "test"
            }
            Action {
                get(temp)
            }
```

**Comment by andylau-55** [comment]
> 用的是openspg-server:0.0.3-beta1、docker环境openspg-python:0.0.3-beta1执行的命令：knext schema reg_concept_rule --file ./schema/concept.rule，报错：
> 
> ```
> ERROR: dsl has syntax error: line: 15, column: 16, input:
>                 get(temp)
>                 ^ error here
> mismatched input 'get' expecting {'}', 'createEdgeInstance', 'createNodeInstance', HexLetter, UnescapedSymbolicName, EscapedSymbolicName}
> ```
> 
> concept.rule
> 
> ```
>             Constraint {
>                 temp = "test"
>             }
>             Action {
>                 get(temp)
>             }
> ```

请使用最新版本进行尝试，latest或者0.0.3-beta2
