### ISSUE TITLE
按教程安装后，参考案例教程，执行相应的knext命令时报错

### ISSUE THREAD

**Issue by WestBBQ** [OpenSPG/openspg#267]
- 启动容器，将其中的${project_dir}替换成源码目录
docker run --rm --net=host -v ${project_dir}:/code \
  -it openspg/openspg-python:latest \
  "/bin/bash"
  
- 容器启动后，进入/code目录，即openspg项目源码目录
cd /code

- 后续可以安装案例教程，比如进入riskmining目录
cd python/knext/knext/examples/riskmining

- 参考案例教程，执行相应的knext命令，比如
knext project create --prj_path .

(openspg_venv) root@docker-desktop:/code/python/knext/knext/examples/riskmining# knext config set --global host_addr=http://127.0.0.1:8887
(openspg_venv) root@docker-desktop:/code/python/knext/knext/examples/riskmining# knext project create --prj_path .
报错
ERROR: HTTPConnectionPool(host='127.0.0.1', port=8887): Max retries exceeded with url: /public/v1/project (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f26546d25e0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by andylau-55** [comment]
本地服务openspg-server 是通过源码启动的还是通过docker启动的？

**Comment by WestBBQ** [comment]
> 本地服务openspg-server 是通过源码启动的还是通过docker启动的？

docker run --rm --net=host -v /Users/openspg:/code \

**Comment by andylau-55** [comment]
根据报错提示为 找不到对应的openspg-server服务，这种情况一般发生在docker容器和宿主机的网络隔离问题。可在openspg-python环境中先测试curl http://127.0.0.1:8887/ 是否联通。如果是docker容器 访问 宿主机的本地网络一般可设置knext config set --global host_addr=http://host.docker.internal:8887   即可解决。也可根据本地部署的环境情况进行其他的设置，只有确保openspg-python容器能访问到openspg-server服务即可。
