### ISSUE TITLE
链指算子疑惑

### ISSUE THREAD

**Issue by YYGe01** [OpenSPG/openspg#268]
你好，https://github.com/OpenSPG/openspg/blob/master/python/knext/knext/examples/supplychain/builder/operator/company_operator.py

这里有点看不懂.

1、这个算子的作用是啥，在哪个阶段发挥作用，怎么触发的，看用户手册和Person的legalRep字段有关系，能举个例子嘛

2、property 是啥，传入什么东西，为啥company_name = property，Company实体有很多属性，为啥property传入的是公司名字

3、record: SPGRecord 又是啥，后面也没用上

```python
class CompanyLinkerOperator(LinkOp):
    bind_to = "SupplyChain.Company"

    def __init__(self):
        super().__init__()
        self.search_client = SearchClient("SupplyChain.Company")
        self.enable_llm = False

    def invoke(self, property: str, record: SPGRecord) -> List[SPGRecord]:
        company_name = property
        query = {"match": {"name": company_name}}
        recalls = self.search_client.search(query, start=0, size=30)

        if not recalls:
            return []

        if recalls[0].score < 0.6:
            # Low similarity, discard recall results
            return []

        if company_name == recalls[0].properties["name"]:
            # If the result of Top1 is the same as the attribute value, then returned directly
            return [
                SPGRecord(spg_type_name="SupplyChain.Company").upsert_properties(
                    {"id": recalls[0].doc_id}
                )
            ]

            # Perform fine-ranking on coarse recall results by calling LLM
        if not self.enable_llm:
            return [
                SPGRecord(spg_type_name="SupplyChain.Company").upsert_properties(
                    {"id": recalls[0].doc_id}
                )
            ]
        recall_dict = {}
        for item in recalls:
            recall_dict[item.properties["name"]] = item.doc_id
        recall_str = ",".join(recall_dict.keys())

        # ----- Please enable the code below when LLM service is ready ------
        llm_result = llm_infer(company_name, recall_str)
        if len(llm_result) > 0 and llm_result != "null":
            return [
                SPGRecord(spg_type_name="SupplyChain.Company").upsert_properties(
                    {"id": recall_dict[llm_result]}
                ),
            ]
        return []
```

**Comment by YYGe01** [comment]
还有es是怎么搜索的，我只知道elasticsearch存储的是图谱数据，但是是怎么存储的，存储了哪些字段呢
有相关的介绍文档嘛。
```
recalls = self.search_client.search(query, start=0, size=30)
```

**Comment by andylau-55** [comment]
1、CompanyLinkerOperator定义了bind_to字段为"SupplyChain.Company" 进行了实体和算子的绑定。Person的legalRepresentative属性为实体类型Company。当执行 knext builder execute Person的mapping阶段对legalRepresentative属性进行值映射时就会进行自动触发该算子
2、这里的property是入参，即为add_property_mapping时的csv文件中的legalRep字段(数据为公司名称)
3、SPGRecord只是数据传输协议，保存mapping节点产出的图信息用于在sink进行图数据存储

> 你好，https://github.com/OpenSPG/openspg/blob/master/python/knext/knext/examples/supplychain/builder/operator/company_operator.py
> 
> 这里有点看不懂.
> 
> 1、这个算子的作用是啥，在哪个阶段发挥作用，怎么触发的，看用户手册和Person的legalRep字段有关系，能举个例子嘛
> 
> 2、property 是啥，传入什么东西，为啥company_name = property，Company实体有很多属性，为啥property传入的是公司名字
> 
> 3、record: SPGRecord 又是啥，后面也没用上
> 
> ```python
> class CompanyLinkerOperator(LinkOp):
>     bind_to = "SupplyChain.Company"
> 
>     def __init__(self):
>         super().__init__()
>         self.search_client = SearchClient("SupplyChain.Company")
>         self.enable_llm = False
> 
>     def invoke(self, property: str, record: SPGRecord) -> List[SPGRecord]:
>         company_name = property
>         query = {"match": {"name": company_name}}
>         recalls = self.search_client.search(query, start=0, size=30)
> 
>         if not recalls:
>             return []
> 
>         if recalls[0].score < 0.6:
>             # Low similarity, discard recall results
>             return []
> 
>         if company_name == recalls[0].properties["name"]:
>             # If the result of Top1 is the same as the attribute value, then returned directly
>             return [
>                 SPGRecord(spg_type_name="SupplyChain.Company").upsert_properties(
>                     {"id": recalls[0].doc_id}
>                 )
>             ]
> 
>             # Perform fine-ranking on coarse recall results by calling LLM
>         if not self.enable_llm:
>             return [
>                 SPGRecord(spg_type_name="SupplyChain.Company").upsert_properties(
>                     {"id": recalls[0].doc_id}
>                 )
>             ]
>         recall_dict = {}
>         for item in recalls:
>             recall_dict[item.properties["name"]] = item.doc_id
>         recall_str = ",".join(recall_dict.keys())
> 
>         # ----- Please enable the code below when LLM service is ready ------
>         llm_result = llm_infer(company_name, recall_str)
>         if len(llm_result) > 0 and llm_result != "null":
>             return [
>                 SPGRecord(spg_type_name="SupplyChain.Company").upsert_properties(
>                     {"id": recall_dict[llm_result]}
>                 ),
>             ]
>         return []
> ```

1、CompanyLinkerOperator定义了bind_to字段为"SupplyChain.Company" 进行了实体和算子的绑定。Person的legalRepresentative属性为实体类型Company。当执行 knext builder execute Person的mapping阶段对legalRepresentative属性进行值映射时就会进行自动触发该算子
2、这里的property是入参，即为add_property_mapping时的csv文件中的legalRep字段(数据为公司名称)
3、SPGRecord只是数据传输协议，保存mapping节点产出的图信息用于在sink进行图数据存储

**Comment by andylau-55** [comment]
> 还有es是怎么搜索的，我只知道elasticsearch存储的是图谱数据，但是是怎么存储的，存储了哪些字段呢 有相关的介绍文档嘛。
> 
> ```
> recalls = self.search_client.search(query, start=0, size=30)
> ```

es中存储了点及对应的属性信息。这里主要用于点的召回，通过公司名获取到对应的id用于链指算子中

**Comment by YYGe01** [comment]
@andylau-55 感谢，再问下，这个builder里写的代码，像您说的knext builder execute Person执行时，会触发，我如果想用pycharm或vscode单步调试，有可能实现嘛。

**Comment by andylau-55** [comment]
> @andylau-55 感谢，再问下，这个builder里写的代码，像您说的knext builder execute Person执行时，会触发，我如果想用pycharm或vscode单步调试，有可能实现嘛。

标准的python代码。根据本地环境debug启动调用到本地代码即可
