### ISSUE TITLE
SPG前台画布信息有误

### ISSUE THREAD

**Issue by billc114** [OpenSPG/openspg#269]
schema：
```
Repository(Repository): EntityType
	properties:
		vid(vid): Text
		dependency(dependency): Repository
		    constraint: MultiValue
```
导入数据：
```
id,dependency
A,""
B,""
C,"A,B"
```
查询出结果：
![image](https://github.com/OpenSPG/openspg/assets/52943316/efb0dc10-224d-4410-853e-aec1c02452bd)

数据显示应该有两条边C->A; C->B，但是画布里仅显示一条边：

![image](https://github.com/OpenSPG/openspg/assets/52943316/6a758173-10bc-4a7c-9b17-df482a6a6b8d)

**Comment by YYGe01** [comment]
这个画布我用起来也一脸懵，展示信息过多。如果查看精确的return结果，建议用命令行执行
```
knext reasoner execute --file ./reasoner/dsl_task.dsl
```

**Comment by andylau-55** [comment]
> schema：
> 
> ```
> Repository(Repository): EntityType
> 	properties:
> 		vid(vid): Text
> 		dependency(dependency): Repository
> 		    constraint: MultiValue
> ```
> 
> 导入数据：
> 
> ```
> id,dependency
> A,""
> B,""
> C,"A,B"
> ```
> 
> 查询出结果： ![image](https://private-user-images.githubusercontent.com/52943316/334792036-efb0dc10-224d-4410-853e-aec1c02452bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMjI3NjQsIm5iZiI6MTcxNzEyMjQ2NCwicGF0aCI6Ii81Mjk0MzMxNi8zMzQ3OTIwMzYtZWZiMGRjMTAtMjI0ZC00NDEwLTg1M2UtYWVjMWMwMjQ1MmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDAyMjc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMWEyOTVmYWZmZGJiMDcyNDYzYTZkZjZlYjJiMzAxMzZiMzFlNThhZWU0YTljNDRmMmRkMmFhY2ZhMDE1OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bZRhZA1hYwtKSY05TjPAMPHS3MhcUw9Pj4gWRWd0k_c)
> 
> 数据显示应该有两条边C->A; C->B，但是画布里仅显示一条边：
> 
> ![image](https://private-user-images.githubusercontent.com/52943316/334791975-6a758173-10bc-4a7c-9b17-df482a6a6b8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMjI3NjQsIm5iZiI6MTcxNzEyMjQ2NCwicGF0aCI6Ii81Mjk0MzMxNi8zMzQ3OTE5NzUtNmE3NTgxNzMtMTBiYy00YTdjLTliMTctZGY0ODJhNmE2YjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDAyMjc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYmJmMWM0ZjE3MWQ3YTc5OGQ1MDNmNTcxMmRkYWU2MWI4OWJhNzdhYjNiZDk1ZjY0MDA1YzhiN2MyN2Y0NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DDWuP-Z9tEw6EBM1dFAm2SMGaJ-t3APq8hrI9K9rwyI)

可通过knext reasoner execute 执行对应dsl语句以便查看是查询问题还是页面展示问题。

**Comment by billc114** [comment]
执行
```
knext reasoner execute --dsl "
MATCH (s:PairCI.Repository)-[e:dependency]->(r:PairCI.Repository)
WHERE s.id='C'
RETURN s.id,r.name"
```
得到结果：
```
(0) [C, B]
(1) [C, A]
```
物理执行计划为：
```
└─Select(orderedFields=List(PropertyVar(s,id::KTString::true), PropertyVar(r,name::KTString::true)), as=List(s.id, r.name), distinct=false)
    └─Drop(fields=Set(EdgeVar(e,Set(__to_id__::KTString::true, __from_id__::KTString::true, __to_id_type__::KTString::true, __from_id_type__::KTString::true))))
        └─ExpandInto(target=(r:PairCI.Repository), pattern=NodePattern((r:PairCI.Repository)), meta=List(EdgeVar(e,Set(__to_id__::KTString::true, __from_id__::KTString::true, __to_id_type__::KTString::true, __from_id_type__::KTString::true)), NodeVar(s,Set(id::KTString::true)), NodeVar(r,Set(name::KTString::true))))
            └─PatternScan(pattern=PartialGraphPattern(s,Map(s -> (s:PairCI.Repository,BinaryOpExpr(name=BEqual)), r -> (r:PairCI.Repository)),Map(s -> Set((s)->[e:dependency]-(r))))), meta=List(EdgeVar(e,Set(__to_id__::KTString::true, __from_id__::KTString::true, __to_id_type__::KTString::true, __from_id_type__::KTString::true)), NodeVar(s,Set(id::KTString::true)), NodeVar(r,Set())))
                └─Start(graphName=KG, alias=s, meta=List(EdgeVar(e,Set(__to_id__::KTString::true, __from_id__::KTString::true, __to_id_type__::KTString::true, __from_id_type__::KTString::true)), NodeVar(s,Set(id::KTString::true)), NodeVar(r,Set(name::KTString::true))), types=Set(PairCI.Repository))

```


> > schema：
> > ```
> > Repository(Repository): EntityType
> > 	properties:
> > 		vid(vid): Text
> > 		dependency(dependency): Repository
> > 		    constraint: MultiValue
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 导入数据：
> > ```
> > id,dependency
> > A,""
> > B,""
> > C,"A,B"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 查询出结果： ![image](https://private-user-images.githubusercontent.com/52943316/334792036-efb0dc10-224d-4410-853e-aec1c02452bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMjI3NjQsIm5iZiI6MTcxNzEyMjQ2NCwicGF0aCI6Ii81Mjk0MzMxNi8zMzQ3OTIwMzYtZWZiMGRjMTAtMjI0ZC00NDEwLTg1M2UtYWVjMWMwMjQ1MmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDAyMjc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMWEyOTVmYWZmZGJiMDcyNDYzYTZkZjZlYjJiMzAxMzZiMzFlNThhZWU0YTljNDRmMmRkMmFhY2ZhMDE1OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bZRhZA1hYwtKSY05TjPAMPHS3MhcUw9Pj4gWRWd0k_c)
> > 数据显示应该有两条边C->A; C->B，但是画布里仅显示一条边：
> > ![image](https://private-user-images.githubusercontent.com/52943316/334791975-6a758173-10bc-4a7c-9b17-df482a6a6b8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMjI3NjQsIm5iZiI6MTcxNzEyMjQ2NCwicGF0aCI6Ii81Mjk0MzMxNi8zMzQ3OTE5NzUtNmE3NTgxNzMtMTBiYy00YTdjLTliMTctZGY0ODJhNmE2YjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDAyMjc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYmJmMWM0ZjE3MWQ3YTc5OGQ1MDNmNTcxMmRkYWU2MWI4OWJhNzdhYjNiZDk1ZjY0MDA1YzhiN2MyN2Y0NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DDWuP-Z9tEw6EBM1dFAm2SMGaJ-t3APq8hrI9K9rwyI)
> 
> 可通过knext reasoner execute 执行对应dsl语句以便查看是查询问题还是页面展示问题。
