### ISSUE TITLE
如何使用融合功能

### ISSUE THREAD

**Issue by yyssxxx** [OpenSPG/openspg#272]
<img width="431" alt="截屏2024-06-05 13 42 19" src="https://github.com/OpenSPG/openspg/assets/104908549/e49b7c15-11ea-45aa-ae4f-3069e53c8d82">
比如说这张图片，我schema提交后，导入数据build后得到一张图谱，然后我后来又在schema上多加了一个属性A和一个关系B，但是这个属性A和B是定义在了一张新的表格里，但这张表和原来的表都有相同的主键，那么我该如何修改Company.py，才能将这两个表格的属性通过主键合并在一起，得到新的图谱呢？而且可以不重写图谱，只是增加新属性和关系吗？

**Comment by andylau-55** [comment]
你可以重新配置一个构建任务，修改mapping 将数据映射到对应属性A和关系B 即可

**Comment by yyssxxx** [comment]
> 你可以重新配置一个构建任务，修改mapping 将数据映射到对应属性A和关系B 即可

但是这样是不是就是要把所有的数据重新导入一遍呢，有没有只是更新的方法？

**Comment by andylau-55** [comment]
> > 你可以重新配置一个构建任务，修改mapping 将数据映射到对应属性A和关系B 即可
> 
> 但是这样是不是就是要把所有的数据重新导入一遍呢，有没有只是更新的方法？



> > 你可以重新配置一个构建任务，修改mapping 将数据映射到对应属性A和关系B 即可
> 
> 但是这样是不是就是要把所有的数据重新导入一遍呢，有没有只是更新的方法？



> > 你可以重新配置一个构建任务，修改mapping 将数据映射到对应属性A和关系B 即可
> 
> 但是这样是不是就是要把所有的数据重新导入一遍呢，有没有只是更新的方法？

不需要，构建任务是属性粒度是append，不是overwrite。

**Comment by yyssxxx** [comment]
wo

> > > 你可以重新配置一个构建任务，修改mapping 将数据映射到对应属性A和关系B 即可
> > 
> > 
> > 但是这样是不是就是要把所有的数据重新导入一遍呢，有没有只是更新的方法？
> 
> > > 你可以重新配置一个构建任务，修改mapping 将数据映射到对应属性A和关系B 即可
> > 
> > 
> > 但是这样是不是就是要把所有的数据重新导入一遍呢，有没有只是更新的方法？
> 
> > > 你可以重新配置一个构建任务，修改mapping 将数据映射到对应属性A和关系B 即可
> > 
> > 
> > 但是这样是不是就是要把所有的数据重新导入一遍呢，有没有只是更新的方法？
> 
> 不需要，构建任务是属性粒度是append，不是overwrite。

我明白了，谢谢您
