### ISSUE TITLE
能实现同一个实体从两个表格读取数据并融合吗？

### ISSUE THREAD

**Issue by yyssxxx** [OpenSPG/openspg#277]
比如一开始我的Company实体只有属性A,B和关系C，数据在表格1。但是后来又多了属性D和关系E，而且这个数据在一个新的表格2里，我在schema更改后想build更新数据，把相同name（主键）的信息合并成一起，这样合并后信息就包含来自两个表格的信息ABCDE，该怎么做呢？

**Comment by andylau-55** [comment]
创建两个构建任务，第一个任务将数据映射到name、属性A,B和关系C；第二个任务将数据映射name、属性D和关系E即可
