### ISSUE TITLE
在医疗图谱刚搭建时，我该怎么询问，已连接api

### ISSUE THREAD

**Issue by bijinacm** [OpenSPG/openspg#285]
在分析推理中，例如我询问，MATCH (s:Medicine.Symptom {name: '症状'})
RETURN s，一直报错如下，
执行失败KGReasonerLocalRunner,error:line: 1, column: 26, input: MATCH (s:Medicine.Symptom {name: '症状'}) ^ error here com.antgroup.openspg.reasoner.common.exception.KGDSLInvalidTokenException: line: 1, column: 26, input: MATCH (s:Medicine.Symptom {name: '症状'}) ^ error here at com.antgroup.openspg.reasoner.parser.ErrorHandlerStrategy.reportNoViableAlternative(ErrorHandlerStrategy.scala:54) at com.antgroup.openspg.reasoner.parser.ErrorHandlerStrategy.reportError(ErrorHandlerStrategy.scala:33) at com.antgroup.openspg.reasoner.KGDSLParser.element_pattern(KGDSLParser.java:2342) at com.antgroup.openspg.reasoner.KGDSLParser.path_pattern_expression(KGDSLParser.java:2266) at com.antgroup.openspg.reasoner.KGDSLParser.path_pattern(KGDSLParser.java:2141) at com.antgroup.openspg.reasoner.KGDSLParser.path_pattern_list(KGDSLParser.java:2064) at com.antgroup.openspg.reasoner.KGDSLParser.graph_pattern(KGDSLParser.java:11554) at com.antgroup.openspg.reasoner.KGDSLParser.match_statement(KGDSLParser.java:11511) at com.antgroup.openspg.reasoner.KGDSLParser.gql_query_statement(KGDSLParser.java:11467) at com.antgroup.openspg.reasoner.KGDSLParser.base_job(KGDSLParser.java:666) at com.antgroup.openspg.reasoner.KGDSLParser.kg_dsl(KGDSLParser.java:607) at com.antgroup.openspg.reasoner.parser.OpenSPGDslParser.parseMultipleStatement(OpenSPGDslParser.scala:108) at com.antgroup.openspg.reasoner.session.KGReasonerSession.planToBlock(KGReasonerSession.scala:388) at com.antgroup.openspg.reasoner.session.KGReasonerSession.plan2UnresolvedLogicalPlan(KGReasonerSession.scala:372) at com.antgroup.openspg.reasoner.session.KGReasonerSession.plan(KGReasonerSession.scala:156) at com.antgroup.openspg.reasoner.runner.local.LocalReasonerRunner.doRun(LocalReasonerRunner.java:114) at com.antgroup.openspg.reasoner.runner.local.LocalReasonerRunner.run(LocalReasonerRunner.java:70) at com.antgroup.openspgapp.core.reasoner.service.impl.TaskRunner$ReasonerLocalTask.call(TaskRunner.java:107) at com.antgroup.openspgapp.core.reasoner.service.impl.TaskRunner$ReasonerLocalTask.call(TaskRunner.java:80) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:750)

**Comment by andylau-55** [comment]
您输入的DSL语句目前不支持，如果需要按照name做查询请使用WHERE条件，具体可参考文档：https://openspg.yuque.com/ndx6g9/nmwkzz/qam8a9m5x5g4syzr#EYNA2

**Comment by andylau-55** [comment]
MATCH (s:Medicine.Symptom)
WHERE s.name == '症状'
RETURN s

**Comment by bijinacm** [comment]
> MATCH (s:Medicine.Symptom) WHERE s.name == '症状' RETURN s

不是这个问题，还是有错误

**Comment by andylau-55** [comment]
> > MATCH (s:Medicine.Symptom) WHERE s.name == '症状' RETURN s
> 
> 不是这个问题，还是有错误

具体什么错误，我这边验证是能正确执行并返回结果的

**Comment by bijinacm** [comment]
> > > MATCH (s:Medicine.Symptom) WHERE s.name == '症状' RETURN s
> > 
> > 
> > 不是这个问题，还是有错误
> 
> 具体什么错误，我这边验证是能正确执行并返回结果的

现在错误是这个了，当我去医疗图谱的step4提交时，报错这个，
(openspg_venv) root@docker-desktop:/code/python/knext/knext/examples/medicine# knext builder execute Disease
2024-06-20 07:20:29,506 [] [] [main] INFO  c.a.o.c.i.g.GraphStoreClientDriverManager - registerDriver: com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver@8297b3a
2024-06-20 07:20:29,510 [] [] [main] INFO  c.a.o.c.u.DriverManagerUtils - DriverManager.initialize: cloudext.graphstore.drivers = null
2024-06-20 07:20:29,510 [] [] [main] INFO  c.a.o.c.i.g.GraphStoreClientDriverManager - graph-store DriverManager initialized
2024-06-20 07:20:30,004 [] [] [main] ERROR c.a.o.b.r.l.LocalBuilderMain - unknown exception.
java.lang.RuntimeException: init TuGraph Client failed
        at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.initTuGraphClient(TuGraphStoreClient.java:142)
        at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.<init>(TuGraphStoreClient.java:84)
        at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver.innerConnect(TuGraphStoreClientDriver.java:36)
        at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver.innerConnect(TuGraphStoreClientDriver.java:22)
        at com.antgroup.openspg.common.util.cloudext.CachedCloudExtClientDriver.connect(CachedCloudExtClientDriver.java:29)
        at com.antgroup.openspg.cloudext.interfaces.graphstore.GraphStoreClientDriverManager.getClient(GraphStoreClientDriverManager.java:49)
        at com.antgroup.openspg.builder.runner.local.physical.sink.impl.GraphStoreSinkWriter.doInit(GraphStoreSinkWriter.java:59)
        at com.antgroup.openspg.builder.core.physical.BasePhysicalNode.init(BasePhysicalNode.java:71)
        at com.antgroup.openspg.builder.runner.local.LocalBuilderRunner.init(LocalBuilderRunner.java:76)
        at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.run(LocalBuilderMain.java:147)
        at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.main(LocalBuilderMain.java:69)
Caused by: com.antgroup.tugraph.TuGraphDbRpcException: No such graph: default
        at com.antgroup.tugraph.TuGraphDbRpcClient$TuGraphSingleRpcClient.listProcedures(TuGraphDbRpcClient.java:698)
        at com.antgroup.tugraph.TuGraphDbRpcClient.listProcedures(TuGraphDbRpcClient.java:190)
        at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.loadCppPlugin(TuGraphStoreClient.java:157)
        at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.initTuGraphClient(TuGraphStoreClient.java:140)
        ... 10 common frames omitted

**Comment by andylau-55** [comment]
> > > > MATCH (s:Medicine.Symptom) WHERE s.name == '症状' RETURN s
> > > 
> > > 
> > > 不是这个问题，还是有错误
> > 
> > 
> > 具体什么错误，我这边验证是能正确执行并返回结果的
> 
> 现在错误是这个了，当我去医疗图谱的step4提交时，报错这个， (openspg_venv) root@docker-desktop:/code/python/knext/knext/examples/medicine# knext builder execute Disease 2024-06-20 07:20:29,506 [] [] [main] INFO c.a.o.c.i.g.GraphStoreClientDriverManager - registerDriver: com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver@8297b3a 2024-06-20 07:20:29,510 [] [] [main] INFO c.a.o.c.u.DriverManagerUtils - DriverManager.initialize: cloudext.graphstore.drivers = null 2024-06-20 07:20:29,510 [] [] [main] INFO c.a.o.c.i.g.GraphStoreClientDriverManager - graph-store DriverManager initialized 2024-06-20 07:20:30,004 [] [] [main] ERROR c.a.o.b.r.l.LocalBuilderMain - unknown exception. java.lang.RuntimeException: init TuGraph Client failed at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.initTuGraphClient(TuGraphStoreClient.java:142) at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.(TuGraphStoreClient.java:84) at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver.innerConnect(TuGraphStoreClientDriver.java:36) at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver.innerConnect(TuGraphStoreClientDriver.java:22) at com.antgroup.openspg.common.util.cloudext.CachedCloudExtClientDriver.connect(CachedCloudExtClientDriver.java:29) at com.antgroup.openspg.cloudext.interfaces.graphstore.GraphStoreClientDriverManager.getClient(GraphStoreClientDriverManager.java:49) at com.antgroup.openspg.builder.runner.local.physical.sink.impl.GraphStoreSinkWriter.doInit(GraphStoreSinkWriter.java:59) at com.antgroup.openspg.builder.core.physical.BasePhysicalNode.init(BasePhysicalNode.java:71) at com.antgroup.openspg.builder.runner.local.LocalBuilderRunner.init(LocalBuilderRunner.java:76) at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.run(LocalBuilderMain.java:147) at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.main(LocalBuilderMain.java:69) Caused by: com.antgroup.tugraph.TuGraphDbRpcException: No such graph: default at com.antgroup.tugraph.TuGraphDbRpcClient$TuGraphSingleRpcClient.listProcedures(TuGraphDbRpcClient.java:698) at com.antgroup.tugraph.TuGraphDbRpcClient.listProcedures(TuGraphDbRpcClient.java:190) at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.loadCppPlugin(TuGraphStoreClient.java:157) at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.initTuGraphClient(TuGraphStoreClient.java:140) ... 10 common frames omitted

该错误是表示tugraph链接失败，请检查本地是否对tugraph镜像做了参数的调整 导致链接不上

**Comment by bijinacm** [comment]
> > > > > MATCH (s:Medicine.Symptom) WHERE s.name == '症状' RETURN s
> > > > 
> > > > 
> > > > 不是这个问题，还是有错误
> > > 
> > > 
> > > 具体什么错误，我这边验证是能正确执行并返回结果的
> > 
> > 
> > 现在错误是这个了，当我去医疗图谱的step4提交时，报错这个， (openspg_venv) root@docker-desktop:/code/python/knext/knext/examples/medicine# knext builder execute Disease 2024-06-20 07:20:29,506 [] [] [main] INFO c.a.o.c.i.g.GraphStoreClientDriverManager - registerDriver: com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver@8297b3a 2024-06-20 07:20:29,510 [] [] [main] INFO c.a.o.c.u.DriverManagerUtils - DriverManager.initialize: cloudext.graphstore.drivers = null 2024-06-20 07:20:29,510 [] [] [main] INFO c.a.o.c.i.g.GraphStoreClientDriverManager - graph-store DriverManager initialized 2024-06-20 07:20:30,004 [] [] [main] ERROR c.a.o.b.r.l.LocalBuilderMain - unknown exception. java.lang.RuntimeException: init TuGraph Client failed at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.initTuGraphClient(TuGraphStoreClient.java:142) at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.(TuGraphStoreClient.java:84) at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver.innerConnect(TuGraphStoreClientDriver.java:36) at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver.innerConnect(TuGraphStoreClientDriver.java:22) at com.antgroup.openspg.common.util.cloudext.CachedCloudExtClientDriver.connect(CachedCloudExtClientDriver.java:29) at com.antgroup.openspg.cloudext.interfaces.graphstore.GraphStoreClientDriverManager.getClient(GraphStoreClientDriverManager.java:49) at com.antgroup.openspg.builder.runner.local.physical.sink.impl.GraphStoreSinkWriter.doInit(GraphStoreSinkWriter.java:59) at com.antgroup.openspg.builder.core.physical.BasePhysicalNode.init(BasePhysicalNode.java:71) at com.antgroup.openspg.builder.runner.local.LocalBuilderRunner.init(LocalBuilderRunner.java:76) at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.run(LocalBuilderMain.java:147) at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.main(LocalBuilderMain.java:69) Caused by: com.antgroup.tugraph.TuGraphDbRpcException: No such graph: default at com.antgroup.tugraph.TuGraphDbRpcClient$TuGraphSingleRpcClient.listProcedures(TuGraphDbRpcClient.java:698) at com.antgroup.tugraph.TuGraphDbRpcClient.listProcedures(TuGraphDbRpcClient.java:190) at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.loadCppPlugin(TuGraphStoreClient.java:157) at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.initTuGraphClient(TuGraphStoreClient.java:140) ... 10 common frames omitted
> 
> 该错误是表示tugraph链接失败，请检查本地是否对tugraph镜像做了参数的调整 导致链接不上

在http://localhost:7070中是可以成功打开的

**Comment by andylau-55** [comment]
你这边是在什么环境下执行knext命令的呢？本地还是openspg/openspg-python镜像中？
