### ISSUE TITLE
schema设计的问题

### ISSUE THREAD

**Issue by LLL1st** [OpenSPG/openspg#289]
在医疗图谱的schema中，HospitalDepartment是一个ConceptType，之后它作为Disease的一个属性department(就诊科室): HospitalDepartment。我有个问题就是在这里HospitalDepartment是ConceptTypem还是EntityType好像没有区别

**Comment by bijinacm** [comment]
佬，能给说下怎么配置成功医疗图谱的么，官方给的教程太简略了，出了很多问题，在TuGraph方面没有任何连接介绍，很麻烦，谢谢你。

**Comment by matthewhyx** [comment]
> 在医疗图谱的schema中，HospitalDepartment是一个ConceptType，之后它作为Disease的一个属性department(就诊科室): HospitalDepartment。我有个问题就是在这里HospitalDepartment是ConceptTypem还是EntityType好像没有区别

您好，可以参考这个问题的回答：https://github.com/OpenSPG/openspg/issues/265

**Comment by matthewhyx** [comment]
> 佬，能给说下怎么配置成功医疗图谱的么，官方给的教程太简略了，出了很多问题，在TuGraph方面没有任何连接介绍，很麻烦，谢谢你。

您好，建议您新开一个issue列举下您在配置过程中遇到的具体问题，比如按照官方的文档，在哪一步出了问题，具体的报错是什么，这样方便我们为您答疑。
