### ISSUE TITLE
SubGraphMapping在哪里？

### ISSUE THREAD

**Issue by LLL1st** [OpenSPG/openspg#290]
https://openspg.yuque.com/ndx6g9/nmwkzz/kes06f94f72xgut9#ZLiZH这个文档中出现了SubGraphMapping，但我并未找到源码中哪里有SubGraphMapping。其次在源码的disease.p文件中Disease抽取是这样写的：extract = LLMBasedExtractor(
            llm=NNInvoker.from_config("builder/model/openai_infer.json"),
            prompt_ops=[
                REPrompt(
                    spg_type_name=Medicine.Disease,
                    property_names=[
                        Medicine.Disease.complication,
                        Medicine.Disease.commonSymptom,
                        Medicine.Disease.applicableDrug,
                        Medicine.Disease.department,
                        Medicine.Disease.diseaseSite,
                    ],
                    relation_names=[(Medicine.Disease.abnormal, Medicine.Indicator)],
                )
            ],
        )；但是文档中的示例是这样的："""
        2. 定义大模型抽取组件，从长文本中抽取Medical.Disease类型实体
        """
        extract = LLMBasedExtractor(
            llm=LLMInvoker.from_config("builder/model/openai_infer.json"),
            prompt_ops=[
                REPrompt(
                    spg_type_name="Medical.Disease",
                    property_names=[
                        "complication",
                        "commonSymptom",
                        "applicableDrug",
                        "department",
                        "diseaseSite",
                    ],
                )
            ],
        )
。请问 property_names中应该是什么呢？

**Comment by andylau-55** [comment]
SubGraphMapping已改名为SPGTypeMapping。property_names为对应实体的属性信息

**Comment by andylau-55** [comment]
> Reference in new issue

需要填写完整信息既Medicine.Disease.complication。具体可参考openspg/python/knext/knext/examples 目录下的示例代码
