### ISSUE TITLE
knext reasoner execute --dsl " MATCH (s:Medicine.Disease)-[p]->(o) RETURN s "这个语句在命令行可以运行，但是在分析推理里无法运行

### ISSUE THREAD

**Issue by bijinacm** [OpenSPG/openspg#292]
这个怎么解决呢？不知道哪里的问题？
![cc](https://github.com/OpenSPG/openspg/assets/109888410/febe3b85-c060-42ad-bad4-e3970b65d357)

**Comment by andylau-55** [comment]
分析推理页面直接执行dsl语句即可，knex是通过命令执行dsl语句
