### ISSUE TITLE
finance示例的一些问题

### ISSUE THREAD

**Issue by LLL1st** [OpenSPG/openspg#293]
您好，
python/knext/knext/examples/finance/builder/job/indicator.py
这个文件中的 add_property_mapping("id", Finance.Indicator.id)
和
python/knext/knext/examples/finance/builder/operator/indicator_link.py
这个文件中的IndicatorLinkOp
有关系吗？

因为我看关于 SPGTypeMapping 的文档中写到“若object类型上绑定或设置了LinkOp，则执行基于属性值生成object的链指流程。” 在我的理解中 indicator 是subject类型，indicator.id 是object类型，而 IndicatorLinkOp 中是bind_to = Finance.Indicator，不知道 add_property_mapping("id", Finance.Indicator.id) 和 IndicatorLinkOp 分别是什么作用呢？

**Comment by LLL1st** [comment]
还是关于finance示例的问题，请问
python/knext/knext/examples/finance/builder/operator/indicator_link.py
中的IndicatorLinkOp中用到了IndicatorLinkPrompt。
我知道IndicatorLinkOp是在构建任务中自动调用的，但是IndicatorLinkOp类中的这行代码 self.prompt_op = IndicatorLinkPrompt() 之后并没有使用到 IndicatorLinkPrompt() 中的方法

**Comment by andylau-55** [comment]
bulid构建过程中会对bind_to配置进行自动拉边。bind_to的逻辑解释可参考：https://github.com/OpenSPG/openspg/issues/268

**Comment by LLL1st** [comment]
`class IndicatorLinkOp(LinkOp):
    bind_to = Finance.Indicator

    def __init__(self):
        super().__init__()
        from builder.operator.prompts import IndicatorLinkPrompt

        self.prompt_op = IndicatorLinkPrompt()
        self.search_client = SearchClient(self.bind_to)

    def invoke(self, property: str, subject_record: SPGRecord) -> List[SPGRecord]:
        # Retrieve relevant indicators from KG based on indicator name
        name = property
        recall_records = self.search_client.fuzzy_search_by_property(
            property, "name", size=3
        )
        if len(recall_records) == 0:
            print("no indicators recalled")
            tmp = SPGRecord("Finance.Indicator")
            tmp.upsert_property("id", property)
            tmp.upsert_property("name", name)
            return [tmp]
        print(f"recalled indicators: {recall_records}")
        return recall_records
`
您好，我说的是这段代码中的 self.prompt_op = IndicatorLinkPrompt()，这个只需要这行代码就表示和大模型进行交互了吗？交互后的结果不需要处理吗？

**Comment by andylau-55** [comment]
> `class IndicatorLinkOp(LinkOp): bind_to = Finance.Indicator
> 
> ```
> def __init__(self):
>     super().__init__()
>     from builder.operator.prompts import IndicatorLinkPrompt
> 
>     self.prompt_op = IndicatorLinkPrompt()
>     self.search_client = SearchClient(self.bind_to)
> 
> def invoke(self, property: str, subject_record: SPGRecord) -> List[SPGRecord]:
>     # Retrieve relevant indicators from KG based on indicator name
>     name = property
>     recall_records = self.search_client.fuzzy_search_by_property(
>         property, "name", size=3
>     )
>     if len(recall_records) == 0:
>         print("no indicators recalled")
>         tmp = SPGRecord("Finance.Indicator")
>         tmp.upsert_property("id", property)
>         tmp.upsert_property("name", name)
>         return [tmp]
>     print(f"recalled indicators: {recall_records}")
>     return recall_records
> ```
> 
> ` 您好，我说的是这段代码中的 self.prompt_op = IndicatorLinkPrompt()，这个只需要这行代码就表示和大模型进行交互了吗？交互后的结果不需要处理吗？

该链指算子代码没有调用大模型相关能力，主要是通过索引召回进行链指的

**Comment by LLL1st** [comment]
您好，那
`from builder.operator.prompts import IndicatorLinkPrompt

    self.prompt_op = IndicatorLinkPrompt()`
这个是在做什么呢
