### ISSUE TITLE
为什么黑产挖掘里面的这个命令会出错，能帮忙看下么？

### ISSUE THREAD

**Issue by bijinacm** [OpenSPG/openspg#294]
在分析推理中我这样问的，
Define (s:App)-[p:belongTo]->(o:`TaxOfRiskApp`/`赌博应用`) {
    Structure {
        (s)
    }
    Constraint {
        R1("风险标记为赌博") s.riskMark like "%赌博%"
    }
}
这个来自
![1](https://github.com/OpenSPG/openspg/assets/109888410/5f5437ed-db21-4c4a-a6db-83873b1feae0)
报错：
执行失败KGReasonerLocalRunner,error:line: 6, column: 22, input: R1("风险标记为赌博") s.riskMark like "%赌博%" ^ error here com.antgroup.openspg.reasoner.common.exception.KGDSLInvalidTokenException: line: 6, column: 22, input: R1("风险标记为赌博") s.riskMark like "%赌博%" ^ error here at com.antgroup.openspg.reasoner.parser.ErrorHandlerStrategy.reportNoViableAlternative(ErrorHandlerStrategy.scala:54) at com.antgroup.openspg.reasoner.parser.ErrorHandlerStrategy.reportError(ErrorHandlerStrategy.scala:33) at com.antgroup.openspg.reasoner.KGDSLParser.rule_expression(KGDSLParser.java:4072) at com.antgroup.openspg.reasoner.KGDSLParser.rule_expression_body(KGDSLParser.java:4006) at com.antgroup.openspg.reasoner.KGDSLParser.the_rule(KGDSLParser.java:3908) at com.antgroup.openspg.reasoner.KGDSLParser.base_rule_define(KGDSLParser.java:431) at com.antgroup.openspg.reasoner.KGDSLParser.the_define_structure(KGDSLParser.java:758) at com.antgroup.openspg.reasoner.KGDSLParser.base_predicated_define(KGDSLParser.java:483) at com.antgroup.openspg.reasoner.KGDSLParser.kg_dsl(KGDSLParser.java:594) at com.antgroup.openspg.reasoner.parser.OpenSPGDslParser.parseMultipleStatement(OpenSPGDslParser.scala:108) at com.antgroup.openspg.reasoner.session.KGReasonerSession.planToBlock(KGReasonerSession.scala:388) at com.antgroup.openspg.reasoner.session.KGReasonerSession.plan2UnresolvedLogicalPlan(KGReasonerSession.scala:372) at com.antgroup.openspg.reasoner.session.KGReasonerSession.plan(KGReasonerSession.scala:156) at com.antgroup.openspg.reasoner.runner.local.LocalReasonerRunner.doRun(LocalReasonerRunner.java:114) at com.antgroup.openspg.reasoner.runner.local.LocalReasonerRunner.run(LocalReasonerRunner.java:70) at com.antgroup.openspgapp.core.reasoner.service.impl.TaskRunner$ReasonerLocalTask.call(TaskRunner.java:107) at com.antgroup.openspgapp.core.reasoner.service.impl.TaskRunner$ReasonerLocalTask.call(TaskRunner.java:80) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:750)

**Comment by andylau-55** [comment]
你好，类型输入全称进行尝试下，比如RiskMining.App RiskMining.TaxOfRiskApp
