### ISSUE TITLE
医疗图谱中我通过提交新的症状描述，已经生成了新的节点，但是并没有跟我所描述的科室连一条边

### ISSUE THREAD

**Issue by bijinacm** [OpenSPG/openspg#298]
这个该怎么解决呢？
例如我提交的是：
肺癌是一种在肺部发生的恶性肿瘤，是全球范围内最常见的恶性肿瘤之一。肺癌的发病率和死亡率都很高，对人类健康构成严重威胁。肺癌的主要病因是长期吸烟，而被动吸烟、空气污染、职业暴露、遗传因素等也是重要的致病因素。肺癌的临床表现多种多样，早期肺癌往往没有明显症状，随着病情的发展，可能出现咳嗽、咳痰、咳血、胸痛、气促等症状，也可能出现全身症状如消瘦、乏力、发热等。肺癌的诊断主要依靠影像学检查和病理学检查，包括胸部X线片、胸部CT、磁共振成像、纵膈镜、支气管镜、经皮肺穿刺活检等。肺癌的治疗主要取决于肺癌的类型和分期，手术、放疗、化疗、靶向治疗、免疫治疗等都是常见的治疗手段。早期肺癌的治疗效果较好，晚期肺癌的治疗效果较差，预后不佳。因此，对于高危人群，建议进行定期的肺癌筛查，以便早期发现、早期治疗。对于肺癌的诊断和治疗，通常需要到呼吸内科或者肿瘤科进行就诊。
然后生成的图是这样的，没有连边
![77](https://github.com/OpenSPG/openspg/assets/109888410/6004d9ce-cee8-4e5d-873a-e12801ef39cf)

**Comment by bijinacm** [comment]
> 请具体描述下你的导入流程和配置信息。如果需要导入边关系，需要配置好相关信息进行导入

这个该在哪个文件中进行添加边关系呢，我这段话是在Disease.csv文件中保存然后执行的，之后生成结点没有边

**Comment by andylau-55** [comment]
请检查数据的抽取结果，模型是否对文本的内容进行了正确抽取。比如肺癌实体抽取出的 '就诊科室' 属性是否有对应的终点实体。是否抽取出了 abnormal(异常指征) 边关系。正常抽取后才会进行点和边的写入

**Comment by bijinacm** [comment]
> 请检查数据的抽取结果，模型是否对文本的内容进行了正确抽取。比如肺癌实体抽取出的 '就诊科室' 属性是否有对应的终点实体。是否抽取出了 abnormal(异常指征) 边关系。正常抽取后才会进行点和边的写入

你好，例如我的这个数据，胃癌依然没有和胃肠外科连线，结点都有了，但是没有成功连边，能帮我尝试修改下么？我已经对着样例改了，但是没有成功连边，以下是我的Disease.csv文件中的胃癌内容：
胃癌是一种发生在胃部的恶性肿瘤，是全球最常见的恶性肿瘤之一，其发病率和死亡率都极高，对人类健康构成了严重威胁。长期的不良饮食习惯，如过度食用烟熏、腌制、油炸食品等是胃癌的主要病因，同时幽门螺杆菌感染、胃炎、胃溃疡、胃息肉等也都是引发胃癌的重要因素。胃癌的临床表现多种多样，早期胃癌往往没有明显症状，随着病情的发展，可能出现上腹部疼痛、消化不良、食欲减退、体重下降等症状。胃癌的诊断主要依靠胃镜检查和病理学检查。胃癌的治疗主要取决于胃癌的类型和分期，手术、放疗、化疗、靶向治疗、免疫治疗等都是常见的治疗手段。早期胃癌的治疗效果较好，晚期胃癌的治疗效果较差，预后不佳。因此，对于高危人群，建议进行定期的胃癌筛查，以便早期发现，早期治疗。患者通常可以选择在消化内科，肿瘤科，胃肠外科挂号就诊。

**Comment by bijinacm** [comment]
> > 请检查数据的抽取结果，模型是否对文本的内容进行了正确抽取。比如肺癌实体抽取出的 '就诊科室' 属性是否有对应的终点实体。是否抽取出了 abnormal(异常指征) 边关系。正常抽取后才会进行点和边的写入
> 
> 你好，例如我的这个数据，胃癌依然没有和胃肠外科连线，结点都有了，但是没有成功连边，能帮我尝试修改下么？我已经对着样例改了，但是没有成功连边，以下是我的Disease.csv文件中的胃癌内容： 胃癌是一种发生在胃部的恶性肿瘤，是全球最常见的恶性肿瘤之一，其发病率和死亡率都极高，对人类健康构成了严重威胁。长期的不良饮食习惯，如过度食用烟熏、腌制、油炸食品等是胃癌的主要病因，同时幽门螺杆菌感染、胃炎、胃溃疡、胃息肉等也都是引发胃癌的重要因素。胃癌的临床表现多种多样，早期胃癌往往没有明显症状，随着病情的发展，可能出现上腹部疼痛、消化不良、食欲减退、体重下降等症状。胃癌的诊断主要依靠胃镜检查和病理学检查。胃癌的治疗主要取决于胃癌的类型和分期，手术、放疗、化疗、靶向治疗、免疫治疗等都是常见的治疗手段。早期胃癌的治疗效果较好，晚期胃癌的治疗效果较差，预后不佳。因此，对于高危人群，建议进行定期的胃癌筛查，以便早期发现，早期治疗。患者通常可以选择在消化内科，肿瘤科，胃肠外科挂号就诊。

在这个提交后，只能看到知识建模的疾病抽样里有胃癌，以及胃癌就诊科室为消化内科，肿瘤科，胃肠外科，但是在分析推理中，不显示这条边，我在分析推理中输入的是以下命令：
MATCH (s:Medicine.Disease)-[r]->(o) RETURN s, r, o
接下来是知识建模的图：
![1](https://github.com/OpenSPG/openspg/assets/109888410/09007bd5-d170-4df3-a1c9-cc637053300e)
下面这个是推理分析输入命令后，观察不到边的图：
![2](https://github.com/OpenSPG/openspg/assets/109888410/a5a21294-7d89-4837-a310-131daa0c1a0a)

**Comment by andylau-55** [comment]
根据你提供的信息，属性中已经获取到了对应的值，理论上会正常输出边关系。属性拉边逻辑会在GraphStoreSinkWriter 写入图存时进行。你可在此处设置日志查看是否进行了正确的拉边转换。
![image](https://github.com/OpenSPG/openspg/assets/19925690/793ba9c8-6def-4625-b574-aededb4c3b90)
或者你可以尝试进行精确的边查询
就诊科室关系：
MATCH
    (s:Medicine.Disease)-[p:department]->(o:Medicine.HospitalDepartment)
RETURN
    s.id,o.id

常见症状
MATCH
    (s:Medicine.Disease)-[p:commonSymptom]->(o:Medicine.Symptom)
RETURN
    s.id,o.id

**Comment by andylau-55** [comment]
![image](https://github.com/OpenSPG/openspg/assets/19925690/87c6469b-5ae3-44a8-8e46-96a9bbacc3e9)
![image](https://github.com/OpenSPG/openspg/assets/19925690/5cc5841e-b2bd-4f04-80c6-f5fe5920fb93)
以上是本地 基于上述文本 构建的结果，请参考
