### ISSUE TITLE
knext命令行和python程序的关系？

### ISSUE THREAD

**Issue by serendipitytoys** [OpenSPG/openspg#300]
在执行医疗图谱的例子时，先在pycharm里面跑了一下body_part.py和hospital_department.py，但是TuGraph网页里没有对应的节点出现，而用命令行执行“knext builder execute BodyPart, HospitalDepartment”后，才会有节点。请问一下这是为什么呢？

**Comment by andylau-55** [comment]
knext定位为openspg的客户端，会做pipeline等构建流程的串联，一步一步去执行对应的python和openspg代码。用户不需要直接手动执行python代码。如果你对knext以及python感兴趣，可以以knext builder execute为入口进行源码的查看
