### ISSUE TITLE
在0.02版本中的医疗图谱中怎么添加规则进行展开，我这没有显示结点，无法展开。

### ISSUE THREAD

**Issue by bijinacm** [OpenSPG/openspg#305]
![33](https://github.com/OpenSPG/openspg/assets/109888410/d54de30c-7f2c-4c32-980c-a8d95791e26d)

**Comment by andylau-55** [comment]
规则的添加可参考"企业供应链"案例https://openspg.yuque.com/ndx6g9/nmwkzz/dwhkxr7o6udthq4n#b242f68d
