### ISSUE TITLE
用户手册中算子示例的问题

### ISSUE THREAD

**Issue by LLL1st** [OpenSPG/openspg#309]
您好，在用户手册中，关于算子的示例，我发现
https://openspg.yuque.com/ndx6g9/nmwkzz/kp5pp2hx8zkrmg0e#adcwC:~:text=5.2-,NERPrompt,-%E9%BB%98%E8%AE%A4%E6%A8%A1%E7%89%88%EF%BC%9A
这里NERPrompt给的示例是REPrompt的示例

**Comment by andylau-55** [comment]
感谢反馈，目前auto_prompt.py中还没有NERPrompt的实现。可以根据REPrompt/OneKE_NERPrompt 进行自定义的实现
