### ISSUE TITLE
在黑产挖掘这个文件的这些是什么，乱码么？在tugraph里查看超级乱

### ISSUE THREAD

**Issue by bijinacm** [OpenSPG/openspg#311]
![01](https://github.com/OpenSPG/openspg/assets/109888410/f3d713ee-b962-4be3-b419-cd73700c66e6)
![02](https://github.com/OpenSPG/openspg/assets/109888410/00f7c525-3a13-4719-ae0e-7e689280faa0)

**Comment by andylau-55** [comment]
该文件是企业拥有证书(Company - hasCert -> Cert) 关系的原始数据表，通过CompanyHasCert类进行导入，可通过OpenSPG的分析推理页面进行图数据的查看
