### ISSUE TITLE
FuseOp的问题

### ISSUE THREAD

**Issue by LLL1st** [OpenSPG/openspg#316]
您好，目前我对FuseOp做了一个实现，bind=Finance.Indicator。我的预期是得到一个 A---B 相连的结构。此时与大模型交互，提供给它一个指标名B和指标列表，让它返回指标列表中与我提供的指标名语义最相近的一个指标，若没有则不返回。
假设交互之后，如果返回了一个指标列表中一个语义相近的指标名C，即是在图谱中已经存在的一个节点，那么我应该会得到 A---C 相连的结构，请问我如何将A---C连接起来呢？因为目前的FuseOp仅是返回SPGRecord

**Comment by andylau-55** [comment]
这需要再FuseOp中做召回，通过指标名称等召回C ，再生成一条A到C的边放入SPGRecord进行返回

**Comment by LLL1st** [comment]
也就是说，融合算子的作用仅是返回相似的SPGRecord或者返回待融合的SPGRecord（没有融合的情况），并没有做连接吗？

**Comment by LLL1st** [comment]
我没太理解您的召回是什么意思呢？
