### ISSUE TITLE
docker镜像拉取失败啊

### ISSUE THREAD

**Issue by Viserion-nlper** [OpenSPG/openspg#320]
![image](https://github.com/OpenSPG/openspg/assets/48983651/57186ebf-23c7-4a26-abd1-4b97341623c1)
请问这是什么原因？

**Comment by Viserion-nlper** [comment]
请相关同事给看下 该镜像是什么原因

**Comment by andylau-55** [comment]
请检查本地的网络环境是否能访问https://hub.docker.com/ ，并且能通过docker pull拉取到镜像。例如执行 docker pull hello-world

**Comment by Viserion-nlper** [comment]
换了国内镜像源也是会出现错误
![image](https://github.com/OpenSPG/openspg/assets/48983651/2621e23d-91af-4e62-b58d-735b9f51c806)

**Comment by dayphosphor** [comment]
同样的问题

**Comment by andylau-55** [comment]
"registry-mirrors": [
    "https://mirror.baidubce.com",
    "https://docker.m.daocloud.io",
    "https://dockerproxy.com",
    "https://docker.nju.edu.cn"
  ] 配置多个代理试下咧，以及阿里云的 "https://xxxxx.mirror.aliyuncs.com"

**Comment by Viserion-nlper** [comment]
![image](https://github.com/OpenSPG/openspg/assets/48983651/6aa6ed2d-7079-43ef-8403-cbcf920dbf90)
老哥 没有别的办法了吗

**Comment by Viserion-nlper** [comment]
![image](https://github.com/OpenSPG/openspg/assets/48983651/8da58d90-691e-4a7f-872a-2affef9fdbf1)

**Comment by Viserion-nlper** [comment]
官方同事给紧急处理下哈

**Comment by caszkgui** [comment]
> 官方同事给紧急处理下哈

you can try this method which works fine for me:
1、touch ./daemon.conf and paste the content below
`{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "registry-mirrors": ["https://b9pmyelo.mirror.aliyuncs.com"]
}`

2、replace docker conf with ./daemon.conf
`
cp ./daemon.conf /etc/docker/daemon.json
`

3、restart docker
`
sudo systemctl daemon-reload
sudo systemctl restart docker
`

**Comment by Viserion-nlper** [comment]
> > 官方同事给紧急处理下哈
> 
> you can try this method which works fine for me: 1、touch ./daemon.conf and paste the content below `{ "exec-opts": ["native.cgroupdriver=systemd"], "registry-mirrors": ["https://b9pmyelo.mirror.aliyuncs.com"] }`
> 
> 2、replace docker conf with ./daemon.conf `cp ./daemon.conf /etc/docker/daemon.json`
> 
> 3、restart docker `sudo systemctl daemon-reload && sudo systemctl restart docker`

我按照该步骤修改后，还是拉不下来

**Comment by caszkgui** [comment]
> > > 官方同事给紧急处理下哈
> > 
> > 
> > you can try this method which works fine for me: 1、touch ./daemon.conf and paste the content below `{ "exec-opts": ["native.cgroupdriver=systemd"], "registry-mirrors": ["https://b9pmyelo.mirror.aliyuncs.com"] }`
> > 2、replace docker conf with ./daemon.conf `cp ./daemon.conf /etc/docker/daemon.json`
> > 3、restart docker `sudo systemctl daemon-reload && sudo systemctl restart docker`
> 
> 我按照该步骤修改后，还是拉不下来

could you install any other docker images ? such as elasticsearch、mysql、redis

**Comment by Viserion-nlper** [comment]
> c

Yes, everything else is fine. It was all correctly pulled down

**Comment by caszkgui** [comment]
> > c
> 
> Yes, everything else is fine. It was all correctly pulled down

could you get your `docker info` response and check whether registry mirror is updated successfully ?

![image](https://github.com/OpenSPG/openspg/assets/15404227/821ea454-ac42-4054-8a70-9e7ca5750a27)

**Comment by Cocolone-pandacue** [comment]
我的也是拉取不下来，直接超时

**Comment by andylau-55** [comment]
You can try this configuration, I verify that it can download
   
"registry-mirrors": [
    "https://public.ecr.aws",
    "https://dockerhub1.beget.com",
    "https://noohub.ru",
    "https://jockerhub.com",
    "https://docker.m.daocloud.io",
    "https://dh-mirror.gitverse.ru",
    "https://huecker.io",
    "https://dockerhub.timeweb.cloud"
  ]
