### ISSUE TITLE
请问Mysql和ES中都保存了Schema的信息，他们的作用分别是什么？

### ISSUE THREAD

**Issue by billc114** [OpenSPG/openspg#327]
观察到Mysql中有几个表kg_ontology_xx，存的是schema中的节点和属性；
观察到ES中也存了schema部分信息，貌似只有节点信息。
请教下他们分别的作用是什么？

**Comment by billc114** [comment]
目前看到ES中也存了所有节点，但是后续推理没有使用，这样做的考虑是什么呢

**Comment by andylau-55** [comment]
MySQL uses this to store metadata about the 'schema'. When building knowledge, entities are written to ES for use in index and chain operators

**Comment by billc114** [comment]
> MySQL uses this to store metadata about the 'schema'. When building knowledge, entities are written to ES for use in index and chain operators

Thx！ tuGraph里同样存了实例节点的所有信息，ES为什么不用tuGraph代替呢？

**Comment by andylau-55** [comment]
TuGraph does not have indexing capabilities yet
