### ISSUE TITLE
tugraph 4.1.0兼容问题

### ISSUE THREAD

**Issue by evilbear** [OpenSPG/openspg#332]
当前tugraph 4.0.1只能支持255个图节点，切换到4.1.0存在bug。目前有兼容修复的计划不

**Comment by billc114** [comment]
这个问题好几个月了，可以先将这个true改为false暂时规避：
![image](https://github.com/user-attachments/assets/4384cd2f-47b6-41c4-8cb9-3a61659f2a38)

**Comment by evilbear** [comment]
666666 work！
