### ISSUE TITLE
请问一下OpenSPG的release计划

### ISSUE THREAD

**Issue by billc114** [OpenSPG/openspg#333]
请问OpenSPG有release计划？
目前看到还没有release过：
![image](https://github.com/user-attachments/assets/94fdd079-3c24-4f8a-94f2-5a24e06dbfcb)

tag也还是beta版的：
![image](https://github.com/user-attachments/assets/e3642246-3519-4000-a82f-d8cf6c04fe05)

**Comment by the-butterfly** [comment]
@billc114 有结果了嘛，issue closed ？

**Comment by w00125533** [comment]
很期待OpenSPG尽快发布一个Release版本

**Comment by andylau-55** [comment]
我们计划在8.15之前发布Release版本，可关注OpenSPG官方通告。感谢您对OpenSPG的支持和关注。

**Comment by billc114** [comment]
> 我们计划在8.15之前发布Release版本，可关注OpenSPG官方通告。感谢您对OpenSPG的支持和关注。

期待期待~

**Comment by Joyce-ZhouY** [comment]
非常期待能发布Release版本！！

**Comment by billc114** [comment]
> 我们计划在8.15之前发布Release版本，可关注OpenSPG官方通告。感谢您对OpenSPG的支持和关注。

请问是以release的形式发布还是以tag的形式发布呢？

**Comment by liang2h** [comment]
期待release版本尽快出来，刚完成本地源码运行和测试，目测spg很符合场景，有计划落地。

**Comment by andylau-55** [comment]
https://github.com/OpenSPG/openspg/releases/tag/v0.0.3  
The release version has been released, welcome to experience
