### ISSUE TITLE
树形关系的schema的查询问题

### ISSUE THREAD

**Issue by Joyce-ZhouY** [OpenSPG/openspg#339]
请问一下：schema是个树形结构，我想要查询根节点到每个叶节点的路径，reasoner查询的时候，有什么简略的写法不需要写出路径上的所有点和边的吗？我试过使用 path: (root:Root)-[p:]->{0,5}(leaf:) 来描述路径，结果不太准确。

**Comment by royzhao** [comment]
可以尝试下
`match (root)-[p]->{0,5}(leaf)  return __path__`

**Comment by royzhao** [comment]
`__path__`会将整个路径作为json格式返回,如下
`[{
	"__alias__": "m",
	"__id__": 8248777770799913213,
	"__label__": "User",
	"kgId": 6381915172615718563,
	"__type__": "vertex",
	"name": "3",
	"description": "3",
	"id": "3",
	"age": 3
}, {
	"__alias__": "n",
	"__id__": 4551451650890805270,
	"__label__": "User",
	"kgId": -2680171185106176564,
	"__type__": "vertex",
	"name": "2",
	"description": "2",
	"id": "2",
	"age": 2
}, {
	"__id__": -8286773200217731421,
	"__label__": "User",
	"kgId": -3496047181088267418,
	"__type__": "vertex",
	"name": "1",
	"description": "1",
	"id": "1",
	"age": 1
}, {
	"__to_id__": "3",
	"__label__": "friend",
	"__type__": "edge",
	"__to_id_type__": "User",
	"__to_internal_id__": 8248777770799913213,
	"__from_id__": "1",
	"__from_internal_id__": -8286773200217731421,
	"__from_id_type__": "User"
}, {
	"__to_id__": "1",
	"__label__": "friend",
	"__type__": "edge",
	"__to_id_type__": "User",
	"__to_internal_id__": -8286773200217731421,
	"__from_id__": "2",
	"__from_internal_id__": 4551451650890805270,
	"__from_id_type__": "User"
}]`
