### ISSUE TITLE
java.lang.ClassCastException: java.lang.String cannot be cast to com.antgroup.openspg.core.schema.model.type.ProjectSchema

### ISSUE THREAD

**Issue by flymoon1314** [OpenSPG/openspg#342]
我出现了同样的问题，不过是在测试https://openspg.yuque.com/ndx6g9/nmwkzz/dht0wtgycuw032gd 中OneKE使用文档中的disease_oneke.py这一项（我并没有在现在的openspg0.0.3的knext/examples/medicine/builder/job/下找到对应py，因此这是我新建并直接复制了文档代码进行测试的），由于文档并未明确给出import部分，我是照着已有的disease.py改的
![image](https://github.com/user-attachments/assets/129ac479-be04-4703-b423-38ef75d410f9)
在命令行测试后，提示如下
![image](https://github.com/user-attachments/assets/a928fdab-da2c-4790-9fac-ff667cfdc478)
通过对比，我发现可能是可能文档代码最后一行可能漏了个s
![image](https://github.com/user-attachments/assets/ce864fbd-c0fd-4a00-9438-2db2c607d8f6)
填了这个s后，确实不报这个错了，但出现了如下错误
![image](https://github.com/user-attachments/assets/a6ebbf28-eee4-4189-808a-5a25d1c8b07b)
这可能是类型转换导致的异常？我是初学者，无法自行解决这个问题，故提交这个issue

双端的docker均是按照文档说明进行的下载，服务器端的ui界面正常，客户端使用的也是文档要求的linux/x86_64 openspg/openspg-python:latest
值得一提的是，我之前按照https://openspg.yuque.com/ndx6g9/nmwkzz/eggc243mxc5quqsx 的黑产挖掘案例执行测试时，执行到step3时（见下图），也出现了该错误
![image](https://github.com/user-attachments/assets/971eec46-79bd-4f24-b94b-80888e1d5449)
![image](https://github.com/user-attachments/assets/0c79a618-fc61-40da-b255-75a043f3f5be)
也就是说schema commit是正常的，我能在ui上看到对应的知识模型，但到了builder execute出错了
若有人能不吝赐教，不胜感激！

**Comment by flymoon1314** [comment]
docker images如下
![image](https://github.com/user-attachments/assets/27b5d483-df7f-4cf9-a487-3492c6a25f63)

**Comment by flymoon1314** [comment]
镜像版本如下
![image](https://github.com/user-attachments/assets/305977a5-5726-4754-a732-b56f0befd2e3)
![image](https://github.com/user-attachments/assets/1303b2ea-4417-494e-bd8d-ee567cab4647)
![image](https://github.com/user-attachments/assets/96075c45-5ede-4c27-926b-b35e90e83e04)

**Comment by andylau-55** [comment]
Thanks for your feedback. Due to the docker network problem, the previous image cannot be obtained. Please follow the  document to fetch the latest openspg-python image again
https://openspg.yuque.com/ndx6g9/nmwkzz/xht6kkegvs33cwwr
