### ISSUE TITLE
前端分析推理页面的DSL语句输入窗口一直显示loading

### ISSUE THREAD

**Issue by ccccchristine3117** [OpenSPG/openspg#350]
浏览器报错显示Failed to load resource：the server responded with a iconfont.woff2:1 status of 404 ()
Failed to load resource:gw. alipayobjects.com... /min/vs/loader. js:1
net::ERR_NAME _NOT RESOLVED
Monaco initialization: error vendors_0-async. 5e2b7ca1. js: 1
Uncaught (in promise)  Event : 8887/#/analysisReasoning? projectID=3: 1

**Comment by andylau-55** [comment]
Please clear the page cache and try again or use a no trace browser
