### ISSUE TITLE
install报错java.lang.NoSuchMethodError: org.fusesource.jansi.AnsiConsole.wrapOutputStream(Ljava/io/OutputStream;)Ljava/io/OutputStream;

### ISSUE THREAD

**Issue by lfzdsg** [OpenSPG/openspg#353]
我是在windows下编译，但是编译时报错显示什么jansi库的问题，多方查找没有找到问题，使用mvn dependency:tree没有显示问题，但是mvn dependency:analyze也会显示标题jansi报错

**Comment by andylau-55** [comment]
使用java1.8 maven3.8.5 能正常编译通过，请检查本地环境
