### ISSUE TITLE
宣传的可视化界面有个新建知识库按钮，怎么我在服务端

### ISSUE THREAD

**Issue by hiro110110** [OpenSPG/openspg#357]
![image](https://github.com/user-attachments/assets/687f85ea-4a23-45b3-b7ce-9a9d3a07f5df)
可视化界面少了一个新建知识库按钮，是不是要从客户端进才有这个按钮？客户端的可视化界面有没有默认端口或者默认地址？

**Comment by andylau-55** [comment]
目前Release版本还不包含知识库的相关能力，可关注OpenSPG的后续发布内容
