### ISSUE TITLE
schema建模咨询

### ISSUE THREAD

**Issue by zhangcongxiao** [OpenSPG/openspg#37]
您好，我在基于当前业务数据表结构使用SPG构建schema时遇到了一些困难，想咨询交流一下。
业务场景简述如下：主表A, 有两个业务属性id1, id2,可以理解为该实体的一个联合主键，另外有若干表Z1,Z2,...., schema描述如下：
```txt
Z1(实体Z1): EntityType
    properties:
        id1(id1):Text
        id2(id2):Text
        p11(属性p11):Text
        p12(属性p12):Text
        p13(属性p13):Text

Z2(实体Z2): EntityType
    properties:
        id1(id1):Text
        id2(id2):Text
        p21(属性p21):Text
        p22(属性p21):Text
        p23(属性p23):Text

A(实体A): EntityType
    properties:
        id1(id1):Text
        id2(id2):Text
```
可以理解A实体有很多p属性，但是业务逻辑上有聚合性且属性众多，所以拆分成若干个Z实体。
业务诉求是在基于不同Z实体之间的组合，对其属性进行进一步的逻辑计算得出结果，期望在schema实现这种约束，类似如下：
```txt
A(实体A): EntityType
    properties:
        id1(id1):Text
        id2(id2):Text
        re1:Text
            rule: [[
                 {
                    STRUCTURE {
                   (s:A)-[p:relationAToZ1]->(f1:Z1)
                   (s:A)-[p:relationAToZ2]->(f2:Z2)
                    }
                    CONSTRAINT {
                     o = f1.p11 + f2.p22
                    }
                }
             ]]
    relations:
       relationAToZ1(relationAToZ1关系): Z1
       relationAToZ2(relationAToZ1关系): Z2
```
当我参考企业供应链2.2章节构建A和不同z实体关系时遇到了困难，我先尝试了手动构造了若干个不同z实体和实体A的关系表，并定义了relationAToZ1的BuilderJob，这种是可以走通的。
当我尝试Define语法去定义这种关系，却无法走通，我尝试的定义如下，在提交schema时就报错了：
```txt
    relations:
       relationAToZ1(relationAToZ1关系): Z1
       rule: [[
             Define (s:A)-[p:relationAToZ1]->(o:Z1) {
                 Structure {
                   (s)-[s:id1]->(o)
                   (s)-[s:id2]->(o)
                 }
                 Constraint {
                   R1: s.id1 == o.id1
                   R2: s.id2 == o.id2
                 }
             }
         ]]
```

请问下要定义这个关系该如何实现呢，或者为了实现对应业务目标有没有更好的建模方式，期待您的解答^·^

**Comment by baifuyu** [comment]
> 您好，我在基于当前业务数据表结构使用SPG构建schema时遇到了一些困难，想咨询交流一下。 业务场景简述如下：主表A, 有两个业务属性id1, id2,可以理解为该实体的一个联合主键，另外有若干表Z1,Z2,...., schema描述如下：
> 
> ```
> Z1(实体Z1): EntityType
>     properties:
>         id1(id1):Text
>         id2(id2):Text
>         p11(属性p11):Text
>         p12(属性p12):Text
>         p13(属性p13):Text
> 
> Z2(实体Z2): EntityType
>     properties:
>         id1(id1):Text
>         id2(id2):Text
>         p21(属性p21):Text
>         p22(属性p21):Text
>         p23(属性p23):Text
> 
> A(实体A): EntityType
>     properties:
>         id1(id1):Text
>         id2(id2):Text
> ```
> 
> 可以理解A实体有很多p属性，但是业务逻辑上有聚合性且属性众多，所以拆分成若干个Z实体。 业务诉求是在基于不同Z实体之间的组合，对其属性进行进一步的逻辑计算得出结果，期望在schema实现这种约束，类似如下：
> 
> ```
> A(实体A): EntityType
>     properties:
>         id1(id1):Text
>         id2(id2):Text
>         re1:Text
>             rule: [[
>                  {
>                     STRUCTURE {
>                    (s:A)-[p:relationAToZ1]->(f1:Z1)
>                    (s:A)-[p:relationAToZ2]->(f2:Z2)
>                     }
>                     CONSTRAINT {
>                      o = f1.p11 + f2.p22
>                     }
>                 }
>              ]]
>     relations:
>        relationAToZ1(relationAToZ1关系): Z1
>        relationAToZ2(relationAToZ1关系): Z2
> ```
> 
> 当我参考企业供应链2.2章节构建A和不同z实体关系时遇到了困难，我先尝试了手动构造了若干个不同z实体和实体A的关系表，并定义了relationAToZ1的BuilderJob，这种是可以走通的。 当我尝试Define语法去定义这种关系，却无法走通，我尝试的定义如下，在提交schema时就报错了：
> 
> ```
>     relations:
>        relationAToZ1(relationAToZ1关系): Z1
>        rule: [[
>              Define (s:A)-[p:relationAToZ1]->(o:Z1) {
>                  Structure {
>                    (s)-[s:id1]->(o)
>                    (s)-[s:id2]->(o)
>                  }
>                  Constraint {
>                    R1: s.id1 == o.id1
>                    R2: s.id2 == o.id2
>                  }
>              }
>          ]]
> ```
> 
> 请问下要定义这个关系该如何实现呢，或者为了实现对应业务目标有没有更好的建模方式，期待您的解答^·^

hi，不知道我有没有理解对？业务的诉求是要【基于不同Z实体之间的组合，对其属性进行进一步的逻辑计算得出结果，期望在schema实现这种约束】。

那这种约束其实就是您第一次理解的那样，类似于这样：

`
Z1(实体Z1)：EntityType
    properties:
        p11(p11): Integer

Z2(实体Z2)：EntityType
    properties:
        p22(p22): Integer

A(实体A): EntityType
    properties:
        id1(id1):Text
        id2(id2):Text
        re1:Integer
            rule: [[
                 Define (s:A)-[p:re1]->(o:Integer) {
                 {
                    STRUCTURE {
                   (s:A)-[p:relationAToZ1]->(f1:Z1)
                   (s:A)-[p:relationAToZ2]->(f2:Z2)
                    }
                    CONSTRAINT {
                     o = f1.p11 + f2.p22
                    }
                }
             ]]
    relations:
       relationAToZ1(relationAToZ1关系): Z1
       relationAToZ2(relationAToZ1关系): Z2
`

不知道上面的描述有没有解决您问题，欢迎交流~

**Comment by zhangcongxiao** [comment]
这个写法是可以提交schema是成功了 但是执行dsl语句查询re1都是null，我困惑的一点是re1计算逻辑的前提是，A的属性id1和id2要Z1 Z1实体的都能相等，这个约束条件是怎么体现呢

**Comment by baifuyu** [comment]
> 这个写法是可以提交schema是成功了 但是执行dsl语句查询re1都是null，我困惑的一点是re1计算逻辑的前提是，A的属性id1和id2要Z1 Z1实体的都能相等，这个约束条件是怎么体现呢


我理解您这里是想达到类似于关系型数据库外键的那种效果吗？上面的图谱schema定义中，将id1和id2的类型从Text改成Z1和Z2，那在导入A的实例数据时，会自动与Z1和Z2的实例数据拉一条边的，如果边拉不上那就代表该A实例的id1属性在Z1实例中不存在。举个简单的例子：

Person 表示A，AlipayAccount 表示Z1，BankOfChinaAccount表示Z2。那可以创建以下的schema：
```
AlipayAccount(支付宝账号)：EntityType
    properties:
        money(金额): Integer

BankOfChinaAccount(中行账号)：EntityType
    properties:
        money(金额): Integer

Person(用户): EntityType
    properties:
       alipayAccount支付宝余额):AlipayAccount
       bocAccount(i中行余额):BankOfChinaAccount
       total_money(总余额): Integer
            rule: [[
                 Define (s:Person)-[p:total_money]->(o:Integer) {
                 {
                    STRUCTURE {
                         # Person具有AlipayAccount和BankOfChinaAccount的属性，默认也会有到他们的边
                          (s:Person)-[p1:alipayAccount]->(f1:AlipayAccount)
                         (s:Person)-[p2:bocAccount]->(f2:BankOfChinaAccount)
                    }
                    CONSTRAINT {
                        o = f1.money + f2.money
                    }
                }
             ]]
```

建立完该schema后，可以将AlipayAccount和BankOfChinaAccount数据先导入图谱中，然后再导入Person数据。
1. 当一个人用对应的AlipayAccount和BankOfChinaAccount时，则上述的STRUCTURE的模式就会成立，则total_money就会有结果
2. 当一个人如果没有AlipayAccount或者BankOfChinaAccount时，则上述的STRUCTURE的模式就不会成立，则total_money就会是null

**Comment by zhangcongxiao** [comment]
感谢解答，还是有些困惑希望继续交流下：
将id1和id2的类型从Text改成Z1和Z2，这句话怎么理解呢。 
回到最初的问题当前的模型是这样的，不是id1和id2分别代表了A和Z1,Z1的关联关系，而是一个联合主键来映射A和Z1的关系，A和Z2的关系，似乎和你举的例子维度不一样。
```txt
Z1(实体Z1): EntityType
    properties:
        id1(id1):Text
        id2(id2):Text
        p11(属性p11):Text

Z2(实体Z2): EntityType
    properties:
        id1(id1):Text
        id2(id2):Text
        p21(属性p21):Text

A(实体A): EntityType
    properties:
        id1(id1):Text
        id2(id2):Text
```
第二点：
在你给代码示例中，“当一个人用对应的AlipayAccount和BankOfChinaAccount时”， 这句话对应的数据体现是个什么情况呢，是AlipayAccount 和Person实际的数据表中都有个id属性，然后会自动对应起来吗（如果AlipayAccount 表中没有Person中定义的id,则这一行即这个人的total_money会呈现为null）。不知道我理解的对不对

**Comment by baifuyu** [comment]
> 感谢解答，还是有些困惑希望继续交流下, 我的核心问题其实就是在schema怎么动态建立两个实体之间的关系，这个关系可能是需要两个字段去同时对应的, 这个好像还没有得到我想要的答案。 第一点： 将id1和id2的类型从Text改成Z1和Z2，这句话怎么理解呢。 回到最初的问题当前的模型是这样的，不是id1和id2分别代表了A和Z1,Z1的关联关系，而是一个联合主键来映射A和Z1的关系，A和Z2的关系，似乎和你举的例子维度不一样。
> 
> ```
> Z1(实体Z1): EntityType
>     properties:
>         id1(id1):Text
>         id2(id2):Text
>         p11(属性p11):Text
> 
> Z2(实体Z2): EntityType
>     properties:
>         id1(id1):Text
>         id2(id2):Text
>         p21(属性p21):Text
> 
> A(实体A): EntityType
>     properties:
>         id1(id1):Text
>         id2(id2):Text
> ```
> 
> 第二点： 在你给代码示例中，“当一个人用对应的AlipayAccount和BankOfChinaAccount时”， 这句话对应的数据体现是个什么情况呢，是AlipayAccount 和Person实际的数据表中都有个id属性，然后会自动对应起来吗（如果AlipayAccount 表中没有Person中定义的id,则这一行即这个人的total_money会呈现为null）。不知道我理解的对不对

对于第二点来说：从业务上理解，就是会有3张表：

第一张是Person表：字段分别是 id(用户id), alipay_account_id(支付宝账户id), boc_account_id(中行账户id)
第二张是AlipayAccount表：字段分为是id(支付宝账户id), money(支付宝账户余额)
第三张是BankOfChinaAccount表，字段分为是id(中行账户id), money(中行账户余额)

假设业务有上面3张表，那建模成以下的schema时合理的。其中person的total_money通过逻辑规则定义，由支付宝账户和中行账户余额相加。
```
AlipayAccount(支付宝账号)：EntityType
    properties:
        money(金额): Integer

BankOfChinaAccount(中行账号)：EntityType
    properties:
        money(金额): Integer

Person(用户): EntityType
    properties:
       alipayAccount支付宝余额):AlipayAccount
       bocAccount(i中行余额):BankOfChinaAccount
       total_money(总余额): Integer
            rule: [[
                 Define (s:Person)-[p:total_money]->(o:Integer) {
                 {
                    STRUCTURE {
                         # Person具有AlipayAccount和BankOfChinaAccount的属性，默认也会有到他们的边
                          (s:Person)-[p1:alipayAccount]->(f1:AlipayAccount)
                         (s:Person)-[p2:bocAccount]->(f2:BankOfChinaAccount)
                    }
                    CONSTRAINT {
                        o = f1.money + f2.money
                    }
                }
             ]]
```

再回到第一点：从客观世界建模来说，一个实体类型的实例只会有一个id标识，比如支付宝账号有id，每个人有身份证id等等。openspg也是一样，每个实体实例或者概念实例都有一个唯一id，暂时还不支持联合主键的方式来表达一个实例。业务上可以考虑把这id1, id2 给concat起来作为实例的唯一id。

**Comment by zhangcongxiao** [comment]
明白了。还有一点没有明白，Person的alipay_account_id 和AlipayAccount 的id(支付宝账户id) ，这两个的映射关系在哪定义的呢，我看schema里面没有体现。

**Comment by baifuyu** [comment]
> 明白了。还有一点没有明白，Person的alipay_account_id 和AlipayAccount 的id(支付宝账户id) ，这两个的映射关系在哪定义的呢，我看schema里面没有体现。

可以再参考下我们的黑产挖掘例子的schema，链接：https://spg.openkg.cn/example/risk-mining

其中部分的schema是这样的：

![image](https://github.com/OpenSPG/openspg/assets/147798664/b318c049-0435-427c-8a4c-81b4aaa102f2)

App有个属性useCert，它的类型是Cert。然后Cert定义了certNum属性。这里需要注意的有以下几点：

1. Cert 和 App都是定义了 EntityType，默认是继承了Thing，Thing上有id和name默认会被Cert和App继承，所以Cert和App默认不用定义id和name字段；
2. App的useCert属性的类型是Cert，当我们导入App数据时，默认会通过idEquals的策略与Cert关联（这里也可以指定其他的链指策略）。在导入App数据时，builder模块判断当前App实例的useCert值是已存在的某个Cert，那么该App实例就会和对应的Cert建立一条useCert的边，如果不存在某个Cert，则这个边就关联不上。

**Comment by baifuyu** [comment]
> 明白了。还有一点没有明白，Person的alipay_account_id 和AlipayAccount 的id(支付宝账户id) ，这两个的映射关系在哪定义的呢，我看schema里面没有体现。

画个图更好理解一些：

![image](https://github.com/OpenSPG/openspg/assets/147798664/d91c053a-ff16-4607-9692-e45bdd19b206)

上面的schema对应的一个数据实例如上。【支付宝证书】实例的id是cert1，【支付宝app】的id是app1，useCert属性是cert1，正好是【支付宝证书】的实例id。那么这里通过idEquals的链指策略，我们可以将【支付宝app】中的useCert属性链接到【支付宝证书】这个实例上。另外用户也可以自定义别的链指策略，比如可以使用名称相等或者搜索召回等链指策略。

不知道以上是否能解答您的疑惑哈？

**Comment by zhangcongxiao** [comment]
这个idEquals的链指策略有具体介绍吗，我们怎么自定义别的链指策略呢。
”useCert属性是cert1，正好是【支付宝证书】的实例id“，但是我看你们黑产挖掘的案例中给的数据，App中useCert属性是对应Cert的certNum，如下：
App.csv
```csv
id,riskMark,useCert
com.ucyDA.gNLGD.oQsbzPe.nQd,UNKNOWN,68802adde35845d76eeb172ff8ea6825
com.Beze.rCOE.ugTRJN,UNKNOWN,d8e654984321f6aac312a897071191f0
```
Cert.csv
```csv
id,certNum
0,68802adde35845d76eeb172ff8ea6825
1,d8e654984321f6aac312a897071191f0
```

**Comment by zhangcongxiao** [comment]
> 这个idEquals的链指策略有具体介绍吗，我们怎么自定义别的链指策略呢。 ”useCert属性是cert1，正好是【支付宝证书】的实例id“，但是我看你们黑产挖掘的案例中给的数据，App中useCert属性是对应Cert的certNum，如下： App.csv
> 
> ```
> id,riskMark,useCert
> com.ucyDA.gNLGD.oQsbzPe.nQd,UNKNOWN,68802adde35845d76eeb172ff8ea6825
> com.Beze.rCOE.ugTRJN,UNKNOWN,d8e654984321f6aac312a897071191f0
> ```
> 
> Cert.csv
> 
> ```
> id,certNum
> 0,68802adde35845d76eeb172ff8ea6825
> 1,d8e654984321f6aac312a897071191f0
> ```

看到了是在BuilderJob体现的吗？
```python

class Cert(BuilderJob):

    def build(self):
        source = SourceCsvComponent(
            local_path="./builder/job/data/Cert.csv",
            columns=["id", 'certNum'],
            start_row=2
        )

        mapping = EntityMappingComponent(
            spg_type_name=RiskMining.Cert
        ).add_field("certNum", RiskMining.Cert.id) \   //  此处
            .add_field("certNum", RiskMining.Cert.certNum) \    
            .add_field("certNum", RiskMining.Cert.name)

        sink = SinkToKgComponent()

        return source >> mapping >> sink

```

**Comment by zhangcongxiao** [comment]
默认的链指策略，和如何自定义链指策略，这块对于用户去理解SPG还是很重要的，至少我在这块花了好久通过交流才弄清楚，这块后面可以在文档中多花点笔墨介绍下

**Comment by baifuyu** [comment]
> ”useCert属性是cert1，正好是【支付宝证书】的实例id“，我理解下实际的数据是App中useCert属性是对应Cert的certNum，如下： App.csv
> 
> ```
> id,riskMark,useCert
> com.ucyDA.gNLGD.oQsbzPe.nQd,UNKNOWN,68802adde35845d76eeb172ff8ea6825
> com.Beze.rCOE.ugTRJN,UNKNOWN,d8e654984321f6aac312a897071191f0
> ```
> 
> Cert.csv
> 
> ```
> id,certNum
> 0,68802adde35845d76eeb172ff8ea6825
> 1,d8e654984321f6aac312a897071191f0
> ```
> 
> 但在BuilderJob 对id做了重新赋值, 所有就实现了想要的映射关系, 这块我明白了，有点隐蔽：
> 
> ```python
> class Cert(BuilderJob):
> 
>     def build(self):
>         source = SourceCsvComponent(
>             local_path="./builder/job/data/Cert.csv",
>             columns=["id", 'certNum'],
>             start_row=2
>         )
> 
>         mapping = EntityMappingComponent(
>             spg_type_name=RiskMining.Cert
>         ).add_field("certNum", RiskMining.Cert.id) \   //  此处
>             .add_field("certNum", RiskMining.Cert.certNum) \    
>             .add_field("certNum", RiskMining.Cert.name)
> 
>         sink = SinkToKgComponent()
> 
>         return source >> mapping >> sink
> ```
> 
> 关于自定义实体链指算子，看指导文档时看到这块没有给出具体的代码示例，就忽略了，我再对着企业供应链的案列研究下吧

是的。实际的csv数据，会经过mapping按照schema的格式导入到图谱中。Cert数据的certNum既导入到id字段，也导入到了certNum字段了。

**Comment by baifuyu** [comment]
> 默认的链指策略，和如何自定义链指策略，这块对于用户去理解SPG还是很重要的，至少我在这块花了好久通过交流才弄清楚，这块后面可以在文档中多花点笔墨介绍下。 相当长的时间在研究relation这块是如何使用了

好的~，这块我们会完善下文档。目前第一版实现还有点不太完善，下个月我们会再发布一版，把其中的算子（包含链指，抽取，标化等算子）都会详细介绍下，非常感谢宝贵的意见。
