### ISSUE TITLE
DSL的GraphStructure块里是否支持完整的GQL？

### ISSUE THREAD

**Issue by billc114** [OpenSPG/openspg#373]
我使用如下查询：
```
knext reasoner execute --dsl "                                                               

GraphStructure {
   Match (cell:TestPro.Mytest)
   WHERE cell.myid=2108322
}
CONSTRAINT {

}
Action {
     get(cell)
}
"
```
会报错：
![image](https://github.com/user-attachments/assets/d643b692-2597-42f2-81cd-c9ee71b2e53f)

看起来像是不支持完整的GQL语法

**Comment by royzhao** [comment]
GraphStructure中只能写图结构
要么
`GraphStructure {
    (cell:TestPro.Mytest)
}
CONSTRAINT {
R1:cell.myid=2108322
}
Action {
     get(cell)
}`
要么直接写GQL
`Match (cell:TestPro.Mytest)  WHERE cell.myid=2108322 return cell`

**Comment by royzhao** [comment]
语法怎么写不会影响到后续的执行计划，可以参考[https://github.com/OpenSPG/openspg/blob/master/reasoner/lube-logical/src/main/scala/com/antgroup/openspg/reasoner/lube/logical/optimizer/rules/FilterPushDown.scala](url)，实现了过滤下推，你写在CONSTRAINT中也会被提前执行，如果觉得哪里性能还可以优化，可以在optimizer目录新增优化策略，欢迎提pr
