### ISSUE TITLE
ERROR: alter schema unknown error

### ISSUE THREAD

**Issue by tuninger** [OpenSPG/openspg#383]
根据安装文档执行到knext schema commit这个步骤时，报错。

Create type: Medicine.Symptom
Create type: Medicine.Drug
Create type: Medicine.Indicator
Create type: Medicine.BodyPart
Create type: Medicine.HospitalDepartment
Create type: Medicine.Disease
Create relation: [Medicine.Disease] abnormal
ERROR: alter schema unknown error

尝试换个examples还是报错。

Create type: RiskMining.TaxOfRiskUser
Create type: RiskMining.TaxOfRiskApp
Create type: RiskMining.Cert
Create type: RiskMining.App
Create type: RiskMining.Company
Create relation: [RiskMining.Company] hasCert
Create relation: [RiskMining.Company] holdShare
Create type: RiskMining.Device
Create type: RiskMining.Person
Create relation: [RiskMining.Person] hasDevice
Create relation: [RiskMining.Person] hasCert
Create relation: [RiskMining.Person] holdShare
Create relation: [RiskMining.Person] fundTrans
Create relation: [RiskMining.Person] developed
Create relation: [RiskMining.Person] release
ERROR: alter schema unknown error

请问这个如何解决？谢谢。

**Comment by NoelYin** [comment]
遇到相同问题了，同问

**Comment by caszkgui** [comment]
> 安装文档执行到

May I ask，which document did you refer to to perform the operation?
KAG provides two modes to startup, one is product mode with user manunal reference: [product mode](https://github.com/OpenSPG/KAG?tab=readme-ov-file#31-product-based-for-ordinary-users), and the other one is developer mode with user manual reference: [developer mode](https://github.com/OpenSPG/KAG?tab=readme-ov-file#32-toolkit-based-for-developers)

**Comment by NoelYin** [comment]
OK，发现问题了，目测是0.5的KAG和0.0.3的OpenSPG手册里服务端的docker-compose.yml混用了。我这里是0.5的服务端docker-compose.yml错误搭配了0.0.3的客户端代码，不知道楼上是不是类似的问题
