### ISSUE TITLE
执行图谱任务时遇到“Reasoner must be executed with SPG Server”错误

### ISSUE THREAD

**Issue by debrisvector** [OpenSPG/openspg#384]
我在使用 Docker 方法安装的服务器上尝试执行图谱任务时遇到了错误：“Reasoner must be executed with SPG Server”。已经成功安装并可以执行 knext 命令，并且能够正常提交知识导入任务。但在执行图谱任务（Step 5）时，遇到了上述错误。
详细信息：
运行以下命令时：
`knext reasoner execute --dsl "${ql}"`
收到以下错误消息：
`ERROR: Reasoner must be executed with SPG Server.`
同理在运行时
```
knext reasoner execute --dsl "
MATCH
    (s:SupplyChain.Company)-[:mainSupply]->(o:SupplyChain.Company)
RETURN
    s.name, o.name
"
```
依旧收到以下错误信息
`ERROR: Reasoner must be executed with SPG Server.`
Docker 容器状态正常：
```
CONTAINER ID   IMAGE                                                                COMMAND                  CREATED        STATUS       PORTS                                                                                            NAMES
f4e7404176fb   spg-registry.cn-hangzhou.cr.aliyuncs.com/spg/openspg-server:latest   "java -jar arks-sofa…"   25 hours ago   Up 3 hours   0.0.0.0:8887->8887/tcp, :::8887->8887/tcp                                                        release-openspg-server
c6b0ceb25e8c   spg-registry.cn-hangzhou.cr.aliyuncs.com/spg/openspg-mysql:latest    "docker-entrypoint.s…”   25 hours ago   Up 3 hours   0.0.0.0:3306->3306/tcp, :::3306->3306/tcp                                                        release-openspg-mysql
cf3809e68885   spg-registry.cn-hangzhou.cr.aliyuncs.com/spg/openspg-neo4j:latest    "tini -g -- /startup…"   25 hours ago   Up 3 hours   0.0.0.0:7474->7474/tcp, :::7474->7474/tcp, 7473/tcp, 0.0.0.0:7687->7687/tcp, :::7687->7687/tcp   release-openspg-neo4j
```
可以看到 openspg-server 正在运行，并且端口映射为 8887，且能从网页端打开和上传内容。
Docker 版本：26.1.4
操作系统：CentOS 7.9 (64位)

**Comment by royzhao** [comment]
你好，执行dsl需要从kag_config.cfg从获取地址信息，默认是从命令执行目录下找
`@click.option("--proj_path", help="Path of config.", default="./")
def execute_reasoner_job(file, dsl, output=None, proj_path="./"):
    """
    Submit asynchronous reasoner jobs to server by providing DSL file or string.
    """
    config_path = os.path.join(proj_path, "kag_config.cfg")`
