### ISSUE TITLE
感觉项目组，这个框架比直接用大模型抽取效率和准确率都好，对硬件要求显著降低，希望开放早期版本里有的实体检索、图谱检索功能

### ISSUE THREAD

**Issue by woniu003007** [OpenSPG/openspg#386]
感觉项目组，这个框架比直接用大模型抽取效率和准确率都好，对硬件要求显著降低，希望开放早期版本里有的实体检索、图谱检索功能

**Comment by andylau-55** [comment]
Thank you for your feedback, we will support it in the next version
