### ISSUE TITLE
知识抽取过程中会把中文原文转成英文存在图数据库

### ISSUE THREAD

**Issue by jt6371** [OpenSPG/openspg#388]
所用的生成模型：Qwen2.5的3B版本，测试用TXT见附件
[温人大〔2022〕61号.txt](https://github.com/user-attachments/files/17614067/2022.61.txt)
截图如下：
![微信图片_20241104133046](https://github.com/user-attachments/assets/8282da0c-b841-4cf0-96ca-2df410d3a584)

**Comment by andylau-55** [comment]
Please pull the latest image，Set the prompt on the project to {
  "biz_scene":"default",
  "language":"zh"
}
