### ISSUE TITLE
No module named 'knext.common.vectorizer'

### ISSUE THREAD

**Issue by moming975** [OpenSPG/openspg#394]
![image](https://github.com/user-attachments/assets/81fad9e6-9c1f-4225-b9db-ef55558fb19b)

```<class 'RuntimeError'>: invalid vectorizer config: No module named 'knext.common.vectorizer'```

**Comment by caszkgui** [comment]
> ![image](https://private-user-images.githubusercontent.com/103560656/383486894-81fad9e6-9c1f-4225-b9db-ef55558fb19b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4ODU0MTgsIm5iZiI6MTczMDg4NTExOCwicGF0aCI6Ii8xMDM1NjA2NTYvMzgzNDg2ODk0LTgxZmFkOWU2LTljMWYtNDIyNS1iOWRiLWVmNTU1NThmYjE5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQwOTI1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTM0M2MwMjY1ZTg5YjhjY2ExZDQ0YjcwYjJlODhlMmY2YWZjM2UwNjVmNTZhZDY2ZjlhOTdkYTI5NDc5MTg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yvWGiXTn10oOCLT8nsv6OVUdHegSNJoLAx0ZHjNd4SA)
> 
> `<class 'RuntimeError'>: invalid vectorizer config: No module named 'knext.common.vectorizer'`

`knext.common.vectorizer` should change to `kag.common.vectorizer`

**Comment by moming975** [comment]
think 

> > ![image](https://private-user-images.githubusercontent.com/103560656/383486894-81fad9e6-9c1f-4225-b9db-ef55558fb19b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4ODU0MTgsIm5iZiI6MTczMDg4NTExOCwicGF0aCI6Ii8xMDM1NjA2NTYvMzgzNDg2ODk0LTgxZmFkOWU2LTljMWYtNDIyNS1iOWRiLWVmNTU1NThmYjE5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQwOTI1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTM0M2MwMjY1ZTg5YjhjY2ExZDQ0YjcwYjJlODhlMmY2YWZjM2UwNjVmNTZhZDY2ZjlhOTdkYTI5NDc5MTg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yvWGiXTn10oOCLT8nsv6OVUdHegSNJoLAx0ZHjNd4SA)
> > `<class 'RuntimeError'>: invalid vectorizer config: No module named 'knext.common.vectorizer'`
> 
> `knext.common.vectorizer` should change to `kag.common.vectorizer`

Thank you, I always thought it was a problem with the code before realizing it was a configuration issue. I wrote it according to the official document, and I hope the official can update the document

https://openspg.yuque.com/ndx6g9/0.5/cfiaugez2n72g08k

**Comment by caszkgui** [comment]
> think
> 
> > > ![image](https://private-user-images.githubusercontent.com/103560656/383486894-81fad9e6-9c1f-4225-b9db-ef55558fb19b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4ODU0MTgsIm5iZiI6MTczMDg4NTExOCwicGF0aCI6Ii8xMDM1NjA2NTYvMzgzNDg2ODk0LTgxZmFkOWU2LTljMWYtNDIyNS1iOWRiLWVmNTU1NThmYjE5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQwOTI1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTM0M2MwMjY1ZTg5YjhjY2ExZDQ0YjcwYjJlODhlMmY2YWZjM2UwNjVmNTZhZDY2ZjlhOTdkYTI5NDc5MTg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yvWGiXTn10oOCLT8nsv6OVUdHegSNJoLAx0ZHjNd4SA)
> > > `<class 'RuntimeError'>: invalid vectorizer config: No module named 'knext.common.vectorizer'`
> > 
> > 
> > `knext.common.vectorizer` should change to `kag.common.vectorizer`
> 
> Thank you, I always thought it was a problem with the code before realizing it was a configuration issue. I wrote it according to the official document, and I hope the official can update the document
> 
> https://openspg.yuque.com/ndx6g9/0.5/cfiaugez2n72g08k

Thanks for your advice， the user manual has been updated.
