### ISSUE TITLE
离线部署时，会由于缺失js导致打开对话一直处于Loading状态

### ISSUE THREAD

**Issue by itshaungmu** [OpenSPG/openspg#397]
1、镜像手动导入到离线环境上进行项目部署运行。
2、打开知识库问答功能，一直处于Loading。
3、<script src="https://gw.alipayobjects.com/os/lib/monaco-editor/0.34.0/min/vs/loader.js"></script> 直接引用了外部地址的js，导致无法正常加载会话页面。

期望可以支持离线部署开发场景。

**Comment by caszkgui** [comment]
> 1、镜像手动导入到离线环境上进行项目部署运行。 2、打开知识库问答功能，一直处于Loading。 3、<script src="https://gw.alipayobjects.com/os/lib/monaco-editor/0.34.0/min/vs/loader.js"></script> 直接引用了外部地址的js，导致无法正常加载会话页面。
> 
> 期望可以支持离线部署开发场景。

thanks for your feedback, docker image stand alone will be released at the month.

**Comment by andylau-55** [comment]
This feature has been released in version 0.5.1
https://github.com/OpenSPG/openspg/releases/tag/v0.5.1
