### ISSUE TITLE
有办法做到将不同知识库隔离起来吗？

### ISSUE THREAD

**Issue by liningping** [OpenSPG/openspg#403]
希望不同主题的知识库互相隔离，例如在使用法律知识库QA时，不要检索到金融知识库中的相关信息，此外，试图使用以下代码删除Neo4j中的图谱数据时，会得到```ValueError: Cannot resolve address release-openspg-neo4j:7687```

```
from kag.common.graphstore.neo4j_graph_store import Neo4jClient

test = Neo4jClient(uri="neo4j://release-openspg-neo4j:7687", user="neo4j", password="neo4j@openspg")
test.delete_all_data("neo4j")
```

**Comment by andylau-55** [comment]
Currently, data is isolated at the project level. You can create different project instances to isolate neo4j data.
