### ISSUE TITLE
文档过期

### ISSUE THREAD

**Issue by yujchn** [OpenSPG/openspg#404]
代码中未找到examples目录，请更新文档或示例代码

**Comment by andylau-55** [comment]
Please refer to the document:

**Comment by liux2** [comment]
Could you please update the path to schema examples? Thanks a lot!
<img width="1512" alt="Screenshot 2024-11-21 at 5 08 45 PM" src="https://github.com/user-attachments/assets/78974c56-a4f7-447d-9f2b-3f97fa97d7e2">
<img width="1506" alt="Screenshot 2024-11-21 at 5 09 30 PM" src="https://github.com/user-attachments/assets/9c64599f-f9c1-4386-a835-0850a3d0bbbd">
