### ISSUE TITLE
希望项目组后续版本可以支持删除project

### ISSUE THREAD

**Issue by zmalqp189** [OpenSPG/openspg#405]
当前版本只有创建知识库的命令与可视化界面，想要删除某个project或者某个建模自己寻找了半天没有找到对应的方法和数据存储地址。希望后续版本可以支持上述的功能

**Comment by andylau-55** [comment]
Project deletion feature will be released soon

**Comment by andylau-55** [comment]
This feature has been released in version 0.5.1
https://github.com/OpenSPG/openspg/releases/tag/v0.5.1
