### ISSUE TITLE
SPGSchemaFacadeTest.groovy 错误 import

### ISSUE THREAD

**Issue by barkingx** [OpenSPG/openspg#409]
[SPGSchemaFacadeTest.groovy](https://github.com/OpenSPG/openspg/blob/918a1fb9ab3855f39a2d6ed0c1a2ba75dbfd70a0/server/test/src/test/java/com/antgroup/openspg/test/kgschema/SPGSchemaFacadeTest.groovy)

29 在 22ea3ee395dc2a5892be0543859599a479ed6f86 中被删除
https://github.com/OpenSPG/openspg/blob/918a1fb9ab3855f39a2d6ed0c1a2ba75dbfd70a0/server/test/src/test/java/com/antgroup/openspg/test/kgschema/SPGSchemaFacadeTest.groovy#L29

34, 36 在 0fde581e872345ab4b32f566b48a73fb6ef9456b 中被重命名
https://github.com/OpenSPG/openspg/blob/918a1fb9ab3855f39a2d6ed0c1a2ba75dbfd70a0/server/test/src/test/java/com/antgroup/openspg/test/kgschema/SPGSchemaFacadeTest.groovy#L34-L36

**Comment by andylau-55** [comment]
SPGSchemaFacadeTest.groovy is a test code and can be ignored or deleted during compilation.
