### ISSUE TITLE
新版本镜像拉取报错

### ISSUE THREAD

**Issue by RayL0221** [OpenSPG/openspg#410]
运行环境：windows 10 wsl
docker版本：24.0.7（非Docker Desktop）
运行命令：docker compose -f docker-compose.yml up -d
报错信息：WARN[0000] /mnt/e/LLM_project/openspg-master/dev/release/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Running 3/3
 ✘ neo4j Error  Get "https://spg-registry.cn-hangzhou.cr.aliyuncs.com/v2/": tls: failed to verify ...              0.2s
 ✘ server Error context canceled                                                                                   0.2s
 ✘ mysql Error  context canceled                                                                                   0.2s
Error response from daemon: Get "https://spg-registry.cn-hangzhou.cr.aliyuncs.com/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority

**Comment by caszkgui** [comment]
> tls: failed to verify certificate: x509: certificate signed by unknown authority

aliyun container registry of openspg is public to access.
may be you can try [install ca-certificates](https://stackoverflow.com/questions/75696690/how-to-resolve-tls-failed-to-verify-certificate-x509-certificate-signed-by-un) in your env.

**Comment by RayL0221** [comment]
> > tls: failed to verify certificate: x509: certificate signed by unknown authority
> 
> aliyun container registry of openspg is public to access. may be you can try [install ca-certificates](https://stackoverflow.com/questions/75696690/how-to-resolve-tls-failed-to-verify-certificate-x509-certificate-signed-by-un) in your env.

I have tried this method, but it did not work; I am still getting the same error.
