### ISSUE TITLE
按照文档示例抽取图谱，抽取结果只有点，没有边关系

### ISSUE THREAD

**Issue by jerryHo123** [OpenSPG/openspg#411]
![image](https://github.com/user-attachments/assets/803963cf-96f8-42fb-9fb8-ba1cb1b404c5)
跑的是示例文档jay.txt周杰伦相关信息，抽取出来的关系就只有一个source,请问是什么配置出问题了吗

**Comment by FuHTong** [comment]
你好，我和你的展示结果相同，请问这个展示问题解决了么？
