### ISSUE TITLE
Failed to download docker image

### ISSUE THREAD

**Issue by NiuBlibing** [OpenSPG/openspg#415]
```log
$ docker pull spg-registry.cn-hangzhou.cr.aliyuncs.com/spg/openspg-server:latest
Error response from daemon: Get "https://spg-registry.cn-hangzhou.cr.aliyuncs.com/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

This link is failed to download, is possible to provide other image url like `docker.io` or `gcr.io`?

**Comment by andylau-55** [comment]
Thank you for your feedback. Please replace `spg-registry.cn-hangzhou.cr.aliyuncs.com` with  `spg-registry.us-west-1.cr.aliyuncs.com` and pull
