### ISSUE TITLE
向量生成错误 20015

### ISSUE THREAD

**Issue by Peter-Rey** [OpenSPG/openspg#425]
根据  用户手册0.5 -> 3.1.1 新建知识库，向量配置，使用siliconflow 模型 BAAI/bge-m3，并更改为自己的key。
（测试模型接口与key 是正常的）
使用  用户手册0.5 中  -> txt文件示例：jay.text
(使用多个类型测试文档)
  ui页面 日志 反馈 向量生成错误。
请问按照手册安装，为什么会发生这种错误？我应该如何修改？
谢谢！
![微信截图_20241217092645](https://github.com/user-attachments/assets/82851624-62ff-4668-97c8-6acdcecc2afe)

**Comment by caszkgui** [comment]
> 根据 用户手册0.5 -> 3.1.1 新建知识库，向量配置，使用siliconflow 模型 BAAI/bge-m3，并更改为自己的key。 （测试模型接口与key 是正常的） 使用 用户手册0.5 中 -> txt文件示例：jay.text (使用多个类型测试文档) ui页面 日志 反馈 向量生成错误。 请问按照手册安装，为什么会发生这种错误？我应该如何修改？ 谢谢！ ![微信截图_20241217092645](https://private-user-images.githubusercontent.com/55908856/396329406-82851624-62ff-4668-97c8-6acdcecc2afe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDc1NjEsIm5iZiI6MTczNDQwNzI2MSwicGF0aCI6Ii81NTkwODg1Ni8zOTYzMjk0MDYtODI4NTE2MjQtNjJmZi00NjY4LTk3YzgtNmFjZGNlY2MyYWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzNDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MjQwZjEwMWRlNTQyNzZkMGYyM2RhMjM5NTVmNzg0ZWI0Nzk3NjU5NjE3MzljZGVkZDRiNTUwMTkxMzJiNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-mR127X5LdBMgnFZCB0aE-Nmjh57I7jZcxIHJ6ebQCg)

Could you paste your llm conf here? It looks like format of llm extraction is invalid.

**Comment by Peter-Rey** [comment]
> > 根据 用户手册0.5 -> 3.1.1 新建知识库，向量配置，使用siliconflow 模型 BAAI/bge-m3，并更改为自己的key。（测试模型接口与key 是正常的） 使用 用户手册0.5 中 -> txt文件示例：jay.text （使用多个类型测试文档） ui页面 日志 反馈 向量生成错误。请问按照手册安装，为什么会发生这种错误？我应该如何修改？ 谢谢！![微信截图_20241217092645](https://private-user-images.githubusercontent.com/55908856/396329406-82851624-62ff-4668-97c8-6acdcecc2afe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDc1NjEsIm5iZiI6MTczNDQwNzI2MSwicGF0aCI6Ii81NTkwODg1Ni8zOTYzMjk0MDYtODI4NTE2MjQtNjJmZi00NjY4LTk3YzgtNmFjZGNlY2MyYWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzNDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MjQwZjEwMWRlNTQyNzZkMGYyM2RhMjM5NTVmNzg0ZWI0Nzk3NjU5NjE3MzljZGVkZDRiNTUwMTkxMzJiNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-mR127X5LdBMgnFZCB0aE-Nmjh57I7jZcxIHJ6ebQCg)
> 
> 你能把你的 llm conf 贴在这里吗？llm 提取的格式似乎无效。
使用 用户手册0.5 中的 jay.text。 以下为内容：
周杰伦（Jay Chou），1979年1月18日出生于台湾省新北市，祖籍福建省永春县，华语流行乐男歌手、音乐人、演员、导演、编剧，毕业于淡江中学。
2000年，发行个人首张音乐专辑《Jay》。2001年，凭借专辑《范特西》奠定其融合中西方音乐的风格。2002年，举行“The One”世界巡回演唱会。2003年，成为美国《时代周刊》封面人物；同年，发行音乐专辑《叶惠美》，该专辑获得第15届台湾金曲奖最佳流行音乐演唱专辑奖。2004年，发行音乐专辑《七里香》，该专辑在亚洲的首月销量达到300万张；同年，获得世界音乐大奖中国区最畅销艺人奖。2005年，主演个人首部电影《头文字D》，并凭借该片获得第25届香港电影金像奖和第42届台湾电影金马奖的最佳新演员奖。2006年起，连续三年获得世界音乐大奖中国区最畅销艺人奖。
2007年，自编自导爱情电影《不能说的秘密》，同年，成立杰威尔音乐有限公司。2007年，凭借歌曲《青花瓷》获得第19届台湾金曲奖最佳作曲人奖。2007年，入选美国CNN“25位亚洲最具影响力人物”；同年，凭借专辑《魔杰座》获得第20届台湾金曲奖最佳国语男歌手奖。2010年，入选美国《Fast Company》评出的“全球百大创意人物”。2011年，凭借专辑《跨时代》获得第22届台湾金曲奖最佳国语男歌手奖。2012年，登上福布斯中国名人榜榜首。2014年，发行个人首张数字音乐专辑《哎呦，不错哦》。2023年，凭借专辑《最伟大的作品》成为首位获得国际唱片业协会“全球畅销专辑榜”冠军的华语歌手。
![微信截图_20241217130119](https://github.com/user-attachments/assets/1c0f4298-3455-44d5-928a-eb450e6ad0ec)

**Comment by Peter-Rey** [comment]
> > 根据 用户手册0.5 -> 3.1.1 新建知识库，向量配置，使用siliconflow 模型 BAAI/bge-m3，并更改为自己的key。 （测试模型接口与key 是正常的） 使用 用户手册0.5 中 -> txt文件示例：jay.text (使用多个类型测试文档) ui页面 日志 反馈 向量生成错误。 请问按照手册安装，为什么会发生这种错误？我应该如何修改？ 谢谢！ ![微信截图_20241217092645](https://private-user-images.githubusercontent.com/55908856/396329406-82851624-62ff-4668-97c8-6acdcecc2afe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDc1NjEsIm5iZiI6MTczNDQwNzI2MSwicGF0aCI6Ii81NTkwODg1Ni8zOTYzMjk0MDYtODI4NTE2MjQtNjJmZi00NjY4LTk3YzgtNmFjZGNlY2MyYWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzNDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MjQwZjEwMWRlNTQyNzZkMGYyM2RhMjM5NTVmNzg0ZWI0Nzk3NjU5NjE3MzljZGVkZDRiNTUwMTkxMzJiNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-mR127X5LdBMgnFZCB0aE-Nmjh57I7jZcxIHJ6ebQCg)
> 
> Could you paste your llm conf here? It looks like format of llm extraction is invalid.

使用 用户手册0.5 中的 jay.text。 以下为内容：
周杰伦（Jay Chou），1979年1月18日出生于台湾省新北市，祖籍福建省永春县，华语流行乐男歌手、音乐人、演员、导演、编剧，毕业于淡江中学。
2000年，发行个人首张音乐专辑《Jay》。2001年，凭借专辑《范特西》奠定其融合中西方音乐的风格。2002年，举行“The One”世界巡回演唱会。2003年，成为美国《时代周刊》封面人物；同年，发行音乐专辑《叶惠美》，该专辑获得第15届台湾金曲奖最佳流行音乐演唱专辑奖。2004年，发行音乐专辑《七里香》，该专辑在亚洲的首月销量达到300万张；同年，获得世界音乐大奖中国区最畅销艺人奖。2005年，主演个人首部电影《头文字D》，并凭借该片获得第25届香港电影金像奖和第42届台湾电影金马奖的最佳新演员奖。2006年起，连续三年获得世界音乐大奖中国区最畅销艺人奖。
2007年，自编自导爱情电影《不能说的秘密》，同年，成立杰威尔音乐有限公司。2007年，凭借歌曲《青花瓷》获得第19届台湾金曲奖最佳作曲人奖。2007年，入选美国CNN“25位亚洲最具影响力人物”；同年，凭借专辑《魔杰座》获得第20届台湾金曲奖最佳国语男歌手奖。2010年，入选美国《Fast Company》评出的“全球百大创意人物”。2011年，凭借专辑《跨时代》获得第22届台湾金曲奖最佳国语男歌手奖。2012年，登上福布斯中国名人榜榜首。2014年，发行个人首张数字音乐专辑《哎呦，不错哦》。2023年，凭借专辑《最伟大的作品》成为首位获得国际唱片业协会“全球畅销专辑榜”冠军的华语歌手。
![微信截图_20241217130119](https://github.com/user-attachments/assets/1c0f4298-3455-44d5-928a-eb450e6ad0ec)

**Comment by Peter-Rey** [comment]
建议删除用户手册0.5 中 左侧菜单 快速开始，4.KAG使用(开发者模式) 的文档，本人的使用中，使用推荐的商用API（deepseek ，siliconflow），至今无法走通流程。
后续 参考  用户手册0.5 中 左侧菜单 内置案例 -> 新场景快速开始，顺利走通流程。里面的内容和 文档中”快速开始“ 的内容高度重合。
所有建议删除或修改  用户手册0.5 中 左侧菜单 快速开始中的内容。
