### ISSUE TITLE
Version conflict on langchain-text-splitters between KAG and openspg-knext

### ISSUE THREAD

**Issue by lazydreamerbliss** [OpenSPG/openspg#428]
Using poetry will detect version conflict in dependency between KAG and openspg-knext

![image](https://github.com/user-attachments/assets/33d7cadf-f240-402e-bebf-d0afbc06c630)

**Comment by caszkgui** [comment]
> Using poetry will detect version conflict in dependency between KAG and openspg-knext
> 
> ![image](https://private-user-images.githubusercontent.com/8576808/397673391-33d7cadf-f240-402e-bebf-d0afbc06c630.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2ODU3NDYsIm5iZiI6MTczNDY4NTQ0NiwicGF0aCI6Ii84NTc2ODA4LzM5NzY3MzM5MS0zM2Q3Y2FkZi1mMjQwLTQwMmUtYmViZi1kMGFmYmMwNmM2MzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjBUMDkwNDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDdmZGM5OWJhODM4MzRmMWYzMTE5MDdhNGE1ODI4NWVmZjMwMmU5NjMzZDUwMTRjMmFlNTNlZjg1OGVkZThjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.pVsq67DlP67B1RLSjC4v9LyxiBmdrtMmBHpk3XznCAQ)

Could you pull the latest KAG code?
[KAG requirements](https://github.com/OpenSPG/KAG/blob/master/requirements.txt)
![image](https://github.com/user-attachments/assets/8fc59cf4-9f24-4dd6-b664-e3d799ef0a5b)

**Comment by lazydreamerbliss** [comment]
Thanks @caszkgui ! It was my fault on the out-dated KAG code, issue resolved after pull
