### ISSUE TITLE
中文文档首页链接待更新

### ISSUE THREAD

**Issue by yyri** [OpenSPG/openspg#431]
https://github.com/OpenSPG/openspg/blob/master/README_cn.md    中文文档首页的链接，如供应链案例，目前链接到的并非最新文档

**Comment by caszkgui** [comment]
Thanks for your feedback and pr.

This issue has been fixed through [https://github.com/OpenSPG/openspg/pull/432](https://github.com/OpenSPG/openspg/pull/432)
