### ISSUE TITLE
代码预编译报缺失类

### ISSUE THREAD

**Issue by Peter-Rey** [OpenSPG/openspg#434]
从github 拉取代码，使用 工具 idea，尝试过切换分支，master ，0.5.1，... ，都显示缺失类。
![image](https://github.com/user-attachments/assets/1d1f3abc-3961-474e-b5da-7ff5bdcd2125)

**Comment by Peter-Rey** [comment]
查找项目没有此路径，但是通过docker 下载的jar包，查看里面含有这些路径以及代码，可以将这些缺失代码上传吗？
![image](https://github.com/user-attachments/assets/7ce608a1-35e4-4858-80e1-8b4587d0facb)
![image](https://github.com/user-attachments/assets/a970d513-924c-4655-b206-12e1f4d65e19)

**Comment by caszkgui** [comment]
> 从github 拉取代码，使用 工具 idea，尝试过切换分支，master ，0.5.1，... ，都显示缺失类。 ![image](https://private-user-images.githubusercontent.com/55908856/398370022-1d1f3abc-3961-474e-b5da-7ff5bdcd2125.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMzI2OTQsIm5iZiI6MTczNTAzMjM5NCwicGF0aCI6Ii81NTkwODg1Ni8zOTgzNzAwMjItMWQxZjNhYmMtMzk2MS00NzRlLWI1ZGEtN2ZmNWJkY2QyMTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDA5MjYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMTYyYTdlZmE0NTIyMjdiMjI1NjY2ZmMyMTdhOWE5MjQ4YTE3Y2E1YjRmMmZjNzUwYzJkODgwYWI1NjczZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cU50vMTH8nQTZVph9MqW7pHAD41GwRbv66M3yEEldAg)

You can refer to [Install from sourceCode](https://openspg.yuque.com/ndx6g9/0.5/xfsvolpck828hlfr) to compile your local files.

![image](https://github.com/user-attachments/assets/c465b7ef-68f9-473c-a5c5-e444de18628c)

**Comment by Peter-Rey** [comment]
> > 从github 拉取代码，使用 工具 idea，尝试过切换分支，master ，0.5.1,...，都显示缺失类。![图像](https://private-user-images.githubusercontent.com/55908856/398370022-1d1f3abc-3961-474e-b5da-7ff5bdcd2125.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMzI2OTQsIm5iZiI6MTczNTAzMjM5NCwicGF0aCI6Ii81NTkwODg1Ni8zOTgzNzAwMjItMWQxZjNhYmMtMzk2MS00NzRlLWI1ZGEtN2ZmNWJkY2QyMTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDA5MjYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMTYyYTdlZmE0NTIyMjdiMjI1NjY2ZmMyMTdhOWE5MjQ4YTE3Y2E1YjRmMmZjNzUwYzJkODgwYWI1NjczZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cU50vMTH8nQTZVph9MqW7pHAD41GwRbv66M3yEEldAg)
> 
> 你可以参考 [从 sourceCode 安装](https://openspg.yuque.com/ndx6g9/0.5/xfsvolpck828hlfr) 来编译你的本地文件。
> 
> ![图像](https://private-user-images.githubusercontent.com/15404227/398378970-c465b7ef-68f9-473c-a5c5-e444de18628c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMzQ5MTYsIm5iZiI6MTczNTAzNDYxNiwicGF0aCI6Ii8xNTQwNDIyNy8zOTgzNzg5NzAtYzQ2NWI3ZWYtNjhmOS00NzNjLWE1YzUtZTQ0NGRlMTg2MjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDEwMDMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhY2JiYjBmMTY1YmU5NTdjMGVmMTU5ZGE1MDEwNDAxMGM3Mjg1MGViZDJjMDVjMTgyMjg5YTQ0ZDAzYjY0ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Cey3RLpj3h2UWp4-7xE6sw3rPtw6224n4JovqZGhUzQ)

谢谢你的帮助，我去尝试一下。
