### ISSUE TITLE
白皮书2.0计划啥时候发布呢

### ISSUE THREAD

**Issue by zhangcongxiao** [OpenSPG/openspg#45]
白皮书2.0计划啥时候发布呢

**Comment by leywar** [comment]
你好，感谢您对SPG的关注。结合当前的规划，OpenSPG社区近期会聚焦在易用性提升和应用落地，帮助用户更好的应用SPG能力。其中1月初有一次版本更新，发布SPG建模指导原则与最佳实践，完善SPG语义谓词的边界和约束，增强LLM联动的知识构建。 届时也会发布未来几个月的发布计划。SPG白皮书2.0的编制工作也在并行推进，具体的发布时间未来会在SPG动态中公告。

**Comment by leywar** [comment]
> 白皮书2.0计划啥时候发布呢

最近在应用SPG遇到的新问题，也可以进一步反馈哈，相关问题会高优排期。 也欢迎参与社区讨论和共建。
