### ISSUE TITLE
查询任务状态是QUEUE

### ISSUE THREAD

**Issue by zhangcongxiao** [OpenSPG/openspg#56]
knext builder submit 之后 knext builder get --id  一直显示QUEUE 是什么原因呢，查看Tugraph 和SPG日志都没有报错，请问可能是什么原因，可以怎么排查下？ 
![image](https://github.com/OpenSPG/openspg/assets/46892331/221d66d1-9971-4725-b2b2-37f1f887818e)

**Comment by baifuyu** [comment]
> knext builder submit 之后 knext builder get --id 一直显示QUEUE 是什么原因呢，查看Tugraph 和SPG日志都没有报错，请问可能是什么原因，可以怎么排查下？ ![image](https://private-user-images.githubusercontent.com/46892331/294176281-221d66d1-9971-4725-b2b2-37f1f887818e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MjE4MzAsIm5iZiI6MTcwNDQyMTUzMCwicGF0aCI6Ii80Njg5MjMzMS8yOTQxNzYyODEtMjIxZDY2ZDEtOTk3MS00NzI1LWIyYjItMzdmMWY4ODc4MThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDAyMjUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjYzZjNjUyMWQ3MzhhNDc3ZGQ4ZDFkZGExZWNhYTkxNzI0MWJmYmRjNTE3ZDFlNDAwNzFkNDlhYTg4MTMwNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xB_V-JlOEwDfPcNZ0K4VM47iVlST4rF7Vwfk1eRVqns)

目前后端有一个调度系统，会按照任务提交顺序按序执行构建任务。如果前面有任务执行过久会导致后续的任务排队。

在我们即将发布的0.0.2版本中架构会有一些调整，builder&reasoner将会作为引擎存在，直接类似于spark/flink本地运行，builder本地运行负责将数据转化为知识导入图谱，reasoner读取图谱数据进行本地推理。
