### ISSUE TITLE
启动openspg报错Whitelabel Error Page

### ISSUE THREAD

**Issue by lznext** [OpenSPG/openspg#6]
我按照官方教程安装后，能正常打开tugraph、elasticsearch，但无法打开openspg网站 http://localhost:8887/ 、release-openspg-mysql的网站 http://localhost:3306/ 。报错如下图
![spgerror](https://github.com/OpenSPG/openspg/assets/53247471/5a275c0e-3343-4b45-90f8-096a7a4bcd2d)
![spgsqlerror](https://github.com/OpenSPG/openspg/assets/53247471/2705016f-b5f7-42cc-bf56-6d946696b58f)
我的docker安装情况如图
![安装情况](https://github.com/OpenSPG/openspg/assets/53247471/b5e68e2b-b640-4108-ab36-4419d18f806d)
请各位大神指点。

**Comment by royzhao** [comment]
你好，
openspg网站 http://localhost:8887/ 
release-openspg-mysql的网站 http://localhost:3306/ 
这两个是服务端口，并没有前端页面，需要通过knext客户端交互的，后期会发布演示页面

**Comment by lznext** [comment]
> 你好， openspg网站 http://localhost:8887/ release-openspg-mysql的网站 http://localhost:3306/ 这两个是服务端口，并没有前端页面，需要通过knext客户端交互的，后期会发布演示页面

感谢回复
