### ISSUE TITLE
运行knext builder submit XX出现no module named "knext.client.model"

### ISSUE THREAD

**Issue by ZhiLyu** [OpenSPG/openspg#69]

**Comment by baifuyu** [comment]
@ZhiLyu hi可以提供更详细一点的报错信息上下文堆栈或者截图吗，这样我们更容易定位这个错误是服务端还是客户端抛的错以及当时报错时候的环境。

另外我们这2天将发布新的一版openspg，这一版本稳定性会有比较大的提升

**Comment by ZhiLyu** [comment]
![image](https://github.com/OpenSPG/openspg/assets/48907296/375db19e-555c-4071-aa11-091cc44b73f7)如图

**Comment by baifuyu** [comment]
> ![image](https://private-user-images.githubusercontent.com/48907296/295118146-375db19e-555c-4071-aa11-091cc44b73f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MTAxMTYsIm5iZiI6MTcwNDgwOTgxNiwicGF0aCI6Ii80ODkwNzI5Ni8yOTUxMTgxNDYtMzc1ZGIxOWUtNTU1Yy00MDcxLWFhMTEtMDkxY2M0NGI3M2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE0MTY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNjRhZTdiYzNiOTFjMjY3NzcyY2FlY2E1NWI0NGY5MWE0NmVjODc1YjEwMjBjMGI3MjZjYzczMTc4ZDJhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w2gcYaIebxBaLsWvRnkR2o5nt-h8Mshd2ZFM8rnQQsY)如图

应该是本地没有安装knext。我们已经发布了新一版的openspg，服务端安装和客户端安装都方便了许多。
knext builder submit命令换成了 knext builder execute。可以尝试下使用这一版，稳定性会好一些
