### ISSUE TITLE
运行Demo时，提示“Error: Unable to access jarfile C:\Program Files\python38\lib\site-packages\knext\lib\builder-runner-local-0.0.1-SNAPSHOT-jar-with-dependencies.jar”

### ISSUE THREAD

**Issue by w00125533** [OpenSPG/openspg#85]
Step1：按示例创建Demo工程（https://spg.openkg.cn/tutorial/knext/command）

Step2：运行“1.5 知识加工”章节时出错：knext builder execute Company

提示出错：“Error: Unable to access jarfile C:\Program Files\python38\lib\site-packages\knext\lib\builder-runner-local-0.0.1-SNAPSHOT-jar-with-dependencies.jar”

**Comment by baifuyu** [comment]
> Step1：按示例创建Demo工程（[https://spg.openkg.cn/tutorial/knext/command）](https://spg.openkg.cn/tutorial/knext/command%EF%BC%89)
> 
> Step2：运行“1.5 知识加工”章节时出错：knext builder execute Company
> 
> 提示出错：“Error: Unable to access jarfile C:\Program Files\python38\lib\site-packages\knext\lib\builder-runner-local-0.0.1-SNAPSHOT-jar-with-dependencies.jar”

hi，客户端的安装需要使用docker安装方式，可以参考下这里，https://spg.openkg.cn/tutorial/installation/installation。

**Comment by w00125533** [comment]
客户端的方式确实可以运行，但在第一个版本中，knext可以直接在windows上运行，能用IDE单步调试，很方便。

**Comment by baifuyu** [comment]
> 客户端的方式确实可以运行，解决了能运行的问题。但在第一个版本中，knext可以直接在windows上运行，能用IDE单步调试，相当方便。 我尝试在windows下安装后，通过两个调整尝试在windows上运行： 1）修改__init__.py的localhost变量： LOCAL_SCHEMA_URL = "http://X.X.X.X:8887" LOCAL_GRAPH_STORE_URL = "tugraph://X.X.X.X:9090?graphName=default&timeout=50000&accessId=admin&accessKey=73@TuGraph" LOCAL_SEARCH_ENGINE_URL = "elasticsearch://X.X.X.X:9200?scheme=http"
> 
> 2）在site-packages\knext\lib增加两个Jar包： builder-runner-local-0.0.1-SNAPSHOT-jar-with-dependencies.jar reasoner-local-runner-0.0.1-SNAPSHOT-jar-with-dependencies.jar
> 
> 大部分命令可以运行，但运行部分推理任务时（比如风控的 knext builder execute App）时，出现了需要安装pemja的提示。 ![image](https://private-user-images.githubusercontent.com/22139807/297086736-d875b83a-8ca4-42b5-806e-20f4ba9531e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1OTY0NzcsIm5iZiI6MTcwNjU5NjE3NywicGF0aCI6Ii8yMjEzOTgwNy8yOTcwODY3MzYtZDg3NWI4M2EtOGNhNC00MmI1LTgwNmUtMjBmNGJhOTUzMWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA2MjkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MDY2ZmQzN2QyOThmMzMxZmQ2MDY1MWJmOGFhZDkzZjdiODUxMTBiZTE5MzNmM2NjMzEwY2IyNjFkZWIwNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6FyFL2WlYHGhqXoHv1EwGN38mZx6qnU991fFWLrTz3Q)
> 
> 尝试按提示安装VS14.0后，再安装依然有错（如下图）；进一步官网了解pemja只支持windows和MacOS的whl：
> 
> ![image](https://private-user-images.githubusercontent.com/22139807/297088823-7f889eb5-6cdc-4842-8660-108b12017689.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1OTY0NzcsIm5iZiI6MTcwNjU5NjE3NywicGF0aCI6Ii8yMjEzOTgwNy8yOTcwODg4MjMtN2Y4ODllYjUtNmNkYy00ODQyLTg2NjAtMTA4YjEyMDE3Njg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA2MjkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0YzNlMmJjNzhjMGY3NTczMjY4MWE1Y2U3OWNiZTUxZmM4OGE1ZTIxZjlhODAwM2Y5MGEwYjk2ZjgxNTZmZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W49PvKvzT8MSX0uhlYuPhhK8p5JjnMUDMTfUp_myxk8)
> 
> 期待knext 支持在windows运行~！

是的，目前将几个 jar 包以及相关环境打包到docker的原因有以下几点：

1. pemja包不支持在window下安装，导致java无法调用python代码
2. pypi无法上传超过100M的包，builder&reasoner的包将近了200M导致上传pypi时失败

目前都将pemja和jar包都打包进docker了支持在docker中运行，后续我们再调研下上述方案如何替代
