### ISSUE TITLE
运行riskmining示例项目的“knext schema commit ”时，出现错误：FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: D:\\openspg-0.0.2-beta2\\python\\knext\\knext\\examples\\riskmining\\schema\\riskmining_schema_helper.py.tmpl' -> 'D:\\openspg-0.0.2-beta2\\python\\knext\\knext\\examples\\riskmining\\schema\\riskmining_schema_helper.py'

### ISSUE THREAD

**Issue by w00125533** [OpenSPG/openspg#86]
Step1：在python\knext\knext\examples\riskmining下，项目初始化：knext project create --prj_path .
Step2:  运行知识建模：knext schema commit ，抛出异常：
`Traceback (most recent call last):
  File "C:\Program Files\python38\Lib\site-packages\knext\command\knext_cli.py", line 83, in <module>
    _main()
  File "C:\Program Files\python38\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\python38\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\python38\lib\site-packages\knext\command\exception.py", line 29, in invoke
    return super().invoke(ctx)
  File "C:\Program Files\python38\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\python38\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\python38\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\python38\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files\python38\lib\site-packages\knext\command\sub_command\schema.py", line 73, in commit_schema
    ml.export_schema_python(tplfile)
  File "C:\Program Files\python38\lib\site-packages\knext\client\marklang\schema_ml.py", line 1312, in export_schema_python
    render_template(Path(filename).parent, Path(filename).name, **metadata)
  File "C:\Program Files\python38\lib\site-packages\knext\common\template.py", line 32, in render_template
    path_obj.rename(render_path)
  File "C:\Program Files\python38\lib\pathlib.py", line 1366, in rename
    self._accessor.rename(self, target)
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'D:\\01.dt-code\\openspg-0.0.2-beta2\\python\\knext\\knext\\examples\\riskmining\\schema\\riskmining_schema_helper.py.tmpl' -> 'D:\\01.dt-code\\openspg-0.0.2-beta2\\python\\knext\\knext\\examples\\riskmining\\schema\\riskmining_schema_helper.py'
`

**Comment by baifuyu** [comment]
> Step1：在python\knext\knext\examples\riskmining下，项目初始化：knext project create --prj_path . Step2: 运行知识建模：knext schema commit ，抛出异常： `Traceback (most recent call last): File "C:\Program Files\python38\Lib\site-packages\knext\command\knext_cli.py", line 83, in <module> _main() File "C:\Program Files\python38\lib\site-packages\click\core.py", line 1157, in __call__ return self.main(*args, **kwargs) File "C:\Program Files\python38\lib\site-packages\click\core.py", line 1078, in main rv = self.invoke(ctx) File "C:\Program Files\python38\lib\site-packages\knext\command\exception.py", line 29, in invoke return super().invoke(ctx) File "C:\Program Files\python38\lib\site-packages\click\core.py", line 1688, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "C:\Program Files\python38\lib\site-packages\click\core.py", line 1688, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "C:\Program Files\python38\lib\site-packages\click\core.py", line 1434, in invoke return ctx.invoke(self.callback, **ctx.params) File "C:\Program Files\python38\lib\site-packages\click\core.py", line 783, in invoke return __callback(*args, **kwargs) File "C:\Program Files\python38\lib\site-packages\knext\command\sub_command\schema.py", line 73, in commit_schema ml.export_schema_python(tplfile) File "C:\Program Files\python38\lib\site-packages\knext\client\marklang\schema_ml.py", line 1312, in export_schema_python render_template(Path(filename).parent, Path(filename).name, **metadata) File "C:\Program Files\python38\lib\site-packages\knext\common\template.py", line 32, in render_template path_obj.rename(render_path) File "C:\Program Files\python38\lib\pathlib.py", line 1366, in rename self._accessor.rename(self, target) FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'D:\\01.dt-code\\openspg-0.0.2-beta2\\python\\knext\\knext\\examples\\riskmining\\schema\\riskmining_schema_helper.py.tmpl' -> 'D:\\01.dt-code\\openspg-0.0.2-beta2\\python\\knext\\knext\\examples\\riskmining\\schema\\riskmining_schema_helper.py' `

尝试客户端使用docker方式安装哈。https://spg.openkg.cn/tutorial/installation/installation

**Comment by w00125533** [comment]
OK，已解决
