### ISSUE TITLE
看到openSPG 可以便于嵌入各类图存储和图引擎，想了解一下细节

### ISSUE THREAD

**Issue by 652994331** [OpenSPG/openspg#89]
一些图数据库/引擎比如 Neo4j, graphscope 这些， 想问下 openSPG 是否支持。使用中有哪些注意点呢，谢谢

**Comment by baifuyu** [comment]
> 一些图数据库/引擎比如 Neo4j, graphscope 这些， 想问下 openSPG 是否支持。使用中有哪些注意点呢，谢谢

目前openspg使用图数据库来存储知识图谱的数据，使用图计算引擎来做推理计算。目前不支持neo4j，graphscope，但我们抽象了对应的接口，可以适配到这些图数据库/引擎，其中图计算引擎的适配可以参考 https://spg.openkg.cn/tutorial/reasoner/rdg。图存储引擎的适配可以参考下代码中的tugraph实现。

**Comment by 652994331** [comment]
@baifuyu  谢谢你的回答， 还想了解下，openSPG 生成的schema  ， 他可以用什么形式留存出来吗，这样的schema 可以被比如Tigergraph, graphscope 这些图计算引擎直接使用吗。问题也就是 是否可以单独摘出 实体提取，构建schema这部分能力，后续接上别的图数据库/图引擎。谢谢

**Comment by baifuyu** [comment]
> @baifuyu 谢谢你的回答， 还想了解下，openSPG 生成的schema ， 他可以用什么形式留存出来吗，这样的schema 可以被比如Tigergraph, graphscope 这些图计算引擎直接使用吗。问题也就是 是否可以单独摘出 实体提取，构建schema这部分能力，后续接上别的图数据库/图引擎。谢谢

openspg的声明式schema是我们定义的一种语法，语法解释可以参考这里 https://spg.openkg.cn/tutorial/schema/dsl。

当用户定义好一个业务的schema后，提交到openspg，openspg底层有一层适配层，将openspg 的schema转化为具体图数据库的schema。

然后reasoner模块消费openspg的schema，驱动底层的图计算引擎从图数据库中查询出来数据开始推理计算。

大致的流程是这样子的，单独从openspg摘出schema这部分能力，对接其他的图数据库和图引擎不太行，还是得将图数据库或者图引擎根据openspg的接口定义适配上来。

**Comment by zcq19952816121** [comment]
产品模式进入 http://127.0.0.1:8887界面后显示要登录，请问这里的登录账号密码是哪个呀？

**Comment by caszkgui** [comment]
> 产品模式进入 [http://127.0.0.1:8887界面后显示要登录，请问这里的登录账号密码是哪个呀？](http://127.0.0.1:8887%E7%95%8C%E9%9D%A2%E5%90%8E%E6%98%BE%E7%A4%BA%E8%A6%81%E7%99%BB%E5%BD%95%EF%BC%8C%E8%AF%B7%E9%97%AE%E8%BF%99%E9%87%8C%E7%9A%84%E7%99%BB%E5%BD%95%E8%B4%A6%E5%8F%B7%E5%AF%86%E7%A0%81%E6%98%AF%E5%93%AA%E4%B8%AA%E5%91%80%EF%BC%9F)

![image](https://github.com/user-attachments/assets/1fc2d3a2-fbdc-43a8-82d4-7830d849c07d)
